-- Recipes Chunk 2
local Chunk = {
    ['Food_Meat_Stew'] = { Inputs = { {Item='Mushroom',Count=1}, {Item='Carrot',Count=1}, {Item='Raw_Meat',Count=1} } },
    ['Food_Fried_Soy_Beans'] = { Inputs = { {Item='Carrot',Count=1}, {Item='Mushroom',Count=1}, {Item='Bean',Count=1} } },
    ['Food_Roasted_Vegetables'] = { Inputs = { {Item='Pumpkin',Count=1}, {Item='Squash',Count=1}, {Item='Carrot',Count=1} } },
    ['Food_Fruit_Salad'] = { Inputs = { {Item='Watermelon',Count=1}, {Item='Berry',Count=1} } },
    ['Food_Wild_Salad'] = { Inputs = { {Item='Pumpkin',Count=1}, {Item='Squash',Count=1} } },
    ['Food_Creamed_Corn'] = { Inputs = { {Item='Animal_Fat',Count=1}, {Item='Corn',Count=1} } },
    ['Animal_Fat'] = { Inputs = { {Item='Raw_Meat',Count=1} } },
    ['Pastry'] = { Inputs = { {Item='Animal_Fat',Count=1}, {Item='Flour',Count=1} } },
    ['Fruit_Pie'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Berry',Count=1}, {Item='Watermelon',Count=1} } },
    ['Meat_Pie'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Mushroom',Count=1}, {Item='Pumpkin',Count=1}, {Item='Raw_Meat',Count=1} } },
    ['Vegetable_Pie'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Squash',Count=1}, {Item='Bean',Count=1}, {Item='Corn',Count=1} } },
    ['Pumpkin_Bread'] = { Inputs = { {Item='Pumpkin',Count=1}, {Item='Dough_Bread',Count=1} } },
    ['Pickled_Carrot'] = { Inputs = { {Item='Carrot',Count=1}, {Item='Glass_Jar',Count=1}, {Item='Salt',Count=5} } },
    ['Hunter_Head_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Advanced_Leather',Count=3}, {Item='Rope',Count=4}, {Item='Epoxy',Count=8} } },
    ['Hunter_Chest_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=5}, {Item='Advanced_Leather',Count=6}, {Item='Rope',Count=6}, {Item='Epoxy',Count=16} } },
    ['Hunter_Arms_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Advanced_Leather',Count=4}, {Item='Epoxy',Count=4} } },
    ['Hunter_Legs_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=4}, {Item='Advanced_Leather',Count=4}, {Item='Rope',Count=6}, {Item='Epoxy',Count=8} } },
    ['Hunter_Feet_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=1}, {Item='Advanced_Leather',Count=2}, {Item='Rope',Count=4}, {Item='Epoxy',Count=4} } },
    ['Electric_Dehumidifier'] = { Inputs = { {Item='Aluminium',Count=20}, {Item='Glass',Count=15}, {Item='Electronics',Count=35}, {Item='Steel_Screw',Count=12}, {Item='Composites',Count=20} } },
    ['Worklamp_OmniDirectional'] = { Inputs = { {Item='Aluminium',Count=10}, {Item='Glass',Count=5}, {Item='Composites',Count=5}, {Item='Electronics',Count=2} } },
    ['Heater_Large'] = { Inputs = { {Item='Aluminium',Count=40}, {Item='Electronics',Count=20}, {Item='Steel_Screw',Count=8}, {Item='Carbon_Fiber',Count=8} } },
    ['Cooler_Large'] = { Inputs = { {Item='Aluminium',Count=40}, {Item='Electronics',Count=20}, {Item='Steel_Screw',Count=8}, {Item='Carbon_Fiber',Count=8} } },
    ['Biofuel_Generator'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Copper_Wire',Count=40}, {Item='Electronics',Count=12}, {Item='Steel_Screw',Count=20}, {Item='Glass',Count=2} } },
    ['SplineTool_Electricity'] = { Inputs = { {Item='Copper_Wire',Count=50}, {Item='Gold_Wire',Count=50}, {Item='Carbon_Fiber',Count=4} } },
    ['SplineTool_Water'] = { Inputs = { {Item='Copper_Wire',Count=50}, {Item='Gold_Wire',Count=50}, {Item='Platinum_Shealth',Count=4} } },
    ['Solar_Panel'] = { Inputs = { {Item='Electronics',Count=30}, {Item='Steel_Screw',Count=10}, {Item='Glass',Count=60}, {Item='Composites',Count=18}, {Item='Carbon_Fiber',Count=8} } },
    ['Chemistry_Bench'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Wood_Refined',Count=30}, {Item='Electronics',Count=20}, {Item='Composites',Count=10}, {Item='Glass',Count=10} } },
    ['Composter_Electric'] = { Inputs = { {Item='Composites',Count=20}, {Item='Concrete_Mix',Count=100}, {Item='Steel_Ingot',Count=60}, {Item='Steel_Screw',Count=20}, {Item='Electronics',Count=20} } },
    ['Masonry_Bench_T4'] = { Inputs = { {Item='Steel_Ingot',Count=60}, {Item='Composites',Count=10}, {Item='Concrete_Mix',Count=100}, {Item='Steel_Screw',Count=10}, {Item='Electronics',Count=20} } },
    ['Carpentry_Bench_T4'] = { Inputs = { {Item='Steel_Ingot',Count=60}, {Item='Composites',Count=10}, {Item='Refined_Metal',Count=40}, {Item='Steel_Screw',Count=10}, {Item='Electronics',Count=20} } },
    ['GreenTea_Drink'] = { Inputs = { {Item='GreenTea',Count=5} } },
    ['WildTea_Drink'] = { Inputs = { {Item='WildTea',Count=5} } },
    ['Cocoa_Drink'] = { Inputs = { {Item='Cocoa',Count=5} } },
    ['Coffee_Drink'] = { Inputs = { {Item='Coffee',Count=5} } },
    ['IceWater_Drink'] = { Inputs = { {Item='Ice',Count=10} } },
    ['Basic_Backpack'] = { Inputs = { {Item='Rope',Count=8}, {Item='Leather',Count=20}, {Item='Fiber',Count=10} } },
    ['T3_Backpack'] = { Inputs = { {Item='Rope',Count=8}, {Item='Advanced_Leather',Count=18}, {Item='Epoxy',Count=8} } },
    ['Bait'] = { Inputs = { {Item='Raw_Meat',Count=1}, {Item='Animal_Fat',Count=2} } },
    ['Poisoned_Bait'] = { Inputs = { {Item='Bait',Count=1}, {Item='Poison_Paste',Count=1} } },
    ['Mission_Thruster'] = { Inputs = { {Item='Mission_Ship_Thruster_Part',Count=1}, {Item='Epoxy',Count=5}, {Item='Titanium_Ingot',Count=10} } },
    ['Mission_Navigation'] = { Inputs = { {Item='Mission_Ship_Navigation_Part',Count=1}, {Item='Electronics',Count=5}, {Item='Carbon_Fiber',Count=10} } },
    ['Buffalo_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Buffalo_Head',Count=1} } },
    ['AlphaWolf_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Alphawolf_Head',Count=1} } },
    ['ConiferWolf_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='ConiferWolf_Head',Count=1} } },
    ['SnowWolf_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='SnowWolf_Head',Count=1} } },
    ['DesertWolf_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='DesertWolf_Head',Count=1} } },
    ['Mammoth_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Mammoth_Head',Count=1} } },
    ['SnowLeopard_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='SnowLeopard_Head',Count=1} } },
    ['Deep_Mining_Drill_Biofuel'] = { Inputs = { {Item='Steel_Ingot',Count=12}, {Item='Refined_Copper',Count=10}, {Item='Epoxy',Count=12}, {Item='Electronics',Count=10}, {Item='Copper_Wire',Count=50} } },
    ['Deep_Mining_Drill_Electric'] = { Inputs = { {Item='Aluminium',Count=25}, {Item='Electronics',Count=15}, {Item='Steel_Screw',Count=12}, {Item='Titanium_Ingot',Count=8}, {Item='Carbon_Fiber',Count=8} } },
    ['Basic_Fertilizer'] = { Inputs = { {Item='Spoiled_Plants',Count=10}, {Item='Dirt',Count=10} } },
    ['Basic_Fertilizer_2'] = { Inputs = { {Item='Guano',Count=1}, {Item='Dirt',Count=10} } },
    ['Yield_Fertilizer'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Sulfur',Count=5} } },
    ['Speed_Fertilizer'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Silica',Count=5} } },
    ['Gunpowder_talent'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Charcoal',Count=1} } },
    ['Farmers_Shotgun'] = { Inputs = { {Item='Wood',Count=15}, {Item='Leather',Count=10}, {Item='Steel_Ingot',Count=10}, {Item='Tree_Sap',Count=10} } },
    ['Composter_Wood'] = { Inputs = { {Item='Wood',Count=25}, {Item='Stone',Count=10}, {Item='Tree_Sap',Count=10}, {Item='Sulfur',Count=5} } },
    ['Iron_Crop_Plot'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Copper_Wire',Count=20}, {Item='Sulfur',Count=12}, {Item='Steel_Screw',Count=8}, {Item='Dirt',Count=20} } },
    ['Hydro_Crop_Plot'] = { Inputs = { {Item='Composites',Count=20}, {Item='Steel_Ingot',Count=25}, {Item='Steel_Screw',Count=10}, {Item='Electronics',Count=10}, {Item='Copper_Wire',Count=20}, {Item='Dirt',Count=20} } },
    ['Water_Pump'] = { Inputs = { {Item='Steel_Ingot',Count=24}, {Item='Electronics',Count=4}, {Item='Concrete_Mix',Count=20}, {Item='Steel_Screw',Count=16} } },
    ['Water_Sprinkler'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Copper_Wire',Count=4} } },
    ['Drying_Rack'] = { Inputs = { {Item='Wood',Count=50}, {Item='Stick',Count=25}, {Item='Fiber',Count=50} } },
    ['Cooked_Giant_Steak'] = { Inputs = { {Item='Giant_Steak',Count=1} } },
    ['Cooked_Fatty_TBone'] = { Inputs = { {Item='Fatty_Tbone',Count=1} } },
    ['Cooked_Gamey_Meat'] = { Inputs = { {Item='Gamey_Meat',Count=1} } },
    ['Cooked_Soft_Meat'] = { Inputs = { {Item='Soft_Meat',Count=1} } },
    ['Cooked_Stringy_Meat'] = { Inputs = { {Item='Stringy_Meat',Count=1} } },
    ['Cooked_White_Meat'] = { Inputs = { {Item='White_Meat',Count=1} } },
    ['Cooked_Bacon'] = { Inputs = { {Item='Raw_Bacon',Count=1} } },
    ['Crispy_Bacon'] = { Inputs = { {Item='Raw_Bacon',Count=1}, {Item='Animal_Fat',Count=1} } },
    ['Dried_Giant_Steak'] = { Inputs = { {Item='Giant_Steak',Count=1} } },
    ['Dried_Fatty_Tbone'] = { Inputs = { {Item='Fatty_Tbone',Count=1} } },
    ['Dried_Gamey_Meat'] = { Inputs = { {Item='Gamey_Meat',Count=1} } },
    ['Dried_Soft_Meat'] = { Inputs = { {Item='Soft_Meat',Count=1} } },
    ['Dried_Stringy_Meat'] = { Inputs = { {Item='Stringy_Meat',Count=1} } },
    ['Dried_White_Meat'] = { Inputs = { {Item='White_Meat',Count=1} } },
    ['Caveworm_Knife'] = { Inputs = { {Item='Wood',Count=2}, {Item='Leather',Count=2}, {Item='Caveworm_Scale',Count=5}, {Item='Poison_Sack',Count=5} } },
    ['Caveworm_Spear'] = { Inputs = { {Item='Wood',Count=16}, {Item='Leather',Count=4}, {Item='Caveworm_Scale',Count=10}, {Item='Poison_Sack',Count=10} } },
    ['Caveworm_Arrow'] = { Inputs = { {Item='Stick',Count=5}, {Item='Leather',Count=5}, {Item='Caveworm_Scale',Count=2}, {Item='Poison_Sack',Count=5} } },
    ['Caveworm_Bow'] = { Inputs = { {Item='Wood',Count=10}, {Item='Leather',Count=25}, {Item='Caveworm_Scale',Count=15}, {Item='Poison_Sack',Count=10} } },
    ['Mission_Laser'] = { Inputs = { {Item='Mission_Laser_Part_1',Count=1}, {Item='Mission_Laser_Part_2',Count=1}, {Item='Mission_Laser_Part_3',Count=1} } },
    ['Solar_Panel_Repair'] = { Inputs = { {Item='Mission_Broken_Solar_Panel',Count=1}, {Item='Glass',Count=15}, {Item='Steel_Screw',Count=2} } },
    ['Bandage_Cooling'] = { Inputs = { {Item='Fiber',Count=40}, {Item='Oxite',Count=4}, {Item='Charcoal',Count=10} } },
    ['Deep_Ore_Scanner'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Electronics',Count=4}, {Item='Steel_Screw',Count=16}, {Item='Copper_Wire',Count=30} } },
    ['Cave_Scanner'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Gold_Wire',Count=25}, {Item='Iron_Nail',Count=12}, {Item='Copper_Wire',Count=25} } },
    ['Mission_Gyroscope'] = { Inputs = { {Item='Mission_Ship_Gyro_Broken',Count=1}, {Item='Refined_Copper',Count=10}, {Item='Refined_Metal',Count=5} } },
    ['Rustic_Decoration_Bench'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Wood',Count=50}, {Item='Stone',Count=12}, {Item='Leather',Count=20} } },
    ['Rustic_Bench'] = { Inputs = { {Item='Wood',Count=10}, {Item='Stick',Count=20}, {Item='Iron_Nail',Count=8} } },
    ['Rustic_Bookshelf'] = { Inputs = { {Item='Wood',Count=25}, {Item='Iron_Nail',Count=10} } },
    ['Rustic_Cabinet'] = { Inputs = { {Item='Wood',Count=30}, {Item='Iron_Nail',Count=20} } },
    ['Rustic_Candles'] = { Inputs = { {Item='Animal_Fat',Count=1}, {Item='Stick',Count=2} } },
    ['Rustic_Candles_1'] = { Inputs = { {Item='Beeswax',Count=2}, {Item='Stick',Count=2} } },
    ['Rustic_CoffeeTable'] = { Inputs = { {Item='Stick',Count=10}, {Item='Wood',Count=2}, {Item='Fiber',Count=10} } },
    ['Rustic_CouchLarge'] = { Inputs = { {Item='Stick',Count=30}, {Item='Fiber',Count=50} } },
    ['Rustic_CouchMedium'] = { Inputs = { {Item='Stick',Count=20}, {Item='Fiber',Count=30} } },
    ['Rustic_DiningChair'] = { Inputs = { {Item='Wood',Count=5}, {Item='Stick',Count=10}, {Item='Fiber',Count=10} } },
    ['Rustic_LivingChair'] = { Inputs = { {Item='Stick',Count=15}, {Item='Fiber',Count=20} } },
    ['Rustic_NightStand'] = { Inputs = { {Item='Wood',Count=15}, {Item='Stick',Count=5}, {Item='Iron_Nail',Count=5} } },
    ['Rustic_Pot'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Stick',Count=10}, {Item='Sulfur',Count=5} } },
    ['Rustic_Stool'] = { Inputs = { {Item='Wood',Count=5}, {Item='Stick',Count=10} } },
    ['Rustic_Table'] = { Inputs = { {Item='Wood',Count=20}, {Item='Stick',Count=20}, {Item='Iron_Nail',Count=10} } },
    ['Rustic_TableLarge'] = { Inputs = { {Item='Wood',Count=80}, {Item='Stick',Count=60}, {Item='Iron_Nail',Count=20} } },
    ['Rustic_TableRound'] = { Inputs = { {Item='Wood',Count=20}, {Item='Stick',Count=20}, {Item='Iron_Nail',Count=10} } },
    ['Rustic_Wardrobe'] = { Inputs = { {Item='Wood',Count=30}, {Item='Iron_Nail',Count=15} } },
    ['Rustic_WardrobeNarrow'] = { Inputs = { {Item='Wood',Count=30}, {Item='Iron_Nail',Count=15} } },
    ['Rustic_Bed'] = { Inputs = { {Item='Wood',Count=20}, {Item='Fur',Count=30}, {Item='Leather',Count=10}, {Item='Iron_Nail',Count=10} } },
    ['Rustic_Statue'] = { Inputs = { {Item='Refined_Metal',Count=5}, {Item='Refined_Copper',Count=5} } },
    ['Rustic_Dresser'] = { Inputs = { {Item='Wood',Count=30}, {Item='Iron_Nail',Count=15} } },
    ['Extractor_Biofuel'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Gold_Wire',Count=25}, {Item='Copper_Nail',Count=10} } },
    ['Radar_Biofuel'] = { Inputs = { {Item='Refined_Metal',Count=12}, {Item='Gold_Wire',Count=50}, {Item='Iron_Nail',Count=8}, {Item='Glass',Count=2}, {Item='Copper_Wire',Count=50} } },
    ['Mission_Prototype_Laser'] = { Inputs = { {Item='Mission_Broken_Prototype_Laser',Count=1}, {Item='Rope',Count=5}, {Item='Tree_Sap',Count=5}, {Item='Leather',Count=1} } },
    ['Scale_Head_Armor'] = { Inputs = { {Item='Bone',Count=5}, {Item='Leather',Count=10}, {Item='Sandworm_Scale',Count=10} } },
    ['Scale_Chest_Armor'] = { Inputs = { {Item='Bone',Count=25}, {Item='Leather',Count=12}, {Item='Sandworm_Scale',Count=20} } },
    ['Scale_Arms_Armor'] = { Inputs = { {Item='Bone',Count=5}, {Item='Leather',Count=4}, {Item='Sandworm_Scale',Count=6} } },
    ['Scale_Legs_Armor'] = { Inputs = { {Item='Bone',Count=15}, {Item='Leather',Count=9}, {Item='Sandworm_Scale',Count=10} } },
    ['Scale_Feet_Armor'] = { Inputs = { {Item='Bone',Count=5}, {Item='Leather',Count=6}, {Item='Sandworm_Scale',Count=6} } },
    ['Scorpion_Head_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=4}, {Item='Leather',Count=15}, {Item='Scorpion_Carapace',Count=10} } },
    ['Scorpion_Chest_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Leather',Count=18}, {Item='Scorpion_Carapace',Count=20} } },
    ['Scorpion_Legs_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=8}, {Item='Leather',Count=12}, {Item='Scorpion_Carapace',Count=10} } },
    ['Scorpion_Arms_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=4}, {Item='Leather',Count=8}, {Item='Scorpion_Carapace',Count=6} } },
    ['Scorpion_Feet_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=2}, {Item='Leather',Count=15}, {Item='Scorpion_Carapace',Count=4} } },
    ['Vapour_Condenser'] = { Inputs = { {Item='Composites',Count=20}, {Item='Glass',Count=12}, {Item='Electronics',Count=10}, {Item='Steel_Screw',Count=8}, {Item='Copper_Wire',Count=40} } },
    ['Deer_Statue_Decoration_Wood'] = { Inputs = { {Item='Wood',Count=10}, {Item='Condensed_Enzymes',Count=1} } },
    ['Scorpion_Statue_Decoration_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['PolarBear_Statue_Decoration_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['Bear_Statue_Decoration_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['Mission_STYX_D_Research2_Containment'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Steel_Ingot',Count=8} } },
    ['Mission_STYX_D_Research2_Catalyst'] = { Inputs = { {Item='Oxite',Count=40}, {Item='Ice',Count=30}, {Item='Carbon_Fiber',Count=4} } },
    ['Mission_STYX_D_Research2_Bomb'] = { Inputs = { {Item='Platinum_Ingot',Count=6}, {Item='Steel_Screw',Count=12}, {Item='Leather',Count=20}, {Item='Concrete_Mix',Count=4}, {Item='Mission_STYX_D_Research2_BombParts',Count=1} } },
    ['Mission_Full_Enzyme_Containment_Unit'] = { Inputs = { {Item='Mission_Empty_Enzyme_Container',Count=1}, {Item='Digested_Enzymes',Count=100} } },
    ['Glass_Floor'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Glass',Count=20}, {Item='Epoxy',Count=6} } },
    ['Raw_Meat_Bacon'] = { Inputs = { {Item='Raw_Bacon',Count=1} } },
    ['Raw_Meat_Soft'] = { Inputs = { {Item='Soft_Meat',Count=1} } },
    ['Raw_Meat_White'] = { Inputs = { {Item='White_Meat',Count=1} } },
    ['Raw_Meat_Stringy'] = { Inputs = { {Item='Stringy_Meat',Count=1} } },
    ['Raw_Meat_Gamey'] = { Inputs = { {Item='Gamey_Meat',Count=1} } },
    ['Raw_Meat_Tbone'] = { Inputs = { {Item='Fatty_Tbone',Count=1} } },
    ['Raw_Meat_Steak'] = { Inputs = { {Item='Giant_Steak',Count=1} } },
    ['Alteration_Bench'] = { Inputs = { {Item='Refined_Metal',Count=24}, {Item='Wood_Refined',Count=10}, {Item='Epoxy',Count=6}, {Item='Rope',Count=6}, {Item='Copper_Nail',Count=40} } },
    ['Advanced_Alteration_Bench'] = { Inputs = { {Item='Steel_Ingot',Count=30}, {Item='Glass',Count=4}, {Item='Electronics',Count=10}, {Item='Concrete_Mix',Count=25}, {Item='Steel_Screw',Count=8} } },
    ['Attachment_Melee_Damage_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Melee_Damage_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Tool_Attachment_Melee_Damage_1',Count=1} } },
    ['Attachment_Melee_Attack_Speed_1'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=4} } },
    ['Attachment_Melee_Attack_Speed_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Composites',Count=1}, {Item='Tool_Attachment_Attack_Speed_1',Count=1} } },
    ['Attachment_Prime_Meat_Chance_1'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Fur',Count=8}, {Item='Epoxy',Count=4} } },
    ['Attachment_Prime_Meat_Chance_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Steel_Screw',Count=8}, {Item='Wood_Refined',Count=8}, {Item='Knife_Attachment_Prime_Meat_Chance_1',Count=1} } },
    ['Attachment_Bone_Yield_1'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Fur',Count=4} } },
    ['Attachment_Bone_Yield_2'] = { Inputs = { {Item='Epoxy',Count=4}, {Item='Carbon_Fiber',Count=1}, {Item='Bone',Count=8}, {Item='Knife_Attachment_Bone_Yield_1',Count=1} } },
    ['Attachment_Leather_Yield_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Fur',Count=8} } },
    ['Attachment_Leather_Yield_2'] = { Inputs = { {Item='Leather',Count=8}, {Item='Carbon_Fiber',Count=1}, {Item='Steel_Screw',Count=6}, {Item='Knife_Attachment_Leather_Yield_1',Count=1} } },
    ['Attachment_Gold_Yield_1'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Copper_Nail',Count=8} } },
    ['Attachment_Gold_Yield_2'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Carbon_Fiber',Count=1}, {Item='Pickaxe_Attachment_Gold_Yield_1',Count=1} } },
    ['Attachment_Copper_Yield_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Steel_Screw',Count=8} } },
    ['Attachment_Copper_Yield_2'] = { Inputs = { {Item='Refined_Copper',Count=4}, {Item='Carbon_Fiber',Count=1}, {Item='Pickaxe_Attachment_Copper_Yield_1',Count=1} } },
    ['Attachment_Platnium_Yield_1'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Iron_Nail',Count=8} } },
    ['Attachment_Platnium_Yield_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Carbon_Fiber',Count=1}, {Item='Pickaxe_Attachment_Platnium_Yield_1',Count=1} } },
    ['Attachment_Reaping_Yield_1'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Steel_Ingot',Count=2} } },
    ['Attachment_Reaping_Yield_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=4}, {Item='Sickle_Attachment_Reaping_Yield_1',Count=1} } },
    ['Attachment_Repair_Time_1'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Epoxy',Count=4} } },
    ['Attachment_Repair_Time_2'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Carbon_Fiber',Count=1}, {Item='Hammer_Attachment_Repair_1',Count=1} } },
    ['Black_Wolf_Knife'] = { Inputs = { {Item='Black_Wolf_Tooth',Count=6}, {Item='Leather',Count=4}, {Item='Metal_Ore',Count=4}, {Item='Iron_Nail',Count=2} } },
    ['Black_Wolf_Arrow'] = { Inputs = { {Item='Wood',Count=1}, {Item='Metal_Ore',Count=1}, {Item='Black_Wolf_Tooth',Count=2} } },
    ['Attachment_Melee_Bleed_Attacks'] = { Inputs = { {Item='Platinum_Ingot',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Raw_Meat',Count=2} } },
    ['Attachment_Melee_Poison_Attacks'] = { Inputs = { {Item='Platinum_Ingot',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Poison_Sack',Count=2} } },
    ['Attachment_Melee_Electroshock_Attacks'] = { Inputs = { {Item='Platinum_Ingot',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Gold_Ore',Count=1} } },
    ['Attachment_Titanium_Yeild_1'] = { Inputs = { {Item='Refined_Copper',Count=4}, {Item='Steel_Screw',Count=8} } },
    ['Attachment_Titanium_Yeild_2'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Carbon_Fiber',Count=1}, {Item='Pickaxe_Attachment_Titanium_1',Count=1} } },
    ['Target_Dummy'] = { Inputs = { {Item='Epoxy',Count=10}, {Item='Stick',Count=50}, {Item='Silica',Count=5} } },
    ['Bullseye_Target'] = { Inputs = { {Item='Wood',Count=10}, {Item='Stick',Count=25}, {Item='Berry',Count=3}, {Item='Refined_Metal',Count=2} } },
    ['Attachment_Cave_Resistance_1'] = { Inputs = { {Item='Refined_Copper',Count=4}, {Item='Charcoal',Count=50} } },
    ['Attachment_Cave_Resistance_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Charcoal',Count=50}, {Item='Helmet_Attachment_Cave_Resistance_1',Count=1} } },
    ['Attachment_Storm_Resistance_1'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Leather',Count=10}, {Item='Glass',Count=2} } },
    ['Attachment_Storm_Resistance_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Leather',Count=10}, {Item='Helmet_Attachment_Storm_Resistance_1',Count=1} } },
    ['Attachment_Poison_Water_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Glass',Count=6} } },
    ['Attachment_Poison_Water_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Epoxy',Count=4}, {Item='Helmet_Attachment_Poison_Water_1',Count=1} } },
    ['Attachment_Tool_Use_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=8}, {Item='Epoxy',Count=2} } },
    ['Attachment_Tool_Use_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Steel_Screw',Count=6}, {Item='Arms_Attachment_Tool_Use_1',Count=1} } },
    ['Attachment_Movement_Bonus_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Copper_Nail',Count=8}, {Item='Leather',Count=4} } },
    ['Attachment_Movement_Bonus_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Steel_Ingot',Count=2}, {Item='Feet_Legs_Attachment_Movement_Bonus_1',Count=1} } },
    ['Attachment_Fall_Resistance_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Steel_Screw',Count=8}, {Item='Leather',Count=6} } },
    ['Attachment_Fall_Resistance_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Epoxy',Count=2}, {Item='Rope',Count=4}, {Item='Feet_Arms_Attachment_Fall_Resistance_1',Count=1} } },
    ['Attachment_Stealth_Movement_1'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Leather',Count=8}, {Item='Fur',Count=6} } },
    ['Attachment_Stealth_Movement_2'] = { Inputs = { {Item='Carbon_Fiber',Count=2}, {Item='Iron_Nail',Count=8}, {Item='Feet_Body_Legs_Attachment_Stealth_Movement_1',Count=1} } },
    ['Attachment_Carrying_Bonus_1'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Leather',Count=8}, {Item='Rope',Count=4} } },
    ['Attachment_Carrying_Bonus_2'] = { Inputs = { {Item='Carbon_Fiber',Count=2}, {Item='Leather',Count=8}, {Item='Rope',Count=4}, {Item='Body_Legs_Arms_Attachment_Carrying_Bonus_1',Count=1} } },
    ['Attachment_Regen_Resistance_1'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Refined_Metal',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Epoxy',Count=2} } },
    ['Attachment_Regen_Resistance_2'] = { Inputs = { {Item='Carbon_Fiber',Count=2}, {Item='Titanium_Ingot',Count=2}, {Item='Composites',Count=2}, {Item='Epoxy',Count=2}, {Item='Body_Legs_Attachment_Regen_Resistance_1',Count=1} } },
    ['Attachment_Boss_Tracker'] = { Inputs = { {Item='Titanium_Ingot',Count=2}, {Item='Electronics',Count=4} } },
    ['Attachment_Stomach_Capacity'] = { Inputs = { {Item='Composites',Count=4}, {Item='Electronics',Count=4} } },
    ['Attachment_Chest_StomachCapacity_2'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Electronics',Count=4}, {Item='Body_Attachment_Stomach_Capacity',Count=1} } },
    ['Attachment_Quick_Healing'] = { Inputs = { {Item='Composites',Count=2}, {Item='Epoxy',Count=4}, {Item='Rope',Count=4} } },
    ['Hard_Leather_Head_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=1}, {Item='Advanced_Leather',Count=6} } },
    ['Hard_Leather_Chest_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=3}, {Item='Advanced_Leather',Count=13} } },
    ['Hard_Leather_Arms_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=1}, {Item='Advanced_Leather',Count=7} } },
    ['Hard_Leather_Legs_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Advanced_Leather',Count=10} } },
    ['Hard_Leather_Feet_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=1}, {Item='Advanced_Leather',Count=4} } },
    ['Attachment_ADS_Upgrade_1'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=1} } },
    ['Attachment_ADS_Upgrade_2'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Glass',Count=1}, {Item='Ranged_Weapon_Attachment_ADS_Upgrade_1',Count=1} } },
    ['Attachment_Ammo_Highlight_1'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Steel_Ingot',Count=2} } },
    ['Attachment_Ammo_Highlight_2'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Aluminium',Count=2}, {Item='Ranged_Weapon_Attachment_Ammo_Highlight_1',Count=1} } },
    ['Attachment_Ranged_Weapon_Wear_1'] = { Inputs = { {Item='Wood_Refined',Count=4}, {Item='Rope',Count=4}, {Item='Steel_Ingot',Count=2} } },
    ['Attachment_Ranged_Weapon_Wear_2'] = { Inputs = { {Item='Rope',Count=4}, {Item='Aluminium',Count=4}, {Item='Ranged_Weapon_Attachment_Wear_1',Count=1} } },
    ['Attachment_Ranged_Weapon_Stealth_1'] = { Inputs = { {Item='Fur',Count=8}, {Item='Epoxy',Count=2}, {Item='Steel_Ingot',Count=2} } },
    ['Attachment_Ranged_Weapon_Stealth_2'] = { Inputs = { {Item='Leather',Count=4}, {Item='Epoxy',Count=2}, {Item='Platinum_Ingot',Count=2}, {Item='Ranged_Weapon_Attachment_Stealth_1',Count=1} } },
    ['Attachment_Ranged_Weapon_Lightweight_1'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Epoxy',Count=2} } },
    ['Attachment_Ranged_Weapon_Lightweight_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Steel_Screw',Count=8}, {Item='Ranged_Weapon_Attachment_Lightweight_1',Count=1} } },
    ['Attachment_Ranged_Weapon_Economic_1'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Steel_Ingot',Count=2} } },
    ['Attachment_Ranged_Weapon_Economic_2'] = { Inputs = { {Item='Leather',Count=8}, {Item='Aluminium',Count=2}, {Item='Ranged_Weapon_Attachment_Economic_1',Count=1} } },
    ['Attachment_Ranged_Weapon_Rapid_Fire'] = { Inputs = { {Item='Composites',Count=2}, {Item='Carbon_Fiber',Count=1} } },
    ['Attachment_Ranged_Weapon_Damage_1'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Epoxy',Count=2} } },
    ['Attachment_Ranged_Weapon_Damage_2'] = { Inputs = { {Item='Titanium_Ingot',Count=2}, {Item='Epoxy',Count=2}, {Item='Steel_Screw',Count=4}, {Item='Ranged_Weapon_Attachment_Damage_1',Count=1} } },
    ['Attachment_Extended_Mag'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Leather',Count=4}, {Item='Epoxy',Count=4} } },
    ['Attachment_Ranged_Weapon_Speed_1'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Steel_Ingot',Count=2}, {Item='Rope',Count=2} } },
    ['Attachment_Ranged_Weapon_Speed_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Epoxy',Count=4}, {Item='Ranged_Weapon_Attachment_Speed_1',Count=1} } },
    ['Attachment_Additional_Projectiles'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Rope',Count=4} } },
    ['Attachment_Ranged_Weapons_Sniper_1'] = { Inputs = { {Item='Titanium_Ingot',Count=2}, {Item='Glass',Count=1} } },
    ['Attachment_Ranged_Weapons_Sniper_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Glass',Count=1}, {Item='Ranged_Weapon_Attachment_Sniper_1',Count=1} } },
    ['Attachment_Ranged_Weapons_Animal_Highlight'] = { Inputs = { {Item='Electronics',Count=1}, {Item='Titanium_Ingot',Count=2}, {Item='Glass',Count=2} } },
    ['Attachment_Ranged_Weapon_Increased_Spread'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Epoxy',Count=4}, {Item='Leather',Count=4} } },
    ['Attachment_Ranged_Weapon_Decreased_Spread_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Leather',Count=4} } },
    ['Attachment_Ranged_Weapon_Decreased_Spread_2'] = { Inputs = { {Item='Titanium_Ingot',Count=2}, {Item='Carbon_Fiber',Count=1}, {Item='Epoxy',Count=2}, {Item='Ranged_Weapon_Attachment_Decreased_Spread_1',Count=1} } },
    ['Advanced_Armor_Bench'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Wood',Count=6}, {Item='Epoxy',Count=8}, {Item='Rope',Count=4}, {Item='Steel_Screw',Count=40} } },
    ['Electric_Armor_Bench'] = { Inputs = { {Item='Steel_Ingot',Count=30}, {Item='Electronics',Count=8}, {Item='Concrete_Mix',Count=15}, {Item='Steel_Screw',Count=18} } },
    ['Cured_Leather'] = { Inputs = { {Item='Leather',Count=6}, {Item='Tree_Sap',Count=2} } },
    ['Cured_Leather_2'] = { Inputs = { {Item='Leather',Count=6}, {Item='Tree_Sap',Count=2} } },
    ['Platinum_Wave'] = { Inputs = { {Item='Fiber',Count=30}, {Item='Platinum_Shealth',Count=2} } },
    ['Advanced_Cloth_Head_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=4} } },
    ['Advanced_Cloth_Chest_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=10} } },
    ['Advanced_Cloth_Arms_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=4} } },
    ['Advanced_Cloth_Legs_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=8} } },
    ['Advanced_Cloth_Feet_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=2} } },
    ['Saddle_Standard'] = { Inputs = { {Item='Leather',Count=14}, {Item='Fur',Count=6}, {Item='Rope',Count=2} } },
    ['Animal_Bed'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Fur',Count=20} } },
    ['Food_Trough'] = { Inputs = { {Item='Wood',Count=60}, {Item='Stick',Count=8}, {Item='Iron_Nail',Count=16} } },
    ['Water_Trough'] = { Inputs = { {Item='Wood',Count=60}, {Item='Stick',Count=8}, {Item='Iron_Nail',Count=16} } },
    ['Spotlight'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Glass',Count=6}, {Item='Copper_Wire',Count=10} } },
    ['Ice_Borer'] = { Inputs = { {Item='Steel_Ingot',Count=12}, {Item='Refined_Copper',Count=24}, {Item='Epoxy',Count=12}, {Item='Electronics',Count=10} } },
    ['Process_Red_Exotic'] = { Inputs = { {Item='Exotic_Red_Raw',Count=1} } },
    ['Shield_Wooden'] = { Inputs = { {Item='Wood',Count=15}, {Item='Fiber',Count=20}, {Item='Leather',Count=5}, {Item='Refined_Metal',Count=3} } },
    ['Clay_Brick'] = { Inputs = { {Item='Clay',Count=1} } },
    ['Clay_Brick_Beam'] = { Inputs = { {Item='Clay_Brick',Count=25}, {Item='Tree_Sap',Count=5} } },
    ['Clay_Brick_Floor'] = { Inputs = { {Item='Clay_Brick',Count=30}, {Item='Tree_Sap',Count=5} } },
    ['Clay_Brick_Wall'] = { Inputs = { {Item='Clay_Brick',Count=30}, {Item='Tree_Sap',Count=5} } },
    ['Clay_Brick_Halfpiece'] = { Inputs = { {Item='Clay_Brick',Count=15}, {Item='Tree_Sap',Count=3} } },
    ['Clay_Brick_Half_Pitch'] = { Inputs = { {Item='Clay_Brick',Count=15}, {Item='Tree_Sap',Count=3} } },
    ['Clay_Brick_Wall_Angle'] = { Inputs = { {Item='Clay_Brick',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Clay_Brick_Ramp'] = { Inputs = { {Item='Clay_Brick',Count=30}, {Item='Tree_Sap',Count=5} } },
    ['Clay_Brick_Roof_Corner'] = { Inputs = { {Item='Clay_Brick',Count=15}, {Item='Tree_Sap',Count=3} } },
    ['Clay_Brick_Window'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Steel_Rebar',Count=3} } },
    ['Clay_Brick_Door'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Steel_Rebar',Count=5} } },
    ['Clay_Brick_TrapDoor'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Steel_Rebar',Count=4} } },
    ['Clay_Brick_Railing'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Wood_Refined',Count=5} } },
    ['Metal_Sledgehammer'] = { Inputs = { {Item='Wood',Count=10}, {Item='Rope',Count=8}, {Item='Refined_Metal',Count=15} } },
    ['Mission_Communicator_T2'] = { Inputs = { {Item='Wood',Count=10}, {Item='Rope',Count=8}, {Item='Refined_Metal',Count=15} } },
    ['Mission_Communicator_T3'] = { Inputs = { {Item='Gold_Wire',Count=25}, {Item='Copper_Wire',Count=50}, {Item='Steel_Ingot',Count=25}, {Item='Aluminium',Count=30} } },
    ['Mission_Communicator_T4'] = { Inputs = { {Item='Glass',Count=25}, {Item='Composites',Count=30}, {Item='Gold_Wire',Count=100}, {Item='Platinum_Shealth',Count=150}, {Item='Titanium_Plate',Count=20}, {Item='Copper_Wire',Count=50}, {Item='Electronics',Count=6} } },
    ['Saddle_Standard_Bag'] = { Inputs = { {Item='Advanced_Leather',Count=8}, {Item='Platinum_Weave',Count=4}, {Item='Rope',Count=2} } },
    ['Bone_Tusks'] = { Inputs = { {Item='Mammoth_Tusk',Count=1} } },
    ['Wood_Railing_Gate'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Wood',Count=8} } },
    ['Exotic_Delivery_Interface'] = { Inputs = { {Item='Wood',Count=10}, {Item='Rope',Count=8}, {Item='Refined_Metal',Count=7}, {Item='Refined_Copper',Count=7} } },
    ['Stone_Throwing_Knife'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Stick',Count=4}, {Item='Stone',Count=4} } },
    ['Bone_Throwing_Knife'] = { Inputs = { {Item='Wood',Count=2}, {Item='Leather',Count=2}, {Item='Bone',Count=15} } },
    ['Metal_Throwing_Knife'] = { Inputs = { {Item='Wood',Count=4}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=5}, {Item='Iron_Nail',Count=4} } },
    ['Titanium_Throwing_Knife'] = { Inputs = { {Item='Carbon_Fiber',Count=2}, {Item='Steel_Screw',Count=4}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=6} } },
    ['Steel_Throwing_Knife'] = { Inputs = { {Item='Wood',Count=4}, {Item='Epoxy',Count=2}, {Item='Steel_Ingot',Count=6}, {Item='Iron_Nail',Count=4} } },
    ['Platinum_Throwing_Knife'] = { Inputs = { {Item='Wood_Refined',Count=4}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=8} } },
    ['Sandworm_Throwing_Knife'] = { Inputs = { {Item='Wood',Count=4}, {Item='Leather',Count=4}, {Item='Sandworm_Scale',Count=4} } },
    ['Caveworm_Throwing_Knife'] = { Inputs = { {Item='Wood',Count=4}, {Item='Leather',Count=4}, {Item='Caveworm_Scale',Count=4}, {Item='Poison_Sack',Count=4} } },
    ['Black_Wolf_Throwing_Knife'] = { Inputs = { {Item='Black_Wolf_Tooth',Count=4}, {Item='Leather',Count=4}, {Item='Metal_Ore',Count=2}, {Item='Iron_Nail',Count=6} } },
    ['Wood_Throwing_Spear'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=16} } },
    ['Bone_Throwing_Spear'] = { Inputs = { {Item='Wood',Count=10}, {Item='Leather',Count=4}, {Item='Bone',Count=40} } },
    ['Metal_Throwing_Spear'] = { Inputs = { {Item='Wood',Count=5}, {Item='Leather',Count=5}, {Item='Refined_Metal',Count=20} } },
    ['Steel_Throwing_Spear'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=5}, {Item='Steel_Ingot',Count=20} } },
    ['Carbon_Throwing_Spear'] = { Inputs = { {Item='Refined_Copper',Count=4}, {Item='Carbon_Fiber',Count=20}, {Item='Epoxy',Count=4} } },
    ['Platinum_Throwing_Spear'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=20} } },
    ['Titanium_Throwing_Spear'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=20} } },
    ['Composite_Throwing_Spear'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Aluminium',Count=4}, {Item='Composites',Count=20} } },
    ['Sandworm_Throwing_Spear'] = { Inputs = { {Item='Wood',Count=10}, {Item='Leather',Count=4}, {Item='Sandworm_Scale',Count=10} } },
    ['Caveworm_Throwing_Spear'] = { Inputs = { {Item='Wood',Count=10}, {Item='Leather',Count=4}, {Item='Caveworm_Scale',Count=10}, {Item='Poison_Sack',Count=10} } },
    ['Platinum_Crossbow'] = { Inputs = { {Item='Wood_Refined',Count=18}, {Item='Advanced_Leather',Count=2}, {Item='Platinum_Ingot',Count=20}, {Item='Epoxy',Count=8}, {Item='Steel_Screw',Count=8} } },
    ['Titanium_Crossbow'] = { Inputs = { {Item='Wood_Refined',Count=24}, {Item='Advanced_Leather',Count=8}, {Item='Titanium_Ingot',Count=20}, {Item='Epoxy',Count=12}, {Item='Steel_Screw',Count=16} } },
    ['Fortification_Wood_Wall'] = { Inputs = { {Item='Wood',Count=50}, {Item='Iron_Nail',Count=18}, {Item='Rope',Count=12} } },
    ['Fortification_Wood_Spikes'] = { Inputs = { {Item='Wood',Count=80}, {Item='Rope',Count=6} } },
    ['Fortification_Wood_Gate'] = { Inputs = { {Item='Wood',Count=40}, {Item='Refined_Metal',Count=6}, {Item='Rope',Count=4} } },
    ['Fortification_Wood_Walkways'] = { Inputs = { {Item='Wood',Count=20}, {Item='Iron_Nail',Count=18} } },
    ['Food_Cooked_Potato'] = { Inputs = { {Item='Potato',Count=1} } },
    ['Food_Cooked_Tomato'] = { Inputs = { {Item='Tomato',Count=1} } },
    ['Food_Cooked_Soy_Bean'] = { Inputs = { {Item='Bean',Count=1} } },
    ['Food_Hearty_Salad'] = { Inputs = { {Item='Tomato',Count=1}, {Item='Bean',Count=1} } },
    ['Food_Tomato_Soup'] = { Inputs = { {Item='Tomato',Count=3} } },
    ['Pickled_Tomato'] = { Inputs = { {Item='Tomato',Count=1}, {Item='Glass_Jar',Count=1}, {Item='Salt',Count=5} } },
    ['Food_Potato_Carrot_Fries'] = { Inputs = { {Item='Potato',Count=1}, {Item='Carrot',Count=1}, {Item='Animal_Fat',Count=1} } },
    ['Potato_Bread'] = { Inputs = { {Item='Potato',Count=1}, {Item='Dough_Bread',Count=1} } },
    ['Shepherds_Pie'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Raw_Meat',Count=1}, {Item='Potato',Count=1}, {Item='Tomato',Count=1} } },
    ['Electric_Stove'] = { Inputs = { {Item='Composites',Count=10}, {Item='Aluminium',Count=20}, {Item='Glass',Count=12}, {Item='Electronics',Count=10}, {Item='Steel_Screw',Count=8}, {Item='Copper_Wire',Count=40} } },
    ['Advanced_Kitchen_Bench'] = { Inputs = { {Item='Composites',Count=2}, {Item='Aluminium',Count=20}, {Item='Concrete_Mix',Count=10}, {Item='Steel_Screw',Count=8}, {Item='Stone',Count=100} } },
    ['Advanced_Kitchen_Storage'] = { Inputs = { {Item='Composites',Count=2}, {Item='Aluminium',Count=10}, {Item='Concrete_Mix',Count=10}, {Item='Steel_Screw',Count=8}, {Item='Stone',Count=100} } },
    ['Advanced_Kitchen_Sink'] = { Inputs = { {Item='Composites',Count=4}, {Item='Aluminium',Count=30}, {Item='Concrete_Mix',Count=8}, {Item='Steel_Screw',Count=16} } },
    ['Health_Enhancement_Tonic'] = { Inputs = { {Item='Lily',Count=3}, {Item='Flour',Count=1}, {Item='Yeast',Count=1}, {Item='Tree_Sap',Count=1} } },
    ['Stamina_Enhancement_Tonic'] = { Inputs = { {Item='Reed_Flower',Count=3}, {Item='Organic_Resin',Count=1}, {Item='Yeast',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Sustenence_Enhancement_Tonic'] = { Inputs = { {Item='Sponge',Count=2}, {Item='Reed_Flower',Count=1}, {Item='Lily',Count=1}, {Item='Organic_Resin',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Strength_Enhancement_Tonic'] = { Inputs = { {Item='Organic_Resin',Count=2}, {Item='Wheat',Count=2}, {Item='Lily',Count=1}, {Item='Crushed_Bone',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Waterwheel'] = { Inputs = { {Item='Organic_Resin',Count=25}, {Item='Stone',Count=50}, {Item='Wood',Count=100}, {Item='Steel_Ingot',Count=10}, {Item='Electronics',Count=10}, {Item='Copper_Nail',Count=50} } },
    ['Dropship_Grenade_T4'] = { Inputs = { {Item='Composites',Count=3}, {Item='Electronics',Count=2}, {Item='Steel_Screw',Count=4}, {Item='Refined_Metal',Count=4}, {Item='Gunpowder',Count=2} } },
    ['Landmine'] = { Inputs = { {Item='Composites',Count=2}, {Item='Electronics',Count=1}, {Item='Copper_Nail',Count=12}, {Item='Gunpowder',Count=4}, {Item='Volatile_Substance',Count=1} } },
    ['Saddle_Wood_Cart'] = { Inputs = { {Item='Saddle_Standard',Count=1}, {Item='Wood',Count=80}, {Item='Iron_Nail',Count=15}, {Item='Rope',Count=20}, {Item='Epoxy',Count=10}, {Item='Wood_Refined',Count=50} } },
    ['Exotic_Harvester'] = { Inputs = { {Item='Platinum_Ingot',Count=10}, {Item='Electronics',Count=3}, {Item='Copper_Wire',Count=50}, {Item='Composites',Count=3}, {Item='Platinum_Shealth',Count=30} } },
    ['Exotic_Processor'] = { Inputs = { {Item='Composites',Count=15}, {Item='Electronics',Count=5}, {Item='Titanium_Ingot',Count=10}, {Item='Shaped_Obsidian',Count=5}, {Item='Platinum_Shealth',Count=30} } },
    ['Basic_Fishing_Rod'] = { Inputs = { {Item='Stick',Count=25}, {Item='Fiber',Count=10} } },
    ['Fishing_Bench'] = { Inputs = { {Item='Wood',Count=25}, {Item='Rope',Count=10}, {Item='Refined_Metal',Count=5}, {Item='Copper_Nail',Count=12} } },
    ['Wooden_Fishing_Rod'] = { Inputs = { {Item='Wood',Count=15}, {Item='Epoxy',Count=2}, {Item='Rope',Count=5} } },
    ['Refined_Wood_Fishing_Rod'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Refined_Metal',Count=2}, {Item='Rope',Count=5} } },
    ['Basic_Fishing_Trap'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Iron_Nail',Count=10}, {Item='Rope',Count=5} } },
    ['Advanced_Fishing_Trap'] = { Inputs = { {Item='Copper_Nail',Count=10}, {Item='Platinum_Weave',Count=5}, {Item='Refined_Metal',Count=10} } },
    ['Fish_Wall_Mount'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Refined_Copper',Count=5}, {Item='Iron_Nail',Count=10} } },
    ['Aquarium'] = { Inputs = { {Item='Glass',Count=20}, {Item='Wood_Refined',Count=10}, {Item='Refined_Gold',Count=8}, {Item='Electronics',Count=5} } },
    ['Advanced_Aquarium'] = { Inputs = { {Item='Glass',Count=30}, {Item='Platinum_Ingot',Count=10}, {Item='Refined_Gold',Count=8}, {Item='Electronics',Count=5}, {Item='Carbon_Paste',Count=12} } },
    ['Large_Advanced_Aquarium'] = { Inputs = { {Item='Glass',Count=50}, {Item='Platinum_Ingot',Count=15}, {Item='Refined_Gold',Count=12}, {Item='Electronics',Count=6}, {Item='Carbon_Paste',Count=20} } },
    ['Thumper'] = { Inputs = { {Item='Titanium_Ingot',Count=8}, {Item='Electronics',Count=6}, {Item='Steel_Screw',Count=18}, {Item='Composites',Count=12}, {Item='Concrete_Mix',Count=8}, {Item='Epoxy',Count=14} } },
    ['Salting_Station'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Stone',Count=25}, {Item='Wood',Count=50}, {Item='Charcoal',Count=25} } },
    ['Deep_Freeze'] = { Inputs = { {Item='Aluminium',Count=20}, {Item='Electronics',Count=15}, {Item='Carbon_Fiber',Count=10}, {Item='Steel_Screw',Count=15}, {Item='Platinum_Ingot',Count=20} } },
    ['Layered_Plating'] = { Inputs = { {Item='Concrete_Mix',Count=20}, {Item='Aluminium',Count=16}, {Item='Titanium_Ingot',Count=10}, {Item='Composites',Count=24}, {Item='Steel_Ingot',Count=40} } },
    ['Tackle_Box'] = { Inputs = { {Item='Wood',Count=10}, {Item='Tree_Sap',Count=10}, {Item='Iron_Nail',Count=5} } },
    ['Wood_Lure'] = { Inputs = { {Item='Wood',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Fiber',Count=2} } },
    ['Bone_Lure'] = { Inputs = { {Item='Bone',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Fiber',Count=2} } },
    ['Wolf_Lure'] = { Inputs = { {Item='Fur',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Leather',Count=2} } },
    ['Bark_Lure'] = { Inputs = { {Item='Stick',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Fiber',Count=2} } },
    ['Gorse_Flower_Lure'] = { Inputs = { {Item='WildTea',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Tree_Sap',Count=2} } },
    ['Iron_Lure'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Blue_Reed_Lure'] = { Inputs = { {Item='Reed_Flower',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Yeast_Lure'] = { Inputs = { {Item='Yeast',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Fiber_Lure'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Rotten_Meat_Lure'] = { Inputs = { {Item='Spoiled_Meat',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Refined_Wood_Lure'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Advanced_Iron_Lure'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Reed_Flower_Lure'] = { Inputs = { {Item='Reed_Flower',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Cured_Leather_Lure'] = { Inputs = { {Item='Advanced_Leather',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Dogtags_Lure'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Platinum_Weave',Count=1} } },
    ['Rubber_Lure'] = { Inputs = { {Item='Epoxy',Count=4}, {Item='Iron_Nail',Count=2}, {Item='Platinum_Weave',Count=1} } },
    ['Poison_Sack_Lure'] = { Inputs = { {Item='Poison_Sack',Count=4}, {Item='Copper_Nail',Count=2}, {Item='Platinum_Weave',Count=1} } },
    ['White_Jelly_Lure'] = { Inputs = { {Item='Animal_Fat',Count=2}, {Item='Iron_Nail',Count=2}, {Item='Platinum_Weave',Count=1} } },
    ['Black_Wolf_Lure'] = { Inputs = { {Item='Black_Wolf_Tooth',Count=1}, {Item='Copper_Nail',Count=2}, {Item='Platinum_Weave',Count=1} } },
    ['Scorpion_Lure'] = { Inputs = { {Item='Scorpion_Tail',Count=1}, {Item='Copper_Nail',Count=2}, {Item='Platinum_Weave',Count=1} } },
    ['Gold_Ore_Lure'] = { Inputs = { {Item='Gold_Ore',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Gold_Wire'] = { Inputs = { {Item='Refined_Gold',Count=1} } },
    ['Copper_Wire'] = { Inputs = { {Item='Refined_Copper',Count=1} } },
    ['Dried_Tomato'] = { Inputs = { {Item='Tomato',Count=1} } },
    ['Dried_Avocado'] = { Inputs = { {Item='Avocado',Count=1} } },
    ['Dried_Rhubarb'] = { Inputs = { {Item='Rhubarb',Count=1} } },
    ['Food_Cooked_Rhubarb'] = { Inputs = { {Item='Rhubarb',Count=1} } },
    ['Food_Cooked_Kumara'] = { Inputs = { {Item='Kumara',Count=1} } },
    ['Food_Stuffed_Avocado'] = { Inputs = { {Item='Avocado',Count=1}, {Item='Bean',Count=1} } },
    ['Food_Mixed_Berries'] = { Inputs = { {Item='Berry',Count=1}, {Item='Strawberry',Count=1} } },
    ['Food_Rhubarb_Stew'] = { Inputs = { {Item='Rhubarb',Count=1}, {Item='Corn',Count=1}, {Item='Berry',Count=1} } },
    ['Food_Fried_Chunky_Vegetables'] = { Inputs = { {Item='Kumara',Count=1}, {Item='Animal_Fat',Count=1}, {Item='Pumpkin',Count=1} } },
    ['Pickled_Avocado'] = { Inputs = { {Item='Glass_Jar',Count=1}, {Item='Avocado',Count=1}, {Item='Salt',Count=5} } },
    ['Strawberry_Jam'] = { Inputs = { {Item='Glass_Jar',Count=1}, {Item='Strawberry',Count=5} } },
    ['Food_Shepherds_Roll'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Kumara',Count=1}, {Item='Raw_Meat',Count=1}, {Item='Carrot',Count=1} } },
    ['Food_Savory_Roll'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Avocado',Count=1}, {Item='Raw_Meat',Count=1}, {Item='Mushroom',Count=1} } },
    ['Food_Vegetable_Roll'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Rhubarb',Count=1}, {Item='Bean',Count=1}, {Item='Pumpkin',Count=1} } },
    ['Food_Fruit_Muffin'] = { Inputs = { {Item='Dough_Bread',Count=1}, {Item='Strawberry',Count=1}, {Item='Watermelon',Count=1} } },
    ['Alpha_Sandworm_Statue_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=15}, {Item='Condensed_Enzymes',Count=1}, {Item='Refined_Gold',Count=10} } },
    ['Cougar_Statue_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['Elephant_Statue_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['SnowLeopard_Statue_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['Jaguar_Statue_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['Hyena_Statue_Bronze'] = { Inputs = { {Item='Refined_Copper',Count=5}, {Item='Condensed_Enzymes',Count=1} } },
    ['Piranha_Statue_Wood'] = { Inputs = { {Item='Wood',Count=25}, {Item='Condensed_Enzymes',Count=1} } },
    ['Rabbit_Statue_Wood'] = { Inputs = { {Item='Wood',Count=25}, {Item='Condensed_Enzymes',Count=1} } },
    ['Buffalo_Statue_Wood'] = { Inputs = { {Item='Wood',Count=35}, {Item='Condensed_Enzymes',Count=1} } },
    ['Komodo_Statue_Stone'] = { Inputs = { {Item='Stone',Count=100}, {Item='Condensed_Enzymes',Count=1} } },
    ['Rabbit_Statue_Stone'] = { Inputs = { {Item='Stone',Count=100}, {Item='Condensed_Enzymes',Count=1} } },
    ['Caveworm_Statue_Stone'] = { Inputs = { {Item='Stone',Count=500}, {Item='Condensed_Enzymes',Count=1} } },
    ['Elephant_Statue_Stone'] = { Inputs = { {Item='Stone',Count=250}, {Item='Condensed_Enzymes',Count=1} } },
    ['Deer_Statue_Stone'] = { Inputs = { {Item='Stone',Count=250}, {Item='Condensed_Enzymes',Count=1} } },
    ['Buffalo_Statue_Stone'] = { Inputs = { {Item='Stone',Count=250}, {Item='Condensed_Enzymes',Count=1} } },
    ['Piranha_Statue_Stone'] = { Inputs = { {Item='Stone',Count=100}, {Item='Condensed_Enzymes',Count=1} } },
    ['Carved_Table_Round'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Copper_Nail',Count=15} } },
    ['Carved_Table_6'] = { Inputs = { {Item='Wood_Refined',Count=100}, {Item='Copper_Nail',Count=20} } },
    ['Carved_Table_10'] = { Inputs = { {Item='Wood_Refined',Count=150}, {Item='Copper_Nail',Count=35} } },
    ['Carved_Chair_Dining'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Copper_Nail',Count=10}, {Item='Fiber',Count=50} } },
    ['Carved_Chair_Living'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Copper_Nail',Count=15}, {Item='Fiber',Count=50} } },
    ['Carved_Chair_Living_2Seater'] = { Inputs = { {Item='Wood_Refined',Count=75}, {Item='Copper_Nail',Count=20}, {Item='Fiber',Count=75} } },
    ['Carved_Chair_Living_3Seater'] = { Inputs = { {Item='Wood_Refined',Count=100}, {Item='Copper_Nail',Count=30}, {Item='Fiber',Count=100} } },
    ['Carved_Sitting_Bench'] = { Inputs = { {Item='Wood_Refined',Count=60}, {Item='Copper_Nail',Count=20} } },
    ['Carved_Wall_Shelf'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Copper_Nail',Count=15} } },
    ['Carved_Display_Cabinet'] = { Inputs = { {Item='Wood_Refined',Count=100}, {Item='Copper_Nail',Count=25} } },
    ['Carved_Wardrobe'] = { Inputs = { {Item='Wood_Refined',Count=150}, {Item='Copper_Nail',Count=30} } },
    ['Carved_Narrow_Wardrobe'] = { Inputs = { {Item='Wood_Refined',Count=75}, {Item='Copper_Nail',Count=15} } },
    ['Carved_Candles'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Animal_Fat',Count=15}, {Item='Fiber',Count=5} } },
    ['Carved_Candles_1'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Beeswax',Count=15}, {Item='Fiber',Count=5} } },
    ['Carved_Dresser'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Copper_Nail',Count=15} } },
    ['Carved_Stool'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=5} } },
    ['Carved_Nightstand'] = { Inputs = { {Item='Wood_Refined',Count=60}, {Item='Copper_Nail',Count=25} } },
    ['Carved_Bookshelf'] = { Inputs = { {Item='Wood_Refined',Count=110}, {Item='Copper_Nail',Count=30} } },
    ['Carved_Bed'] = { Inputs = { {Item='Wood_Refined',Count=75}, {Item='Fur',Count=40}, {Item='Leather',Count=15}, {Item='Copper_Nail',Count=20} } },
    ['Carved_Coffee_Table'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Copper_Nail',Count=10} } },
    ['Carved_Desk_Lamp'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=10}, {Item='Electronics',Count=2}, {Item='Glass',Count=5} } },
    ['Rustic_Shelf'] = { Inputs = { {Item='Wood',Count=15}, {Item='Iron_Nail',Count=10} } },
    ['Geode_Lamp_Cut_Copper'] = { Inputs = { {Item='Copper_Ore',Count=10}, {Item='Stone',Count=10} } },
}
return Chunk
