-- Recipes Chunk 3
local Chunk = {
    ['Geode_Lamp_Cut_Gold'] = { Inputs = { {Item='Gold_Ore',Count=10}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Cut_Oxite'] = { Inputs = { {Item='Oxite',Count=10}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Burst_Copper'] = { Inputs = { {Item='Copper_Ore',Count=35}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Burst_Gold'] = { Inputs = { {Item='Gold_Ore',Count=35}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Burst_Oxite'] = { Inputs = { {Item='Oxite',Count=35}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Monolith_Copper'] = { Inputs = { {Item='Copper_Ore',Count=40}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Monolith_Gold'] = { Inputs = { {Item='Gold_Ore',Count=40}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Monolith_Oxite'] = { Inputs = { {Item='Oxite',Count=40}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Rock_Copper'] = { Inputs = { {Item='Copper_Ore',Count=20}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Rock_Gold'] = { Inputs = { {Item='Gold_Ore',Count=20}, {Item='Stone',Count=10} } },
    ['Geode_Lamp_Rock_Oxite'] = { Inputs = { {Item='Oxite',Count=20}, {Item='Stone',Count=10} } },
    ['Food_Fried_Fish_Chunks'] = { Inputs = { {Item='Fish_Chunks',Count=1} } },
    ['Food_Fish_Chunk_Stew'] = { Inputs = { {Item='Corn',Count=1}, {Item='Squash',Count=1}, {Item='Fish_Chunks',Count=1} } },
    ['Dried_Freshwater_Fillet'] = { Inputs = { {Item='Freshwater_Fish_Fillet',Count=1} } },
    ['Dried_Saltwater_Fillet'] = { Inputs = { {Item='Saltwater_Fish_Fillet',Count=1} } },
    ['Food_Freshwater_Fillet_Curry'] = { Inputs = { {Item='Animal_Fat',Count=1}, {Item='Bean',Count=1}, {Item='Freshwater_Fish_Fillet',Count=1} } },
    ['Food_Saltwater_Fillet_Sashimi'] = { Inputs = { {Item='Saltwater_Fish_Fillet',Count=1}, {Item='Carrot',Count=1} } },
    ['Pickled_Freshwater_Fillet'] = { Inputs = { {Item='Freshwater_Fish_Fillet',Count=1}, {Item='Glass_Jar',Count=1}, {Item='Salt',Count=5} } },
    ['Food_Crumbed_Saltwater_Fillet'] = { Inputs = { {Item='Dough_Bread',Count=1}, {Item='Animal_Fat',Count=1}, {Item='Saltwater_Fish_Fillet',Count=1} } },
    ['Food_Fish_Fillet_Pie'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Mushroom',Count=1}, {Item='Freshwater_Fish_Fillet',Count=1}, {Item='Saltwater_Fish_Fillet',Count=1} } },
    ['Ammo_Casing'] = { Inputs = { {Item='Refined_Metal',Count=1} } },
    ['Volatile_Substance'] = { Inputs = { {Item='Gunpowder',Count=2}, {Item='Oxite',Count=2}, {Item='Spoiled_Plants',Count=2} } },
    ['Volatile_Substance_2'] = { Inputs = { {Item='Guano',Count=2}, {Item='Oxite',Count=2} } },
    ['Volatile_Substance_3'] = { Inputs = { {Item='Lithium_Refined',Count=1} } },
    ['Shield_Bone'] = { Inputs = { {Item='Bone',Count=25}, {Item='Leather',Count=15} } },
    ['Shield_Steel'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Leather',Count=15} } },
    ['Shield_Platinum'] = { Inputs = { {Item='Platinum_Ingot',Count=20}, {Item='Advanced_Leather',Count=3}, {Item='Epoxy',Count=5}, {Item='Steel_Screw',Count=10} } },
    ['Shield_Titanium'] = { Inputs = { {Item='Titanium_Plate',Count=4}, {Item='Advanced_Leather',Count=3}, {Item='Epoxy',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Titanium_Ingot',Count=2} } },
    ['Shield_Carbon'] = { Inputs = { {Item='Carbon_Fiber',Count=14}, {Item='Platinum_Shealth',Count=8}, {Item='Steel_Screw',Count=20}, {Item='Epoxy',Count=4} } },
    ['Shield_Composites'] = { Inputs = { {Item='Composites',Count=14}, {Item='Platinum_Weave',Count=4}, {Item='Steel_Screw',Count=20}, {Item='Epoxy',Count=4}, {Item='Titanium_Plate',Count=2} } },
    ['SpawnBlocker_T2'] = { Inputs = { {Item='Cloth_Head',Count=1}, {Item='Cloth_Arms',Count=1}, {Item='Stone',Count=20}, {Item='Wood',Count=25}, {Item='Tree_Sap',Count=20}, {Item='Spoiled_Meat',Count=10} } },
    ['SpawnBlocker_T3'] = { Inputs = { {Item='Aluminium',Count=20}, {Item='Electronics',Count=20}, {Item='Carbon_Fiber',Count=15}, {Item='Steel_Screw',Count=30}, {Item='Glass',Count=10} } },
    ['SpawnBlocker_T4'] = { Inputs = { {Item='Composites',Count=15}, {Item='Electronics',Count=25}, {Item='Titanium_Plate',Count=5}, {Item='Steel_Screw',Count=20} } },
    ['Wind_Turbine'] = { Inputs = { {Item='Electronics',Count=8}, {Item='Steel_Screw',Count=20}, {Item='Aluminium',Count=25}, {Item='Copper_Wire',Count=35}, {Item='Gold_Wire',Count=25}, {Item='Carbon_Fiber',Count=5} } },
    ['Carcass_Pronghorn'] = { Inputs = { {Item='AnimalCarcass_Pronghorn',Count=1} } },
    ['Tree_Sap_Wood'] = { Inputs = { {Item='Wood',Count=1} } },
    ['Food_Grilled_Saltwater_Fillet'] = { Inputs = { {Item='Saltwater_Fish_Fillet',Count=1} } },
    ['Food_Grilled_Feshwater_Fillet'] = { Inputs = { {Item='Freshwater_Fish_Fillet',Count=1} } },
    ['Painting_Wood'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Fiber',Count=25}, {Item='Paints',Count=5} } },
    ['Painting_Dark'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Charcoal',Count=10}, {Item='Fiber',Count=25}, {Item='Paints',Count=5} } },
    ['Painting_Gold'] = { Inputs = { {Item='Refined_Gold',Count=10}, {Item='Fiber',Count=10}, {Item='Paints',Count=5} } },
    ['Painting_Gold_Wood'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Refined_Gold',Count=5}, {Item='Fiber',Count=10}, {Item='Paints',Count=5} } },
    ['Painting_Metal'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Fiber',Count=25}, {Item='Paints',Count=5} } },
    ['Painting_Scroll'] = { Inputs = { {Item='Refined_Metal',Count=5}, {Item='Fiber',Count=25}, {Item='Paints',Count=5} } },
    ['Paints_1'] = { Inputs = { {Item='GreenTea',Count=5}, {Item='Charcoal',Count=5} } },
    ['Paints_2'] = { Inputs = { {Item='WildTea',Count=5}, {Item='Berry',Count=5} } },
    ['Paints_3'] = { Inputs = { {Item='Coffee',Count=5}, {Item='Tree_Sap',Count=5} } },
    ['Paints_4'] = { Inputs = { {Item='Cocoa',Count=5}, {Item='Lily',Count=5} } },
    ['Paints_5'] = { Inputs = { {Item='Crushed_Bone',Count=5}, {Item='Sulfur',Count=5} } },
    ['Paints_6'] = { Inputs = { {Item='Honeycomb',Count=5}, {Item='Yeast',Count=5} } },
    ['Pistol_Armor_Piercing_Round'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=1}, {Item='Platinum_Shealth',Count=1} } },
    ['Rifle_Armor_Piercing_Round'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=1}, {Item='Platinum_Shealth',Count=1} } },
    ['Shotgun_Shell_Armor_Piercing'] = { Inputs = { {Item='Shotgun_Casing',Count=1}, {Item='Gunpowder',Count=1}, {Item='Platinum_Shealth',Count=1} } },
    ['Titanium_Plate'] = { Inputs = { {Item='Titanium_Ingot',Count=3} } },
    ['Platinum_Sheath'] = { Inputs = { {Item='Platinum_Ingot',Count=1} } },
    ['Obsidian_Axe'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Leather',Count=4}, {Item='Shaped_Obsidian',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Obsidian_Pickaxe'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Leather',Count=4}, {Item='Shaped_Obsidian',Count=6} } },
    ['Obsidian_Spear'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Leather',Count=6}, {Item='Shaped_Obsidian',Count=15} } },
    ['Obsidian_Knife'] = { Inputs = { {Item='Wood_Refined',Count=5}, {Item='Leather',Count=4}, {Item='Shaped_Obsidian',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Obsidian_Sickle'] = { Inputs = { {Item='Wood_Refined',Count=5}, {Item='Leather',Count=4}, {Item='Shaped_Obsidian',Count=10} } },
    ['Obsidian_Sledgehammer'] = { Inputs = { {Item='Shaped_Obsidian',Count=15}, {Item='Wood_Refined',Count=20}, {Item='Iron_Nail',Count=10}, {Item='Leather',Count=5} } },
    ['Obsidian_Bolt'] = { Inputs = { {Item='Wood_Refined',Count=5}, {Item='Shaped_Obsidian',Count=1} } },
    ['Obsidian_Arrow'] = { Inputs = { {Item='Leather',Count=5}, {Item='Wood_Refined',Count=5}, {Item='Shaped_Obsidian',Count=1} } },
    ['Pistol_Round_Obsidian'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=5}, {Item='Shaped_Obsidian',Count=1} } },
    ['Rifle_Round_Obsidian'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=5}, {Item='Shaped_Obsidian',Count=1} } },
    ['Obsidian_Throwing_Knife'] = { Inputs = { {Item='Wood_Refined',Count=5}, {Item='Leather',Count=4}, {Item='Shaped_Obsidian',Count=5}, {Item='Iron_Nail',Count=4} } },
    ['Obsidian_Throwing_Spear'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Leather',Count=5}, {Item='Shaped_Obsidian',Count=20} } },
    ['Cold_Steel_Axe'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=10}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Pickaxe'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=10}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Knife'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Throwing_Knife'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Spear'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=20}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Throwing_Spear'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=20}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Sickle'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=5}, {Item='Wood_Refined',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Sledgehammer'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=15}, {Item='Wood_Refined',Count=20}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=5} } },
    ['Cold_Steel_Arrow'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=1}, {Item='Copper_Nail',Count=5}, {Item='Fur',Count=5}, {Item='Wood_Refined',Count=5} } },
    ['Cold_Steel_Bolt'] = { Inputs = { {Item='Cold_Steel_Ingot',Count=1}, {Item='Wood_Refined',Count=5}, {Item='Steel_Screw',Count=5}, {Item='Fur',Count=5} } },
    ['Pistol_Round_Cold_Steel'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=5}, {Item='Cold_Steel_Ingot',Count=1} } },
    ['Rifle_Round_Cold_Steel'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=5}, {Item='Cold_Steel_Ingot',Count=1} } },
    ['Iron_Wood_Axe'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=6}, {Item='Refined_Iron_Wood',Count=6}, {Item='Wood_Refined',Count=10} } },
    ['Iron_Wood_Pickaxe'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=6}, {Item='Refined_Iron_Wood',Count=6}, {Item='Wood_Refined',Count=10} } },
    ['Iron_Wood_Knife'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=2}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=4}, {Item='Refined_Iron_Wood',Count=4}, {Item='Wood_Refined',Count=5} } },
    ['Iron_Wood_Throwing_Knife'] = { Inputs = { {Item='Carbon_Fiber',Count=2}, {Item='Steel_Screw',Count=4}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=3}, {Item='Refined_Iron_Wood',Count=3}, {Item='Wood_Refined',Count=5} } },
    ['Iron_Wood_Spear'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=12}, {Item='Refined_Iron_Wood',Count=12} } },
    ['Iron_Wood_Throwing_Spear'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=10}, {Item='Refined_Iron_Wood',Count=10} } },
    ['Iron_Wood_Sickle'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=2}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=5}, {Item='Refined_Iron_Wood',Count=5}, {Item='Wood_Refined',Count=5} } },
    ['Iron_Wood_Bolt'] = { Inputs = { {Item='Steel_Screw',Count=4}, {Item='Titanium_Ingot',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Refined_Iron_Wood',Count=1} } },
    ['Iron_Wood_Arrow'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Steel_Screw',Count=2}, {Item='Titanium_Ingot',Count=1}, {Item='Refined_Iron_Wood',Count=1} } },
    ['Iron_Wood_Sledgehammer'] = { Inputs = { {Item='Titanium_Ingot',Count=8}, {Item='Carbon_Fiber',Count=6}, {Item='Steel_Screw',Count=10}, {Item='Refined_Iron_Wood',Count=8}, {Item='Wood_Refined',Count=20} } },
    ['Pistol_Round_Iron_Wood'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=5}, {Item='Refined_Iron_Wood',Count=1} } },
    ['Rifle_Round_Iron_Wood'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=5}, {Item='Refined_Iron_Wood',Count=1} } },
    ['Shaped_Obsidian'] = { Inputs = { {Item='Obsidian',Count=2} } },
    ['Cold_Steel_Ingot'] = { Inputs = { {Item='Steel_Ingot',Count=1}, {Item='Super_Cooled_Ice',Count=1} } },
    ['Cold_Steel_Ingot_2'] = { Inputs = { {Item='Steel_Ingot',Count=1}, {Item='Super_Cooled_Ice',Count=1}, {Item='Ruby_Shaped',Count=1} } },
    ['Refined_Iron_Wood'] = { Inputs = { {Item='Raw_Iron_Wood',Count=1} } },
    ['Refined_Iron_Wood_2'] = { Inputs = { {Item='Raw_Iron_Wood',Count=1}, {Item='Lithium_Refined',Count=1} } },
    ['Infected_Bark'] = { Inputs = { {Item='Infected_Bark',Count=1} } },
    ['Acific_Glands'] = { Inputs = { {Item='Acidic_Glands',Count=1} } },
    ['Pyritic_Crust_Iron'] = { Inputs = { {Item='Pyritic_Crust_Iron',Count=1} } },
    ['Pyritic_Crust_Gold'] = { Inputs = { {Item='Pyritic_Crust_Gold',Count=1} } },
    ['Pyritic_Crust_Copper'] = { Inputs = { {Item='Pyritic_Crust_Copper',Count=1} } },
    ['Pyritic_Crust_Silicon'] = { Inputs = { {Item='Pyritic_Crust_Silicon',Count=1} } },
    ['Pyritic_Crust_Coal'] = { Inputs = { {Item='Pyritic_Crust_Coal',Count=1} } },
    ['Pyritic_Crust_Sulfur'] = { Inputs = { {Item='Pyritic_Crust_Sulfur',Count=1} } },
    ['Pyritic_Crust_Bauxite'] = { Inputs = { {Item='Pyritic_Crust_Bauxite',Count=1} } },
    ['Pyritic_Crust_Oxite'] = { Inputs = { {Item='Pyritic_Crust_Oxite',Count=1} } },
    ['Pyritic_Crust_Titanium'] = { Inputs = { {Item='Pyritic_Crust_Titanium',Count=1} } },
    ['Pyritic_Crust_Platinum'] = { Inputs = { {Item='Pyritic_Crust_Platinum',Count=1} } },
    ['Pyritic_Crust_Obsidian'] = { Inputs = { {Item='Pyritic_Crust_Obsidian',Count=1} } },
    ['Pyritic_Crust_Scoria'] = { Inputs = { {Item='Pyritic_Crust_Scoria',Count=1} } },
    ['Pyritic_Crust_Clay'] = { Inputs = { {Item='Pyritic_Crust_Clay',Count=1} } },
    ['Pyritic_Crust_Purple_Exotic'] = { Inputs = { {Item='Pyritic_Crust_Purple_Exotic',Count=1} } },
    ['Pyritic_Crust_Red_Exotic'] = { Inputs = { {Item='Pyritic_Crust_Red_Exotic',Count=1} } },
    ['Heavy_Obsidian_Head_Armor'] = { Inputs = { {Item='Leather',Count=4}, {Item='Obsidian',Count=3}, {Item='Rope',Count=4} } },
    ['Heavy_Obsidian_Chest_Armor'] = { Inputs = { {Item='Leather',Count=4}, {Item='Obsidian',Count=12}, {Item='Rope',Count=4} } },
    ['Heavy_Obsidian_Arm_Armor'] = { Inputs = { {Item='Leather',Count=2}, {Item='Obsidian',Count=2}, {Item='Rope',Count=2} } },
    ['Heavy_Obsidian_Legs_Armor'] = { Inputs = { {Item='Leather',Count=2}, {Item='Obsidian',Count=2}, {Item='Rope',Count=2} } },
    ['Heavy_Obsidian_Feet_Armor'] = { Inputs = { {Item='Leather',Count=2}, {Item='Obsidian',Count=1}, {Item='Rope',Count=4} } },
    ['Obsidian_Head_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=10}, {Item='Composites',Count=5}, {Item='Steel_Screw',Count=5}, {Item='Shaped_Obsidian',Count=5} } },
    ['Obsidian_Chest_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=15}, {Item='Composites',Count=8}, {Item='Steel_Screw',Count=6}, {Item='Shaped_Obsidian',Count=15} } },
    ['Obsidian_Arms_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=5}, {Item='Composites',Count=3}, {Item='Steel_Screw',Count=2}, {Item='Shaped_Obsidian',Count=5} } },
    ['Obsidian_Legs_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=12}, {Item='Composites',Count=2}, {Item='Steel_Screw',Count=3}, {Item='Shaped_Obsidian',Count=12} } },
    ['Obsidian_Feet_Armor'] = { Inputs = { {Item='Platinum_Weave',Count=3}, {Item='Composites',Count=2}, {Item='Steel_Screw',Count=3}, {Item='Shaped_Obsidian',Count=5} } },
    ['Scoria_Frame'] = { Inputs = { {Item='Wood',Count=12}, {Item='Scoria',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=12} } },
    ['Scoria_Beam'] = { Inputs = { {Item='Wood',Count=2}, {Item='Scoria',Count=3}, {Item='Leather',Count=1}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Floor'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Wall'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Halfpiece'] = { Inputs = { {Item='Wood',Count=3}, {Item='Scoria',Count=5}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Scoria_Half_Pitch'] = { Inputs = { {Item='Wood',Count=3}, {Item='Scoria',Count=5}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Scoria_Wall_Angled'] = { Inputs = { {Item='Wood',Count=3}, {Item='Scoria',Count=5}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Scoria_Ramp'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Roof_Corner'] = { Inputs = { {Item='Wood',Count=3}, {Item='Scoria',Count=5}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Scoria_Brick'] = { Inputs = { {Item='Scoria',Count=1} } },
    ['Scoria_Brick_Beam'] = { Inputs = { {Item='Scoria_Brick',Count=25}, {Item='Tree_Sap',Count=5} } },
    ['Scoria_Brick_Floor'] = { Inputs = { {Item='Scoria_Brick',Count=40}, {Item='Tree_Sap',Count=5} } },
    ['Scoria_Brick_Wall'] = { Inputs = { {Item='Scoria_Brick',Count=40}, {Item='Tree_Sap',Count=5} } },
    ['Scoria_Brick_Halfpiece'] = { Inputs = { {Item='Scoria_Brick',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Scoria_Brick_Half_Pitch'] = { Inputs = { {Item='Scoria_Brick',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Scoria_Brick_Wall_Angle'] = { Inputs = { {Item='Scoria_Brick',Count=25}, {Item='Tree_Sap',Count=5} } },
    ['Scoria_Brick_Ramp'] = { Inputs = { {Item='Scoria_Brick',Count=30}, {Item='Tree_Sap',Count=5} } },
    ['Scoria_Bick_Roof_Corner'] = { Inputs = { {Item='Scoria_Brick',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['AlienFossil_Pottery'] = { Inputs = { {Item='Clay',Count=15}, {Item='Organic_Resin',Count=5}, {Item='Scoria',Count=5} } },
    ['AlienFossil_Conch'] = { Inputs = { {Item='Clay',Count=10}, {Item='Organic_Resin',Count=5}, {Item='Scoria',Count=20} } },
    ['Frozen_Ore'] = { Inputs = { {Item='Frozen_Ore',Count=1} } },
    ['Carcass_BatDog'] = { Inputs = { {Item='AnimalCarcass_BatDog',Count=1} } },
    ['Carcass_Deer_Variant'] = { Inputs = { {Item='AnimalCarcass_Deer_Variant',Count=1} } },
    ['Carcass_Chamois_Var'] = { Inputs = { {Item='AnimalCarcass_Chamois_Var',Count=1} } },
    ['Carcass_PredatorBird'] = { Inputs = { {Item='AnimalCarcass_PredatorBird',Count=1} } },
    ['Carcass_Roat_Swamp'] = { Inputs = { {Item='AnimalCarcass_Roat_Swamp',Count=1} } },
    ['Carcass_Roat_Lava'] = { Inputs = { {Item='AnimalCarcass_Roat_Lava',Count=1} } },
    ['Carcass_Wooly_Zebra'] = { Inputs = { {Item='AnimalCarcass_Wooly_Zebra',Count=1} } },
    ['Rug_Bear'] = { Inputs = { {Item='Bear_Head',Count=1}, {Item='Fur',Count=30}, {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=5} } },
    ['Rug_Buffalo'] = { Inputs = { {Item='Buffalo_Head',Count=1}, {Item='Fur',Count=30}, {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=5} } },
    ['Rug_Conifer_Wolf'] = { Inputs = { {Item='ConiferWolf_Head',Count=1}, {Item='Fur',Count=20}, {Item='Leather',Count=10}, {Item='Fiber',Count=20} } },
    ['Rug_Cougar'] = { Inputs = { {Item='Cougar_Head',Count=1}, {Item='Fur',Count=20}, {Item='Leather',Count=10}, {Item='Fiber',Count=20} } },
    ['Rug_Deer'] = { Inputs = { {Item='Deer_Head',Count=1}, {Item='Fur',Count=20}, {Item='Leather',Count=10}, {Item='Fiber',Count=20} } },
    ['Rug_Desert_Wolf'] = { Inputs = { {Item='DesertWolf_Head',Count=1}, {Item='Fur',Count=20}, {Item='Leather',Count=10}, {Item='Fiber',Count=20} } },
    ['Rug_Jaguar'] = { Inputs = { {Item='Jaguar_Head',Count=1}, {Item='Fur',Count=30}, {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=5} } },
    ['Rug_PolarBear'] = { Inputs = { {Item='PolarBear_Head',Count=1}, {Item='Polarbear_Pelt',Count=10}, {Item='Fur',Count=20}, {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=5} } },
    ['Rug_Snow_Wolf'] = { Inputs = { {Item='SnowWolf_Head',Count=1}, {Item='Fur',Count=20}, {Item='Leather',Count=10}, {Item='Fiber',Count=20} } },
    ['Rug_SnowLeopard'] = { Inputs = { {Item='SnowLeopard_Head',Count=1}, {Item='Fur',Count=30}, {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=5} } },
    ['Rug_Weave_Thin'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=10}, {Item='Fiber',Count=60} } },
    ['Rug_Weave_Thick'] = { Inputs = { {Item='Leather',Count=10}, {Item='Fiber',Count=100} } },
    ['Seed_Bread'] = { Inputs = { {Item='Dough_Bread',Count=1}, {Item='Seed',Count=10} } },
    ['Seed_Crackers'] = { Inputs = { {Item='Seed',Count=5} } },
    ['Berry_Bar'] = { Inputs = { {Item='Seed',Count=10}, {Item='Berry',Count=10} } },
    ['Animal_Feed'] = { Inputs = { {Item='Seed',Count=10}, {Item='Wheat',Count=5} } },
    ['Seed_Oil'] = { Inputs = { {Item='Seed',Count=15} } },
    ['Seed_Biofuel'] = { Inputs = { {Item='Seed_Oil',Count=1} } },
    ['Cured_Leather_3'] = { Inputs = { {Item='Leather',Count=3}, {Item='Seed_Oil',Count=1} } },
    ['Cured_Leather_4'] = { Inputs = { {Item='Leather',Count=3}, {Item='Beeswax',Count=2} } },
    ['Watering_Can'] = { Inputs = { {Item='Refined_Metal',Count=5}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=2} } },
    ['Anvil_Bench_T3'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Stone',Count=150}, {Item='Epoxy',Count=8}, {Item='Steel_Ingot',Count=20} } },
    ['Anvil_Bench_T4'] = { Inputs = { {Item='Titanium_Plate',Count=5}, {Item='Electronics',Count=8}, {Item='Concrete_Mix',Count=15}, {Item='Steel_Screw',Count=18}, {Item='Glass',Count=5} } },
    ['Masonry_Bench_T3'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Epoxy',Count=15}, {Item='Iron_Nail',Count=80}, {Item='Stone',Count=150} } },
    ['Bone_Head_Armor'] = { Inputs = { {Item='Bone',Count=20}, {Item='Leather',Count=5} } },
    ['Bone_Chest_Armor'] = { Inputs = { {Item='Bone',Count=60}, {Item='Leather',Count=15} } },
    ['Bone_Arms_Armor'] = { Inputs = { {Item='Bone',Count=15}, {Item='Leather',Count=8} } },
    ['Bone_Legs_Armor'] = { Inputs = { {Item='Bone',Count=40}, {Item='Leather',Count=12} } },
    ['Bone_Feet_Armor'] = { Inputs = { {Item='Bone',Count=15}, {Item='Leather',Count=8} } },
    ['Carcass_Rabbit_Variant'] = { Inputs = { {Item='AnimalCarcass_Rabbit_Variant',Count=1} } },
    ['Carcass_Rabbit_Variant_Snow'] = { Inputs = { {Item='AnimalCarcass_Rabbit_Variant_Snow',Count=1} } },
    ['Gunpowder_Salt'] = { Inputs = { {Item='Salt',Count=1}, {Item='Charcoal',Count=1}, {Item='Spoiled_Plants',Count=1} } },
    ['Volatile_Substance_Inert'] = { Inputs = { {Item='Salt',Count=2} } },
    ['Raw_Wood_Sign'] = { Inputs = { {Item='Wood',Count=10}, {Item='Stick',Count=5}, {Item='Fiber',Count=15} } },
    ['Raw_Wood_Sign_Trunk_A'] = { Inputs = { {Item='Wood',Count=10}, {Item='Stick',Count=5}, {Item='Fiber',Count=15} } },
    ['Raw_Wood_Sign_Trunk_B'] = { Inputs = { {Item='Wood',Count=10}, {Item='Stick',Count=5}, {Item='Fiber',Count=15} } },
    ['Raw_Wood_Lamp'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=10}, {Item='Electronics',Count=2}, {Item='Glass',Count=5} } },
    ['Brownbear_Head_Armor'] = { Inputs = { {Item='Leather',Count=3}, {Item='Fur',Count=10}, {Item='Rope',Count=4}, {Item='Bear_Head',Count=1} } },
    ['Brownbear_Chest_Armor'] = { Inputs = { {Item='Leather',Count=5}, {Item='Fur',Count=20}, {Item='Rope',Count=6} } },
    ['Brownbear_Arm_Armor'] = { Inputs = { {Item='Leather',Count=3}, {Item='Fur',Count=15}, {Item='Rope',Count=2} } },
    ['Brownbear_Leg_Armor'] = { Inputs = { {Item='Leather',Count=4}, {Item='Fur',Count=16}, {Item='Rope',Count=6} } },
    ['Brownbear_Feet_Armor'] = { Inputs = { {Item='Leather',Count=3}, {Item='Fur',Count=15}, {Item='Rope',Count=2} } },
    ['Shroud_Light'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Glass',Count=10}, {Item='Copper_Wire',Count=10} } },
    ['Blueback_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Blueback_Head',Count=1} } },
    ['Stonejaw_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Stonejaw_Head',Count=1} } },
    ['Dac_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Drac_Head',Count=1} } },
    ['Caveworm_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Caveworm_Head',Count=1} } },
    ['Teenage_Caveworm_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Teenage_Caveworm_Head',Count=1} } },
    ['Chamios_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Chamios_Head',Count=1} } },
    ['Chala_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Chala_Head',Count=1} } },
    ['Crocodile_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Crocodile_Head',Count=1} } },
    ['Equix_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Equix_Head',Count=1} } },
    ['Desert_Striker_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Desert_Striker_Head',Count=1} } },
    ['Elephant_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Elephant_Head',Count=1} } },
    ['Kea_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Kea_Head',Count=1} } },
    ['Ashen_Drake_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Ashen_Drake_Head',Count=1} } },
    ['Redback_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Redback_Head',Count=1} } },
    ['Broodling_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Lava_Broodling_Head',Count=1} } },
    ['Lava_Viscid_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Lava_Viscid_Head',Count=1} } },
    ['Moa_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Moa_Head',Count=1} } },
    ['Needler_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Needler_Head',Count=1} } },
    ['Rabbit_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Rabbit_Head',Count=1} } },
    ['Arctic_Rabbit_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Snow_Rabbit_Head',Count=1} } },
    ['Pygmy_Lopp_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Rabbit_Varient_Head',Count=1} } },
    ['Snow_Stalker_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Snow_Stalker_Head',Count=1} } },
    ['Roat_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Roat_Head',Count=1} } },
    ['Viscid_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Swamp_Viscid_Head',Count=1} } },
    ['Pronghorn_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Pronghorn_Head',Count=1} } },
    ['Desert_Mammoth_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Desert_Mammoth_Head',Count=1} } },
    ['Desert_Deer_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Desert_Deer_Head',Count=1} } },
    ['T3_Smoker'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Refined_Copper',Count=10}, {Item='Concrete_Mix',Count=15}, {Item='Steel_Screw',Count=20}, {Item='Charcoal',Count=50} } },
    ['Shotgun_Shell_Cold_Steel'] = { Inputs = { {Item='Ammo_Shell_Buckshot',Count=5}, {Item='Cold_Steel_Ingot',Count=1} } },
    ['Shotgun_Shell_Obsidian'] = { Inputs = { {Item='Ammo_Shell_Buckshot',Count=5}, {Item='Shaped_Obsidian',Count=1} } },
    ['Shotgun_Shell_Ironwood'] = { Inputs = { {Item='Ammo_Shell_Buckshot',Count=5}, {Item='Refined_Iron_Wood',Count=1} } },
    ['Sandworm_Biomass_1'] = { Inputs = { {Item='Sandworm_Scale',Count=25} } },
    ['Biomass_To_SandwormScale'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Sandworm_Biomass_2'] = { Inputs = { {Item='Sandworm_Tendon',Count=3} } },
    ['Biomass_To_SandwormTendon'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Alpha_Wolf_Biomass_1'] = { Inputs = { {Item='Black_Wolf_Tooth',Count=5} } },
    ['Biomass_To_BlackWolfTooth'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Alpha_Wolf_Biomass_2'] = { Inputs = { {Item='Black_Fur',Count=3} } },
    ['Biomass_To_BlackFur'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Giant_Scorpion_Biomass_1'] = { Inputs = { {Item='Scorpion_Carapace',Count=25} } },
    ['Biomass_To_Scorpion_Carapace'] = { Inputs = { {Item='Biomass',Count=25} } },
    ['Giant_Scorpion_Biomass_2'] = { Inputs = { {Item='Venom_Sac',Count=3} } },
    ['Biomass_To_Scorpion_Sac'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Frozen_Mammoth_Biomass_1'] = { Inputs = { {Item='Frozen_Wool',Count=5} } },
    ['Biomass_To_Frozen_Wool'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Frozen_Mammoth_Biomass_2'] = { Inputs = { {Item='Ice_Armor_Fragment',Count=3} } },
    ['Biomass_To_Ice_Fragment'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Metal_Table_Round'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Steel_Screw',Count=10} } },
    ['Metal_Table6'] = { Inputs = { {Item='Refined_Metal',Count=30}, {Item='Steel_Screw',Count=10} } },
    ['Metal_Table10'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Steel_Screw',Count=10} } },
    ['Metal_Chair_Living'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=8} } },
    ['Metal_Chair_Living_2Seater'] = { Inputs = { {Item='Refined_Metal',Count=25}, {Item='Steel_Screw',Count=10} } },
    ['Metal_Chair_Living_Sitting'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=8} } },
    ['Metal_Chair_Dining'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=8} } },
    ['Metal_Wall_Shelf'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Steel_Screw',Count=5} } },
    ['Metal_Display_Cabinet'] = { Inputs = { {Item='Refined_Metal',Count=25}, {Item='Steel_Screw',Count=10} } },
    ['Metal_Wardrobe'] = { Inputs = { {Item='Refined_Metal',Count=30}, {Item='Steel_Screw',Count=15} } },
    ['Metal_Candles'] = { Inputs = { {Item='Refined_Metal',Count=5}, {Item='Steel_Screw',Count=3}, {Item='Animal_Fat',Count=5} } },
    ['Metal_Candles_1'] = { Inputs = { {Item='Refined_Metal',Count=5}, {Item='Steel_Screw',Count=3}, {Item='Beeswax',Count=5} } },
    ['Metal_Dresser'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=10}, {Item='Glass',Count=5} } },
    ['Metal_Stool'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Steel_Screw',Count=5} } },
    ['Metal_Nightstand'] = { Inputs = { {Item='Refined_Metal',Count=25}, {Item='Steel_Screw',Count=10}, {Item='Glass',Count=15} } },
    ['Metal_Bed'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Steel_Screw',Count=10}, {Item='Fur',Count=20} } },
    ['Metal_Bookshelf'] = { Inputs = { {Item='Refined_Metal',Count=30}, {Item='Steel_Screw',Count=10} } },
    ['Metal_Lamp'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=5}, {Item='Glass',Count=10} } },
    ['Metal_Coffeetable'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Steel_Screw',Count=5}, {Item='Glass',Count=20} } },
    ['Seed_Pouch'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Leather',Count=10} } },
    ['Water_Purifier_T1_Water'] = { Inputs = { {Item='Stick',Count=30}, {Item='Fiber',Count=25}, {Item='Stone',Count=4}, {Item='Charcoal',Count=10} } },
    ['Water_Purifier_T1_Ground'] = { Inputs = { {Item='Stick',Count=15}, {Item='Fiber',Count=20}, {Item='Stone',Count=15}, {Item='Charcoal',Count=10} } },
    ['Water_Purifier_T2'] = { Inputs = { {Item='Wood_Refined',Count=40}, {Item='Refined_Metal',Count=10}, {Item='Stone',Count=30}, {Item='Epoxy',Count=5} } },
    ['Water_Purifier_T4'] = { Inputs = { {Item='Titanium_Plate',Count=2}, {Item='Electronics',Count=10}, {Item='Aluminium',Count=14} } },
    ['Arctic_Scorpion_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Arctic_Scorpion_Head',Count=1} } },
    ['Zebrah_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Zebra_Head',Count=1} } },
    ['Wooly_Zebrah_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Wooly_Zebra_Head',Count=1} } },
    ['Boar_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='WildBoar_Head',Count=1} } },
    ['Stryder_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Stryder_Head',Count=1} } },
    ['Ubis_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Ubis_Head',Count=1} } },
    ['Scorpion_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Scorpion_Head',Count=1} } },
    ['Dreadwing_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dreadwing_Head',Count=1} } },
    ['Terrenus_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Terrenus_Head',Count=1} } },
    ['Tusker_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Tusker_Head',Count=1} } },
    ['Komodo_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Komodo_Head',Count=1} } },
    ['Shield_IceMammoth'] = { Inputs = { {Item='Ice_Armor_Fragment',Count=20}, {Item='Leather',Count=3}, {Item='Epoxy',Count=5}, {Item='Frozen_Wool',Count=4} } },
    ['IceMammoth_Spear'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Frozen_Wool',Count=1}, {Item='Ice_Armor_Fragment',Count=15} } },
    ['IceMammoth_Throwing_Spear'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Frozen_Wool',Count=1}, {Item='Ice_Armor_Fragment',Count=15} } },
    ['Scorpion_FishingRod'] = { Inputs = { {Item='Scorpion_Tail',Count=2}, {Item='Venom_Sac',Count=1}, {Item='Rope',Count=5} } },
    ['Landshark_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Land_Shark_Head',Count=1} } },
    ['Scorpion_Boss_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Scorpion_Boss_Head',Count=1} } },
    ['T3_Cleaning_Device'] = { Inputs = { {Item='Steel_Ingot',Count=25}, {Item='Glass',Count=10}, {Item='Epoxy',Count=12}, {Item='Electronics',Count=15}, {Item='Copper_Wire',Count=40} } },
    ['Black_Wolf_Shield'] = { Inputs = { {Item='Black_Wolf_Tooth',Count=5}, {Item='Black_Fur',Count=3}, {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=2} } },
    ['Scorpion_Crossbow'] = { Inputs = { {Item='Scorpion_Head',Count=1}, {Item='Iron_Nail',Count=15}, {Item='Tree_Sap',Count=40}, {Item='Rope',Count=5}, {Item='Venom_Sac',Count=1} } },
    ['Brutalist_Dining_Table_Round'] = { Inputs = { {Item='Concrete_Mix',Count=10}, {Item='Copper_Nail',Count=10} } },
    ['Brutalist_Dining_Table_6'] = { Inputs = { {Item='Concrete_Mix',Count=10}, {Item='Copper_Nail',Count=10}, {Item='Glass',Count=4} } },
    ['Brutalist_Dining_Table_10'] = { Inputs = { {Item='Concrete_Mix',Count=20}, {Item='Copper_Nail',Count=10}, {Item='Glass',Count=4} } },
    ['Brutalist_Dining_Chair'] = { Inputs = { {Item='Concrete_Mix',Count=4}, {Item='Leather',Count=5} } },
    ['Brutalist_Living_Chair'] = { Inputs = { {Item='Concrete_Mix',Count=4}, {Item='Leather',Count=5} } },
    ['Brutalist_Living_Couch_2'] = { Inputs = { {Item='Concrete_Mix',Count=8}, {Item='Leather',Count=10} } },
    ['Brutalist_Living_Couch_3'] = { Inputs = { {Item='Concrete_Mix',Count=12}, {Item='Leather',Count=15} } },
    ['Brutalist_Bench_Sitting'] = { Inputs = { {Item='Concrete_Mix',Count=10} } },
    ['Brutalist_Shelf_Wall'] = { Inputs = { {Item='Concrete_Mix',Count=3} } },
    ['Brutalist_Cabinet'] = { Inputs = { {Item='Concrete_Mix',Count=15}, {Item='Refined_Metal',Count=8} } },
    ['Brutalist_Wardrobe'] = { Inputs = { {Item='Concrete_Mix',Count=14}, {Item='Refined_Metal',Count=6} } },
    ['Brutalist_Candle'] = { Inputs = { {Item='Concrete_Mix',Count=1}, {Item='Animal_Fat',Count=2} } },
    ['Brutalist_Candle_1'] = { Inputs = { {Item='Concrete_Mix',Count=1}, {Item='Beeswax',Count=2} } },
    ['Brutalist_Dresser'] = { Inputs = { {Item='Concrete_Mix',Count=14}, {Item='Fiber',Count=20} } },
    ['Brutalist_Stool'] = { Inputs = { {Item='Concrete_Mix',Count=4} } },
    ['Brutalist_Nightstand'] = { Inputs = { {Item='Concrete_Mix',Count=6} } },
    ['Brutalist_Bed'] = { Inputs = { {Item='Concrete_Mix',Count=10}, {Item='Platinum_Weave',Count=10} } },
    ['Brutalist_Bookshelf'] = { Inputs = { {Item='Concrete_Mix',Count=14}, {Item='Refined_Metal',Count=6} } },
    ['Brutalist_Lamp'] = { Inputs = { {Item='Concrete_Mix',Count=2}, {Item='Glass',Count=3}, {Item='Gold_Wire',Count=4}, {Item='Fiber',Count=8} } },
    ['Brutalist_Lamp_Square'] = { Inputs = { {Item='Concrete_Mix',Count=2}, {Item='Glass',Count=3}, {Item='Gold_Wire',Count=4}, {Item='Fiber',Count=8} } },
    ['Brutalist_CoffeeTable'] = { Inputs = { {Item='Concrete_Mix',Count=6}, {Item='Refined_Metal',Count=4}, {Item='Glass',Count=4} } },
    ['Gold_Bed'] = { Inputs = { {Item='Refined_Gold',Count=8}, {Item='Stone',Count=20}, {Item='Platinum_Weave',Count=6} } },
    ['Gold_Bookshelf'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Stone',Count=40} } },
    ['Gold_Candle'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Animal_Fat',Count=4} } },
    ['Gold_Candle_1'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Beeswax',Count=4} } },
    ['Gold_Standing_Lamp'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Stone',Count=10}, {Item='Glass',Count=4}, {Item='Gold_Wire',Count=4} } },
    ['Gold_Dining_Chair'] = { Inputs = { {Item='Refined_Gold',Count=3}, {Item='Platinum_Weave',Count=2} } },
    ['Gold_Table_6Seater'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Stone',Count=40} } },
    ['Gold_Table_10Seater'] = { Inputs = { {Item='Refined_Gold',Count=8}, {Item='Stone',Count=60} } },
    ['Gold_Table_Round'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Stone',Count=40} } },
    ['Gold_Dresser'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Stone',Count=40} } },
    ['Gold_Living_Chair'] = { Inputs = { {Item='Refined_Gold',Count=3}, {Item='Platinum_Weave',Count=2} } },
    ['Gold_Living_Chair2'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Platinum_Weave',Count=4} } },
    ['Gold_Living_Chair3'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Platinum_Weave',Count=5} } },
    ['Gold_Sitting_Bench'] = { Inputs = { {Item='Refined_Gold',Count=3}, {Item='Platinum_Weave',Count=4} } },
    ['Gold_Shelf_Wall'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Stone',Count=20}, {Item='Steel_Screw',Count=6} } },
    ['Gold_Wardrobe'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Stone',Count=40} } },
    ['Gold_Vault'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Steel_Ingot',Count=20}, {Item='Gold_Wire',Count=4}, {Item='Stone',Count=20} } },
    ['Gold_Safe'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Steel_Ingot',Count=14}, {Item='Gold_Wire',Count=4}, {Item='Stone',Count=20} } },
    ['Gold_Fireplace'] = { Inputs = { {Item='Refined_Gold',Count=10}, {Item='Stone',Count=160}, {Item='Wood',Count=20} } },
    ['Gold_Fireplace_Ext'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Stone',Count=50} } },
    ['Gold_Fireplace_Cap'] = { Inputs = { {Item='Refined_Gold',Count=2}, {Item='Stone',Count=60} } },
    ['Gold_Chandelier'] = { Inputs = { {Item='Refined_Gold',Count=8}, {Item='Glass',Count=20}, {Item='Gold_Wire',Count=20}, {Item='Stone',Count=16} } },
    ['Gold_Wall_Light'] = { Inputs = { {Item='Refined_Gold',Count=2}, {Item='Glass',Count=2}, {Item='Gold_Wire',Count=4}, {Item='Stone',Count=6} } },
    ['Gold_Wall_Sign'] = { Inputs = { {Item='Refined_Gold',Count=2}, {Item='Stone',Count=16} } },
    ['Gold_Partition'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Stone',Count=24} } },
    ['Gold_Rug'] = { Inputs = { {Item='Refined_Gold',Count=2}, {Item='Gold_Wire',Count=8}, {Item='Platinum_Weave',Count=12} } },
    ['Gold_Vase'] = { Inputs = { {Item='Refined_Gold',Count=2}, {Item='Stone',Count=14} } },
    ['Gold_Nightstand'] = { Inputs = { {Item='Refined_Gold',Count=4}, {Item='Stone',Count=20} } },
    ['Fur_Curtain_Door'] = { Inputs = { {Item='Fur',Count=25}, {Item='Wood',Count=5}, {Item='Fiber',Count=15} } },
    ['Battery_T3_Shelf'] = { Inputs = { {Item='Electronics',Count=4}, {Item='Copper_Wire',Count=16}, {Item='Wood_Refined',Count=10}, {Item='Platinum_Shealth',Count=6}, {Item='Titanium_Plate',Count=2} } },
    ['Battery_T4_Shelf'] = { Inputs = { {Item='Electronics',Count=8}, {Item='Titanium_Plate',Count=8}, {Item='Copper_Wire',Count=18}, {Item='Gold_Wire',Count=18}, {Item='Composites',Count=4} } },
    ['Black_Wolf_Head'] = { Inputs = { {Item='Leather',Count=3}, {Item='Black_Fur',Count=10}, {Item='Rope',Count=4}, {Item='Alphawolf_Head',Count=1}, {Item='Black_Wolf_Tooth',Count=4} } },
    ['Black_Wolf_Chest'] = { Inputs = { {Item='Leather',Count=5}, {Item='Black_Fur',Count=20}, {Item='Rope',Count=6}, {Item='Black_Wolf_Tooth',Count=4} } },
    ['Black_Wolf_Feet'] = { Inputs = { {Item='Leather',Count=3}, {Item='Black_Fur',Count=15}, {Item='Rope',Count=2}, {Item='Black_Wolf_Tooth',Count=6} } },
    ['Black_Wolf_Arms'] = { Inputs = { {Item='Leather',Count=3}, {Item='Black_Fur',Count=15}, {Item='Rope',Count=2}, {Item='Black_Wolf_Tooth',Count=4} } },
    ['Black_Wolf_Legs'] = { Inputs = { {Item='Leather',Count=4}, {Item='Black_Fur',Count=16}, {Item='Rope',Count=6}, {Item='Black_Wolf_Tooth',Count=4} } },
    ['Smoked_Giant_Steak'] = { Inputs = { {Item='Giant_Steak',Count=1}, {Item='Watermelon',Count=1} } },
    ['Smoked_Fatty_Tbone'] = { Inputs = { {Item='Fatty_Tbone',Count=1}, {Item='Coffee',Count=5} } },
    ['Smoked_Gamey_Meat'] = { Inputs = { {Item='Gamey_Meat',Count=1}, {Item='WildTea',Count=5} } },
    ['Smoked_Stringy_Meat'] = { Inputs = { {Item='Stringy_Meat',Count=1}, {Item='Animal_Fat',Count=1} } },
    ['Smoked_Soft_Meat'] = { Inputs = { {Item='Soft_Meat',Count=1}, {Item='Cocoa',Count=5} } },
    ['Smoked_White_Meat'] = { Inputs = { {Item='White_Meat',Count=1}, {Item='Bean',Count=1} } },
    ['Smoked_Freshwater_Fillet'] = { Inputs = { {Item='Freshwater_Fish_Fillet',Count=1}, {Item='GreenTea',Count=5} } },
    ['Smoked_Saltwater_Fillet'] = { Inputs = { {Item='Saltwater_Fish_Fillet',Count=1}, {Item='Berry',Count=5} } },
    ['Dried_Meat_Generic'] = { Inputs = { {Item='Raw_Meat',Count=1} } },
    ['Smoked_Meat_Generic'] = { Inputs = { {Item='Raw_Meat',Count=1}, {Item='Salt',Count=5} } },
    ['Sugar'] = { Inputs = { {Item='Sugar_Cane',Count=5} } },
    ['Crushed_Limestone'] = { Inputs = { {Item='Limestone',Count=1} } },
    ['Limestone_Glass'] = { Inputs = { {Item='Crushed_Limestone',Count=4} } },
    ['Limestone_Concrete_Mix'] = { Inputs = { {Item='Tree_Sap',Count=1}, {Item='Crushed_Limestone',Count=10} } },
    ['Limestone_Fertilizer'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Crushed_Limestone',Count=5} } },
    ['Steel_Bloom_Limestone'] = { Inputs = { {Item='Crushed_Limestone',Count=5}, {Item='Sulfur',Count=1}, {Item='Metal_Ore',Count=2} } },
    ['Limestone_Frame'] = { Inputs = { {Item='Steel_Rebar',Count=20}, {Item='Limestone',Count=16}, {Item='Steel_Screw',Count=10} } },
    ['Limestone_Beam'] = { Inputs = { {Item='Steel_Rebar',Count=8}, {Item='Limestone',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Limestone_Floor'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Wall'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Halfpiece'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Limestone',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Limestone_Half_Pitch'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Limestone',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Limestone_Wall_Angled'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Limestone',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Limestone_Ramp'] = { Inputs = { {Item='Steel_Rebar',Count=12}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Roof_Corner'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Limestone',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Smoked_Bacon'] = { Inputs = { {Item='Raw_Bacon',Count=1}, {Item='Honey',Count=5} } },
    ['Glass_Jar_Honey'] = { Inputs = { {Item='Glass_Jar',Count=1}, {Item='Honey',Count=5} } },
    ['Honey_Pastry'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Honey',Count=5} } },
    ['Honey'] = { Inputs = { {Item='Honeycomb',Count=2} } },
    ['Beeswax'] = { Inputs = { {Item='Honeycomb',Count=2} } },
    ['Beehive'] = { Inputs = { {Item='Honeycomb',Count=10}, {Item='Wood_Refined',Count=30}, {Item='Copper_Nail',Count=25} } },
    ['Beehive_Expansion1'] = { Inputs = { {Item='Honeycomb',Count=15}, {Item='Wood_Refined',Count=20}, {Item='Aluminium',Count=25}, {Item='Steel_Screw',Count=10} } },
    ['Beehive_Expansion2'] = { Inputs = { {Item='Honeycomb',Count=20}, {Item='Titanium_Plate',Count=2}, {Item='Steel_Screw',Count=20} } },
    ['Beehive_Breeder'] = { Inputs = { {Item='Platinum_Shealth',Count=16}, {Item='Beeswax',Count=20}, {Item='Steel_Screw',Count=10} } },
    ['Beehive_Extractor'] = { Inputs = { {Item='Copper_Wire',Count=30}, {Item='Titanium_Plate',Count=2}, {Item='Glass',Count=15}, {Item='Electronics',Count=8} } },
    ['Turret_Pistol'] = { Inputs = { {Item='Titanium_Plate',Count=8}, {Item='Electronics',Count=12}, {Item='Composites',Count=12}, {Item='Aluminium',Count=12}, {Item='Pistol_Handgun',Count=1}, {Item='Steel_Screw',Count=20}, {Item='Copper_Wire',Count=12} } },
    ['Sandworm_Trophy'] = { Inputs = { {Item='Sandworm_Head',Count=1}, {Item='Wood_Refined',Count=60}, {Item='Refined_Metal',Count=16}, {Item='Copper_Nail',Count=30}, {Item='Sandworm_Scale',Count=20}, {Item='Sandworm_Tendon',Count=10} } },
    ['Sandworm_Trophy_Brazier'] = { Inputs = { {Item='Sandworm_Head',Count=1}, {Item='Wood',Count=4}, {Item='Refined_Metal',Count=16}, {Item='Steel_Screw',Count=8} } },
    ['Sandworm_Trophy_Brazier_Large'] = { Inputs = { {Item='Sandworm_Head',Count=1}, {Item='Wood',Count=4}, {Item='Refined_Metal',Count=16}, {Item='Steel_Screw',Count=8}, {Item='Sandworm_Scale',Count=20}, {Item='Sandworm_Tendon',Count=10} } },
    ['Reinforced_Wood_Floor_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15}, {Item='Beeswax',Count=10} } },
    ['Reinforced_Wood_Wall_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15}, {Item='Beeswax',Count=10} } },
    ['Reinforced_Wood_Wall_Angled_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Beeswax',Count=5} } },
    ['Reinforced_Wood_Ramp_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15}, {Item='Beeswax',Count=10} } },
    ['Reinforced_Wood_Halfpiece_Carpentry_Bench'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Beeswax',Count=5} } },
    ['Reinforced_Wood_Half_Pitch'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Beeswax',Count=5} } },
    ['ReinforcedWood_Roof_Corner'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Beeswax',Count=5} } },
    ['Honey_Mead'] = { Inputs = { {Item='Berry',Count=5}, {Item='Honey',Count=10}, {Item='Yeast',Count=1}, {Item='Glass_Bottle',Count=1} } },
    ['Honey_Bar'] = { Inputs = { {Item='Seed',Count=10}, {Item='Honeycomb',Count=2} } },
    ['Honey_Tea'] = { Inputs = { {Item='Honey',Count=5} } },
    ['Stationeers_Trophy_1'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Refined_Gold',Count=10}, {Item='Condensed_Enzymes',Count=1}, {Item='Oxite',Count=20} } },
    ['Saddle_Bearhide'] = { Inputs = { {Item='Leather',Count=14}, {Item='Fur',Count=6}, {Item='Rope',Count=2}, {Item='Bear_Head',Count=1} } },
    ['Saddle_DeluxeLeather'] = { Inputs = { {Item='Advanced_Leather',Count=14}, {Item='Fur',Count=6}, {Item='Rope',Count=2} } },
    ['Saddle_CrocSkin'] = { Inputs = { {Item='Leather',Count=14}, {Item='Fur',Count=6}, {Item='Rope',Count=2}, {Item='Crocodile_Head',Count=1} } },
    ['Saddle_Sandworm'] = { Inputs = { {Item='Sandworm_Scale',Count=10}, {Item='Fur',Count=6}, {Item='Rope',Count=2} } },
    ['Saddle_Desert'] = { Inputs = { {Item='Leather',Count=20}, {Item='Fiber',Count=14}, {Item='Rope',Count=2} } },
    ['Saddle_Armored'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Fur',Count=6}, {Item='Rope',Count=2} } },
    ['Saddle_Explorer'] = { Inputs = { {Item='Leather',Count=10}, {Item='Fur',Count=6}, {Item='Rope',Count=2} } },
    ['Saddle_Racing'] = { Inputs = { {Item='Advanced_Leather',Count=15}, {Item='Rope',Count=2} } },
}
return Chunk
