-- Recipes Chunk 6
local Chunk = {
    ['Carcass_Dog_A'] = { Inputs = { {Item='AnimalCarcass_Tame_Dog_A',Count=1} } },
    ['Carcass_Dog_B'] = { Inputs = { {Item='AnimalCarcass_Tame_Dog_B',Count=1} } },
    ['Carcass_Dog_C'] = { Inputs = { {Item='AnimalCarcass_Tame_Dog_C',Count=1} } },
    ['Carcass_Dog_C2'] = { Inputs = { {Item='AnimalCarcass_Tame_Dog_C2',Count=1} } },
    ['Carcass_Dog_D'] = { Inputs = { {Item='AnimalCarcass_Tame_Dog_D',Count=1} } },
    ['Carcass_Dog_E'] = { Inputs = { {Item='AnimalCarcass_Tame_Dog_E',Count=1} } },
    ['Bandage_Basic_Silk'] = { Inputs = { {Item='Spider_Silk',Count=5} } },
    ['Bandage_Heat_Silk'] = { Inputs = { {Item='Spider_Silk',Count=5}, {Item='Oxite',Count=4}, {Item='Charcoal',Count=10} } },
    ['Bandage_Cooling_Silk'] = { Inputs = { {Item='Spider_Silk',Count=5}, {Item='Oxite',Count=4}, {Item='Charcoal',Count=10} } },
    ['Rope_Silk'] = { Inputs = { {Item='Spider_Silk',Count=3} } },
    ['Platinum_Wave_Silk'] = { Inputs = { {Item='Spider_Silk',Count=5}, {Item='Platinum_Shealth',Count=1} } },
    ['Spider_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Spider_Head',Count=1} } },
    ['Geothermal_Bat_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Geothermal_Bat_Head',Count=1} } },
    ['Geothermal_Spider_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Geothermal_Spider_Head',Count=1} } },
    ['Ghost_Crocodile_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Ghost_Crocodile_Head',Count=1} } },
    ['Mange_Wolf_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Mange_Wolf_Head',Count=1} } },
    ['Mange_Wolf_Alpha_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Mange_Wolf_Alpha_Head',Count=1} } },
    ['Sandscuttle_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Sandscuttle_Head',Count=1} } },
    ['Tundra_Monkey_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Tundra_Monkey_Head',Count=1} } },
    ['Rabbit_Varient_Snow_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Rabbit_Variant_Snow_Head',Count=1} } },
    ['Flying_Tank_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Flying_Tank_Head',Count=1} } },
    ['Flightless_Tank_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Flightless_Tank_Head',Count=1} } },
    ['Dragonfly_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='DragonFly_Head',Count=1} } },
    ['Giant_Roach_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Giant_Roach_Head',Count=1} } },
    ['Stomper_Matriach_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Stomper_Matriarch_Head',Count=1} } },
    ['Stomper_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Stomper_Head',Count=1} } },
    ['Hopping_Creature_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Hopping_Creature_Head',Count=1} } },
    ['Hopping_Creature_Swamp_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Hopping_Creature_Swamp_Head',Count=1} } },
    ['Tundra_Deer_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Tundra_Deer_Head',Count=1} } },
    ['Bounder_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Bounder_Head',Count=1} } },
    ['Reaver_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Reaver_Head',Count=1} } },
    ['Storca_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Storca_Head',Count=1} } },
    ['Chew_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Chew_Head',Count=1} } },
    ['Slinker_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Slinker_Head',Count=1} } },
    ['Ram_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Ram_Head',Count=1} } },
    ['Rooster_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Rooster_Head',Count=1} } },
    ['Polarbear_Head_Armor_Yeti'] = { Inputs = { {Item='Advanced_Leather',Count=3}, {Item='Fur',Count=10}, {Item='Rope',Count=4}, {Item='Yeti_Head',Count=1} } },
    ['Homestead_Candle'] = { Inputs = { {Item='Refined_Gold',Count=6}, {Item='Beeswax',Count=4} } },
    ['Homestead_Refrigerator'] = { Inputs = { {Item='Aluminium',Count=40}, {Item='Electronics',Count=20}, {Item='Carbon_Fiber',Count=8}, {Item='Steel_Screw',Count=12} } },
    ['Homestead_Copper_Pot'] = { Inputs = { {Item='Refined_Copper',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Homestead_Cushion_A'] = { Inputs = { {Item='Wool',Count=5}, {Item='Fiber',Count=25} } },
    ['Homestead_Cushion_B'] = { Inputs = { {Item='Wool',Count=5}, {Item='Fiber',Count=25} } },
    ['Homestead_Lantern'] = { Inputs = { {Item='Refined_Metal',Count=8}, {Item='Rope',Count=4}, {Item='Epoxy',Count=12}, {Item='Animal_Fat',Count=5} } },
    ['Homestead_Fireplace_Tools'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Epoxy',Count=3}, {Item='Wood_Refined',Count=5} } },
    ['Homestead_Fireplace_Screen'] = { Inputs = { {Item='Steel_Ingot',Count=5}, {Item='Steel_Screw',Count=3} } },
    ['Homestead_Fireplace_Bellows'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Epoxy',Count=4}, {Item='Refined_Metal',Count=1} } },
    ['Homestead_Knitting_Decor'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Wool',Count=5} } },
    ['Homestead_Birdbath_Iron'] = { Inputs = { {Item='Refined_Metal',Count=10} } },
    ['Homestead_Birdbath_Gold'] = { Inputs = { {Item='Refined_Gold',Count=10} } },
    ['Homestead_Spinning_Wheel'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Epoxy',Count=4}, {Item='Iron_Nail',Count=15} } },
    ['Homestead_Kitchen_Bench'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=8}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=20} } },
    ['Homestead_Kitchen_Stove'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=4}, {Item='Steel_Ingot',Count=24}, {Item='Steel_Screw',Count=8} } },
    ['Homestead_Kitchen_Sink'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=10}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=12} } },
    ['Homestead_Kitchen_Storage'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=2}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=12} } },
    ['Homestead_Shutter'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Refined_Metal',Count=2}, {Item='Iron_Nail',Count=8}, {Item='Rope',Count=4} } },
    ['Homestead_Curtain_Window'] = { Inputs = { {Item='Wool',Count=5}, {Item='Refined_Metal',Count=6}, {Item='Fiber',Count=35}, {Item='Gold_Wire',Count=20} } },
    ['Homestead_Door'] = { Inputs = { {Item='Wood_Refined',Count=8}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=8}, {Item='Rope',Count=4} } },
    ['Homestead_Cuckcoo_Clock'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Epoxy',Count=5}, {Item='Refined_Metal',Count=1}, {Item='Refined_Gold',Count=2} } },
    ['Homestead_Weather_Vane'] = { Inputs = { {Item='Refined_Metal',Count=5}, {Item='Refined_Gold',Count=3} } },
    ['Nesting_Box'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Fiber',Count=40} } },
    ['Homestead_Iron_Stove'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Refined_Copper',Count=6}, {Item='Epoxy',Count=10} } },
    ['Homestead_Pitchfork'] = { Inputs = { {Item='Wood',Count=5}, {Item='Leather',Count=6}, {Item='Refined_Metal',Count=24} } },
    ['Homestead_Barn_Door'] = { Inputs = { {Item='Wood_Refined',Count=25}, {Item='Copper_Nail',Count=15} } },
    ['Homestead_Hay_Bale'] = { Inputs = { {Item='Fiber',Count=100} } },
    ['Homestead_Retaining_Wall'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=4} } },
    ['Homestead_Flower_Pot_A'] = { Inputs = { {Item='Stone',Count=20}, {Item='Glass',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Homestead_Flower_Pot_B'] = { Inputs = { {Item='Stone',Count=20}, {Item='Glass',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Homestead_Flower_Pot_C'] = { Inputs = { {Item='Stone',Count=20}, {Item='Glass',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Homestead_Flower_Pot_D'] = { Inputs = { {Item='Stone',Count=20}, {Item='Glass',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Homestead_Flower_Pot_E'] = { Inputs = { {Item='Stone',Count=20}, {Item='Glass',Count=2}, {Item='Organic_Resin',Count=2} } },
    ['Homestead_WildFlower_Bluebell'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Homestead_WildFlower_Strawflower'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Homestead_WildFlower_Poppy'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Homestead_WildFlower_Daisy'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Homestead_WildFlower_Lavender'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Tree_Sap',Count=3} } },
    ['Fertility_Serum_Chicken'] = { Inputs = { {Item='Seed',Count=10}, {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Chicken_Exotic'] = { Inputs = { {Item='MetaResource',Count=5}, {Item='Seed',Count=10} } },
    ['Fertility_Serum_Cow'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Cow_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Moa'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Moa_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Buffalo'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Buffalo_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Pig'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Pig_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Sheep'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Sheep_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Bulk_Shotgun_Shell_Slug'] = { Inputs = { {Item='Shotgun_Casing',Count=5}, {Item='Gunpowder',Count=5}, {Item='Platinum_Shealth',Count=5} } },
    ['Onion_Seeds'] = { Inputs = { {Item='Onion',Count=4} } },
    ['Agave_Seeds'] = { Inputs = { {Item='Agave',Count=4} } },
    ['PricklyPear_Seeds'] = { Inputs = { {Item='PricklyPear',Count=4} } },
    ['Garlic_Seeds'] = { Inputs = { {Item='Garlic',Count=4} } },
    ['Truffle_Seeds'] = { Inputs = { {Item='Truffle',Count=4} } },
    ['Cooked_Banana'] = { Inputs = { {Item='Banana',Count=4} } },
    ['Dried_Banana'] = { Inputs = { {Item='Banana',Count=4} } },
    ['Banana_Porridge'] = { Inputs = { {Item='Banana',Count=1}, {Item='Wheat',Count=2}, {Item='Seed',Count=3} } },
    ['Frozen_Banana'] = { Inputs = { {Item='Banana',Count=1}, {Item='Stick',Count=1}, {Item='Ice',Count=5}, {Item='Cocoa',Count=2} } },
    ['Banana_Tart'] = { Inputs = { {Item='Pastry',Count=2}, {Item='Banana',Count=1}, {Item='Honey',Count=1}, {Item='Egg',Count=1} } },
    ['Soy_Milk'] = { Inputs = { {Item='Bean',Count=8} } },
    ['Food_Banana_Toast'] = { Inputs = { {Item='Banana',Count=1}, {Item='Food_Bread',Count=1}, {Item='Butter',Count=1} } },
    ['Bone_ElephantTusks'] = { Inputs = { {Item='Elephant_Tusk',Count=1} } },
    ['Sandwyrm_Lantern'] = { Inputs = { {Item='Rope',Count=4}, {Item='Glass',Count=12}, {Item='Aluminium',Count=8}, {Item='Epoxy',Count=4}, {Item='Sandwyrm_Egg',Count=2} } },
    ['Sandwyrm_Backpack'] = { Inputs = { {Item='Advanced_Leather',Count=25}, {Item='Carbon_Fiber',Count=6}, {Item='Steel_Screw',Count=10}, {Item='Sandwyrm_Wing',Count=10} } },
    ['Sandwyrm_Lure'] = { Inputs = { {Item='Sandwyrm_Egg',Count=2}, {Item='Copper_Nail',Count=2}, {Item='Rope',Count=2} } },
    ['Sandwyrm_Target'] = { Inputs = { {Item='Epoxy',Count=10}, {Item='Stick',Count=50}, {Item='Silica',Count=5}, {Item='Sandwyrm_Egg',Count=3}, {Item='Sandwyrm_Wing',Count=10} } },
    ['Sandwyrm_Throne'] = { Inputs = { {Item='Sandwyrm_Queen_Head',Count=1}, {Item='Refined_Metal',Count=6}, {Item='Steel_Screw',Count=8}, {Item='Sandwyrm_Egg',Count=5} } },
    ['Homestead_Well'] = { Inputs = { {Item='Refined_Metal',Count=8}, {Item='Wood',Count=20}, {Item='Stone',Count=100}, {Item='Epoxy',Count=4}, {Item='Charcoal',Count=20} } },
    ['Kitchen_Sink'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=10}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=12} } },
    ['Oil_Can'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Aluminium_Screw',Count=5} } },
    ['Lamb_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Lamb_Head',Count=1} } },
    ['Metal_Grate_Floor'] = { Inputs = { {Item='Aluminium',Count=5}, {Item='Steel_Rebar',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Metal_Grate_Stairs'] = { Inputs = { {Item='Aluminium',Count=5}, {Item='Steel_Rebar',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Animal_Bed_Nesting'] = { Inputs = { {Item='Fur',Count=60}, {Item='Wool',Count=10} } },
    ['Deep_Mining_Drill_Oil'] = { Inputs = { {Item='Aluminium',Count=45}, {Item='Electronics',Count=10}, {Item='Steel_Screw',Count=15}, {Item='Compounds',Count=15}, {Item='Carbon_Fiber',Count=10} } },
    ['Homestead_Kitchen_Corner'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Refined_Metal',Count=2}, {Item='Epoxy',Count=10}, {Item='Copper_Nail',Count=12} } },
    ['Homestead_Kitchen_Herbalism'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=8}, {Item='Organic_Resin',Count=5}, {Item='Copper_Nail',Count=20}, {Item='Glass',Count=5} } },
    ['Homestead_Kitchen_Butchery'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=20}, {Item='Copper_Nail',Count=20}, {Item='Steel_Ingot',Count=10} } },
    ['Farmer_Plant_Extract'] = { Inputs = { {Item='Plant_Extract',Count=10} } },
    ['Food_Soda'] = { Inputs = { {Item='Ren',Count=10} } },
    ['Food_Ration'] = { Inputs = { {Item='Ren',Count=10} } },
    ['Food_Oxy'] = { Inputs = { {Item='Ren',Count=10} } },
    ['Food_Gruel'] = { Inputs = { {Item='Ren',Count=1} } },
    ['Fur_Stack'] = { Inputs = { {Item='Fur',Count=200} } },
    ['Sandwyrm_Bow'] = { Inputs = { {Item='Rope',Count=8}, {Item='Carbon_Fiber',Count=18}, {Item='Sandwyrm_Wing',Count=3}, {Item='Steel_Screw',Count=4} } },
    ['Sandwyrm_Biomass'] = { Inputs = { {Item='Sandwyrm_Egg',Count=3} } },
    ['Sandwyrm_Biomass_2'] = { Inputs = { {Item='Sandwyrm_Wing',Count=5} } },
    ['Biomass_To_Sandwyrm_Egg'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Biomass_To_Sandwyrm_Wing'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Pig_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Pig_Head',Count=1} } },
    ['Piglet_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Piglet_Head',Count=1} } },
    ['Homestead_Fireplace'] = { Inputs = { {Item='Clay_Brick',Count=100}, {Item='Wood_Refined',Count=30}, {Item='Tree_Sap',Count=20} } },
    ['Homestead_Fireplace_Ext'] = { Inputs = { {Item='Clay_Brick',Count=50}, {Item='Wood_Refined',Count=20}, {Item='Tree_Sap',Count=10} } },
    ['Homestead_Fireplace_Cap'] = { Inputs = { {Item='Clay_Brick',Count=30}, {Item='Wood_Refined',Count=20}, {Item='Tree_Sap',Count=10} } },
    ['Animal_Silage_Fiber'] = { Inputs = { {Item='Fiber',Count=20} } },
    ['Mission_Drone_Navigation'] = { Inputs = { {Item='Plastics',Count=15}, {Item='Electronics',Count=20}, {Item='Steel_Ingot',Count=10} } },
    ['Mission_Drone_Rotor'] = { Inputs = { {Item='Aluminium',Count=25}, {Item='Steel_Screw',Count=20}, {Item='Synthetics',Count=5} } },
    ['Fertility_Serum_Raptor'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Raptor_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Slinker'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Slinker_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Wolf'] = { Inputs = { {Item='Condensed_Enzymes',Count=3} } },
    ['Fertility_Serum_Wolf_Exotic'] = { Inputs = { {Item='MetaResource',Count=5} } },
    ['Fertility_Serum_Boar'] = { Inputs = { {Item='Condensed_Enzymes',Count=3}, {Item='Seed',Count=5} } },
    ['Fertility_Serum_Boar_Exotic'] = { Inputs = { {Item='MetaResource',Count=5}, {Item='Seed',Count=5} } },
    ['Speeder_Kit'] = { Inputs = { {Item='Oil_Can',Count=1}, {Item='Electronics',Count=45}, {Item='Aluminium_Screw',Count=70}, {Item='Carbon_Fiber',Count=40}, {Item='Synthetics',Count=40}, {Item='Plastics',Count=25}, {Item='Lithium_Refined',Count=30} } },
    ['Checkered_Flag'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['Submachine_Gun_Scout'] = { Inputs = { {Item='Composites',Count=15}, {Item='Titanium_Plate',Count=6}, {Item='Plastics',Count=25}, {Item='Epoxy',Count=15}, {Item='Aluminium_Screw',Count=25}, {Item='Seed_Oil',Count=5} } },
    ['Submachine_Gun_Sandwyrm'] = { Inputs = { {Item='Composites',Count=15}, {Item='Titanium_Plate',Count=6}, {Item='Plastics',Count=25}, {Item='Epoxy',Count=15}, {Item='Aluminium_Screw',Count=25}, {Item='Sandwyrm_Egg',Count=2} } },
    ['Solar_Panel_Lithium'] = { Inputs = { {Item='Electronics',Count=20}, {Item='Steel_Screw',Count=10}, {Item='Ruby_Shaped',Count=10}, {Item='Composites',Count=18}, {Item='Carbon_Fiber',Count=8} } },
    ['Flat_Solar_Panel_Lithium'] = { Inputs = { {Item='Electronics',Count=20}, {Item='Steel_Screw',Count=10}, {Item='Ruby_Shaped',Count=10}, {Item='Composites',Count=18}, {Item='Carbon_Fiber',Count=8} } },
    ['Limestone_Diagonal_Set'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Curved_Set'] = { Inputs = { {Item='Steel_Rebar',Count=12}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Wall_Curved'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Limestone_Advanced_Beams_Set'] = { Inputs = { {Item='Steel_Rebar',Count=4}, {Item='Limestone',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Limestone_Roof_CurvedAngles'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Limestone',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Carcass_Juvenile_Wolf'] = { Inputs = { {Item='AnimalCarcass_Conifer_Wolf_Juvenile',Count=1} } },
    ['Carcass_Juvenile_Snow_Wolf'] = { Inputs = { {Item='AnimalCarcass_Snow_Wolf_Juvenile',Count=1} } },
    ['Butcher_Knife'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=4}, {Item='Steel_Ingot',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Molotov'] = { Inputs = { {Item='Glass_Bottle',Count=1}, {Item='Rope',Count=2} } },
    ['Carcass_Juvenile_Tundra_Monkey'] = { Inputs = { {Item='AnimalCarcass_Tundra_Monkey_Juvenile',Count=1} } },
    ['Fertility_Serum_Tundra_Monkey'] = { Inputs = { {Item='Condensed_Enzymes',Count=3}, {Item='Banana',Count=3} } },
    ['Fertility_Serum_Tundra_Monkey_Exotic'] = { Inputs = { {Item='MetaResource',Count=5}, {Item='Banana',Count=3} } },
    ['Sawblade'] = { Inputs = { {Item='Refined_Metal',Count=3} } },
    ['Interior_Wood_Floor_Curved'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Copper_Nail',Count=4} } },
    ['Carcass_Komodo'] = { Inputs = { {Item='AnimalCarcass_Komodo',Count=1} } },
    ['Carcass_Lava_Komodo'] = { Inputs = { {Item='AnimalCarcass_Lava_Komodo',Count=1} } },
    ['Thumper_Deep'] = { Inputs = { {Item='Titanium_Ingot',Count=10}, {Item='Electronics',Count=8}, {Item='Aluminium_Screw',Count=18}, {Item='Composites',Count=15}, {Item='Concrete_Mix',Count=8}, {Item='Synthetics',Count=10} } },
    ['Fertility_Serum_Ubis'] = { Inputs = { {Item='Condensed_Enzymes',Count=3}, {Item='Acidic_Glands',Count=2} } },
    ['Fertility_Serum_Ubis_Exotic'] = { Inputs = { {Item='MetaResource',Count=5}, {Item='Acidic_Glands',Count=2} } },
    ['Biomass_To_Boss_Vestiage_Wolf'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Biomass_To_Boss_Vestiage_Sandworm'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Biomass_To_Boss_Vestiage_Scorpion'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Biomass_To_Boss_Vestiage_Landshark'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Biomass_To_Boss_Vestiage_Hammerhead'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Biomass_To_Boss_Vestiage_LavaHunter'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Biomass_To_Boss_Vestiage_Golem'] = { Inputs = { {Item='Biomass',Count=4} } },
    ['Biomass_To_Boss_Vestiage_Mammoth'] = { Inputs = { {Item='Biomass',Count=4} } },
    ['Biomass_To_Boss_Vestiage_Ape'] = { Inputs = { {Item='Biomass',Count=4} } },
    ['Biomass_To_Boss_Vestiage_SandWyrm'] = { Inputs = { {Item='Biomass',Count=2} } },
    ['Carbon_Fishing_Rod'] = { Inputs = { {Item='Carbon_Fiber',Count=8}, {Item='Steel_Screw',Count=10}, {Item='Rope',Count=5} } },
    ['T2_Launcher'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Leather',Count=25}, {Item='Refined_Metal',Count=30}, {Item='Epoxy',Count=10}, {Item='Iron_Nail',Count=30} } },
    ['Rudimentary_Smoke_Grenade'] = { Inputs = { {Item='Fiber',Count=5}, {Item='Gunpowder',Count=4} } },
    ['Rudimentary_Impact_Grenade'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Gunpowder',Count=6} } },
}
return Chunk
