-- Recipes Chunk 5
local Chunk = {
    ['Homestead_Rocking_Chair_Single'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=3}, {Item='Copper_Nail',Count=20} } },
    ['Homestead_Rocking_Chair_Double'] = { Inputs = { {Item='Wood_Refined',Count=100}, {Item='Refined_Metal',Count=6}, {Item='Copper_Nail',Count=40} } },
    ['Homestead_Picnic_Table'] = { Inputs = { {Item='Wood_Refined',Count=100}, {Item='Wool',Count=5}, {Item='Iron_Nail',Count=40} } },
    ['Homestead_Barbed_Wire_Fence'] = { Inputs = { {Item='Refined_Metal',Count=8}, {Item='Wood',Count=20}, {Item='Copper_Wire',Count=10} } },
    ['Homestead_Lamp_Ground'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Steel_Screw',Count=10}, {Item='Beeswax',Count=5}, {Item='Glass',Count=5} } },
    ['Homestead_Lamp_Wall'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Steel_Screw',Count=5}, {Item='Beeswax',Count=5}, {Item='Glass',Count=5} } },
    ['Sandworm_Floor'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15}, {Item='Sandworm_Scale',Count=2} } },
    ['Sandworm_Wall'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15}, {Item='Sandworm_Scale',Count=2} } },
    ['Sandworm_Wall_Angle'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Sandworm_Scale',Count=1} } },
    ['Sandworm_Ramp'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15}, {Item='Sandworm_Scale',Count=2} } },
    ['Sandworm_Beam'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=6}, {Item='Sandworm_Scale',Count=1} } },
    ['Sandworm_Roof_Corner'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Sandworm_Scale',Count=2} } },
    ['Sandworm_Half_Pitch'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Sandworm_Scale',Count=2} } },
    ['Sandworm_Halfpiece'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8}, {Item='Sandworm_Scale',Count=2} } },
    ['Assault_Rifle_T4'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Titanium_Plate',Count=10}, {Item='Titanium_Ingot',Count=15}, {Item='Epoxy',Count=20}, {Item='Steel_Screw',Count=50}, {Item='Seed_Oil',Count=8} } },
    ['Synthetic_Enzymes'] = { Inputs = { {Item='Organic_Resin',Count=1}, {Item='Spoiled_Meat',Count=2}, {Item='Charcoal',Count=2} } },
    ['Synthetic_Enzymes_2'] = { Inputs = { {Item='Honeycomb',Count=1}, {Item='Spoiled_Plants',Count=2}, {Item='Charcoal',Count=2} } },
    ['Synthetic_Enzymes_3'] = { Inputs = { {Item='Seed_Oil',Count=1}, {Item='Spoiled_Plants',Count=2}, {Item='Spoiled_Meat',Count=2} } },
    ['Flour_Corn'] = { Inputs = { {Item='Corn',Count=10} } },
    ['Flour_Potato'] = { Inputs = { {Item='Potato',Count=10} } },
    ['Seed_Oil_Soy'] = { Inputs = { {Item='Bean',Count=25} } },
    ['Seed_Oil_Avocado'] = { Inputs = { {Item='Avocado',Count=15} } },
    ['Sugar_Kumara'] = { Inputs = { {Item='Kumara',Count=5} } },
    ['Sugar_Honey'] = { Inputs = { {Item='Honey',Count=5} } },
    ['Assault_Rifle_Legacy'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Titanium_Ingot',Count=40}, {Item='Epoxy',Count=15}, {Item='Steel_Screw',Count=25}, {Item='Seed_Oil',Count=5} } },
    ['AssaultRifle_Round'] = { Inputs = { {Item='Ammo_Casing',Count=2}, {Item='Gunpowder',Count=3} } },
    ['AssaultRifle_Round_Incendiary'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=1}, {Item='Gunpowder',Count=5} } },
    ['AssaultRifle_Round_Explosive'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=5}, {Item='Volatile_Substance',Count=1} } },
    ['Bulk_AssaultRifle_Round'] = { Inputs = { {Item='Ammo_Casing',Count=10}, {Item='Gunpowder',Count=15} } },
    ['AssaultRifle_Armor_Piercing_Round'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=1}, {Item='Platinum_Shealth',Count=1} } },
    ['AssaultRifle_Round_Obsidian'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=5}, {Item='Shaped_Obsidian',Count=1} } },
    ['AssaultRifle_Round_Cold_Steel'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=5}, {Item='Cold_Steel_Ingot',Count=1} } },
    ['AssaultRifle_Round_Iron_Wood'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=5}, {Item='Refined_Iron_Wood',Count=1} } },
    ['PlatinumWeave_Curtain_Door'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=14}, {Item='Fiber',Count=15} } },
    ['SilkWeave_Curtain_Door'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Refined_Metal',Count=6}, {Item='Fiber',Count=45}, {Item='Gold_Wire',Count=20} } },
    ['Fur_Curtain_Window'] = { Inputs = { {Item='Fur',Count=20}, {Item='Wood',Count=5}, {Item='Fiber',Count=10} } },
    ['PlatinumWeave_Curtain_Window'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=14}, {Item='Fiber',Count=10} } },
    ['SilkWeave_Curtain_Window'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Refined_Metal',Count=6}, {Item='Fiber',Count=35}, {Item='Gold_Wire',Count=20} } },
    ['Seed_Extractor'] = { Inputs = { {Item='Wood',Count=15}, {Item='Fiber',Count=20}, {Item='Stone',Count=25}, {Item='Charcoal',Count=10} } },
    ['Corn_Seeds'] = { Inputs = { {Item='Corn',Count=3} } },
    ['Wheat_Seeds'] = { Inputs = { {Item='Wheat',Count=6} } },
    ['Reed_Flower_Seeds'] = { Inputs = { {Item='Reed_Flower',Count=1} } },
    ['Yeast_Seeds'] = { Inputs = { {Item='Yeast',Count=2} } },
    ['Lily_Seeds'] = { Inputs = { {Item='Lily',Count=2} } },
    ['Berry_Seeds'] = { Inputs = { {Item='Berry',Count=5} } },
    ['Pumpkin_Seeds'] = { Inputs = { {Item='Pumpkin',Count=2} } },
    ['Bean_Seeds'] = { Inputs = { {Item='Bean',Count=3} } },
    ['Squash_Seeds'] = { Inputs = { {Item='Squash',Count=2} } },
    ['Watermelon_Seeds'] = { Inputs = { {Item='Watermelon',Count=2} } },
    ['Cocoa_Seeds'] = { Inputs = { {Item='Cocoa',Count=3} } },
    ['Coffee_Seeds'] = { Inputs = { {Item='Coffee',Count=3} } },
    ['GreenTea_Seeds'] = { Inputs = { {Item='GreenTea',Count=3} } },
    ['WildTea_Seeds'] = { Inputs = { {Item='WildTea',Count=3} } },
    ['Carrot_Seeds'] = { Inputs = { {Item='Carrot',Count=1} } },
    ['Mushroom_Seeds'] = { Inputs = { {Item='Mushroom',Count=2} } },
    ['Rhubarb_Seeds'] = { Inputs = { {Item='Rhubarb',Count=1} } },
    ['Kumara_Seeds'] = { Inputs = { {Item='Kumara',Count=1} } },
    ['Avocado_Seeds'] = { Inputs = { {Item='Avocado',Count=1} } },
    ['Strawberry_Seeds'] = { Inputs = { {Item='Strawberry',Count=7} } },
    ['Fiber_Seeds'] = { Inputs = { {Item='Fiber',Count=25} } },
    ['Tomato_Seeds'] = { Inputs = { {Item='Tomato',Count=3} } },
    ['Potato_Seeds'] = { Inputs = { {Item='Potato',Count=4} } },
    ['Sugar_Cane'] = { Inputs = { {Item='Sugar_Cane',Count=4} } },
    ['Coconut_Seeds_Young'] = { Inputs = { {Item='Coconut_young',Count=1} } },
    ['Coconut_Seeds_Old'] = { Inputs = { {Item='Coconut_mature',Count=2} } },
    ['Bramble_Seeds'] = { Inputs = { {Item='Bramble',Count=1} } },
    ['Kiwi_Fruit_Seeds'] = { Inputs = { {Item='Kiwi_Fruit',Count=2} } },
    ['Sickle_Attachment_Harvest_Seeds'] = { Inputs = { {Item='Steel_Ingot',Count=3}, {Item='Epoxy',Count=3}, {Item='Coal_Ore',Count=2} } },
    ['Seed_Fertilizer'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Volatile_Substance',Count=1} } },
    ['Seed_Fertilizer_2'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Volatile_Substance_Inert',Count=3} } },
    ['Recovery_Beacon_Tracker'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Gold_Wire',Count=25}, {Item='Electronics',Count=5}, {Item='Copper_Wire',Count=25} } },
    ['Enzyme_Elixir'] = { Inputs = { {Item='Synthetic_Enzymes',Count=2}, {Item='Charcoal',Count=5}, {Item='Salt',Count=3} } },
    ['Seed_Harvester'] = { Inputs = { {Item='Steel_Ingot',Count=12}, {Item='Epoxy',Count=4}, {Item='Rope',Count=8}, {Item='Wood_Refined',Count=18} } },
    ['Coconut_Seeds_Mid'] = { Inputs = { {Item='Coconut_mid',Count=2} } },
    ['Stone_Sign_Small'] = { Inputs = { {Item='Stone',Count=16}, {Item='Iron_Nail',Count=4} } },
    ['Brick_Sign_Small'] = { Inputs = { {Item='Clay_Brick',Count=10}, {Item='Concrete_Mix',Count=2}, {Item='Iron_Nail',Count=4} } },
    ['Iron_Sign_Small'] = { Inputs = { {Item='Refined_Metal',Count=8}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4} } },
    ['Composite_Sign_Small'] = { Inputs = { {Item='Composites',Count=2}, {Item='Epoxy',Count=2}, {Item='Aluminium',Count=4} } },
    ['Snow_Viscid_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Snow_Slug_Head',Count=1} } },
    ['Snow_Mammoth_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Snow_Mammoth_Head',Count=1} } },
    ['Enzyme_Propagation_Unit'] = { Inputs = { {Item='Titanium_Plate',Count=2}, {Item='Electronics',Count=10}, {Item='Steel_Screw',Count=10}, {Item='Composites',Count=4}, {Item='Epoxy',Count=11} } },
    ['Wooden_Armor_Stand'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Copper_Nail',Count=15}, {Item='Seed_Oil',Count=1} } },
    ['Mission_Vesper_Cage'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Steel_Screw',Count=8}, {Item='Carbon_Paste',Count=2} } },
    ['Enzyme_Virus'] = { Inputs = { {Item='Synthetic_Enzymes',Count=3}, {Item='Super_Cooled_Ice',Count=1}, {Item='Salt',Count=3} } },
    ['Gas_Fireplace'] = { Inputs = { {Item='Refined_Metal',Count=22}, {Item='Epoxy',Count=14}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Ingot',Count=8}, {Item='Steel_Screw',Count=8} } },
    ['Gas_Fireplace_Ext'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Epoxy',Count=2} } },
    ['Gas_Fireplace_Cap'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Epoxy',Count=4}, {Item='Steel_Ingot',Count=2} } },
    ['Electric_Fireplace'] = { Inputs = { {Item='Aluminium',Count=18}, {Item='Epoxy',Count=14}, {Item='Concrete_Mix',Count=4}, {Item='Titanium_Ingot',Count=8} } },
    ['Electric_Fireplace_Ext'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Epoxy',Count=2}, {Item='Titanium_Ingot',Count=1} } },
    ['Electric_Fireplace_Cap'] = { Inputs = { {Item='Aluminium',Count=6}, {Item='Epoxy',Count=2}, {Item='Titanium_Ingot',Count=4} } },
    ['Banana_Seeds'] = { Inputs = { {Item='Banana',Count=2} } },
    ['Mission_Sonic_Device'] = { Inputs = { {Item='Gold_Wire',Count=25}, {Item='Copper_Wire',Count=50}, {Item='Steel_Ingot',Count=25}, {Item='Aluminium',Count=30} } },
    ['Concrete_Door'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Platinum_Ingot',Count=2}, {Item='Steel_Screw',Count=4} } },
    ['Mission_Homogenized_Sample'] = { Inputs = { {Item='Mission_DNA_TissueSample',Count=1} } },
    ['Mission_Heated_Lysate'] = { Inputs = { {Item='Mission_DNA_Lysate',Count=1} } },
    ['Mission_Surgical_Equipment'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Platinum_Weave',Count=3} } },
    ['Mission_Buffer'] = { Inputs = { {Item='Reed_Flower',Count=2}, {Item='Epoxy',Count=5} } },
    ['Mission_Ethanol'] = { Inputs = { {Item='Spoiled_Meat',Count=2}, {Item='Epoxy',Count=5} } },
    ['Mission_Stirrer'] = { Inputs = { {Item='Electronics',Count=2}, {Item='Copper_Wire',Count=5}, {Item='Refined_Metal',Count=2} } },
    ['Mission_Burner'] = { Inputs = { {Item='Glass',Count=3}, {Item='Copper_Wire',Count=5}, {Item='Refined_Metal',Count=2} } },
    ['Mission_Centrifuge'] = { Inputs = { {Item='Glass',Count=3}, {Item='Copper_Wire',Count=5}, {Item='Refined_Metal',Count=2}, {Item='Electronics',Count=2} } },
    ['Mission_Microscope'] = { Inputs = { {Item='Glass',Count=5}, {Item='Copper_Wire',Count=5}, {Item='Refined_Metal',Count=2} } },
    ['Mission_Moisture'] = { Inputs = { {Item='Copper_Wire',Count=5}, {Item='Refined_Metal',Count=2}, {Item='Electronics',Count=5} } },
    ['Mission_Scales'] = { Inputs = { {Item='Gold_Wire',Count=5}, {Item='Refined_Metal',Count=3}, {Item='Electronics',Count=2} } },
    ['Pouch_Generic'] = { Inputs = { {Item='Rope',Count=5}, {Item='Leather',Count=20}, {Item='Iron_Nail',Count=5} } },
    ['Pouch_Generic_Red'] = { Inputs = { {Item='Rope',Count=5}, {Item='Leather',Count=20}, {Item='Iron_Nail',Count=5}, {Item='Paints',Count=5} } },
    ['Pouch_Generic_Green'] = { Inputs = { {Item='Rope',Count=5}, {Item='Leather',Count=20}, {Item='Iron_Nail',Count=5}, {Item='Paints',Count=5} } },
    ['Pouch_Generic_Blue'] = { Inputs = { {Item='Rope',Count=5}, {Item='Leather',Count=20}, {Item='Iron_Nail',Count=5}, {Item='Paints',Count=5} } },
    ['Great_Hunts_Boss_Upgrade'] = { Inputs = { {Item='Glass',Count=30}, {Item='Carbon_Fiber',Count=30}, {Item='Copper_Wire',Count=50}, {Item='Aluminium',Count=40}, {Item='Titanium_Plate',Count=10}, {Item='Electronics',Count=20}, {Item='Epoxy',Count=25} } },
    ['Sand_Armor_Head'] = { Inputs = { {Item='Carbon_Fiber',Count=20}, {Item='Platinum_Weave',Count=15}, {Item='Electronics',Count=1}, {Item='Gold_Wire',Count=15} } },
    ['Sand_Armor_Chest'] = { Inputs = { {Item='Carbon_Fiber',Count=30}, {Item='Platinum_Weave',Count=30}, {Item='Electronics',Count=2}, {Item='Gold_Wire',Count=20} } },
    ['Sand_Armor_Arms'] = { Inputs = { {Item='Carbon_Fiber',Count=20}, {Item='Platinum_Weave',Count=10}, {Item='Electronics',Count=1}, {Item='Gold_Wire',Count=10} } },
    ['Sand_Armor_Legs'] = { Inputs = { {Item='Carbon_Fiber',Count=30}, {Item='Platinum_Weave',Count=25}, {Item='Electronics',Count=2}, {Item='Gold_Wire',Count=15} } },
    ['Sand_Armor_Feet'] = { Inputs = { {Item='Carbon_Fiber',Count=20}, {Item='Platinum_Weave',Count=10}, {Item='Electronics',Count=1}, {Item='Gold_Wire',Count=5} } },
    ['Sand_Armor_Backpack'] = { Inputs = { {Item='Carbon_Fiber',Count=30}, {Item='Platinum_Weave',Count=30}, {Item='Electronics',Count=4}, {Item='Gold_Wire',Count=35} } },
    ['Arctic_Armor_Head'] = { Inputs = { {Item='Platinum_Weave',Count=10}, {Item='Glass',Count=10}, {Item='Titanium_Ingot',Count=3} } },
    ['Arctic_Armor_Chest'] = { Inputs = { {Item='Wool',Count=20}, {Item='Epoxy',Count=10}, {Item='Platinum_Weave',Count=10} } },
    ['Arctic_Armor_Arms'] = { Inputs = { {Item='Wool',Count=10}, {Item='Epoxy',Count=5}, {Item='Platinum_Weave',Count=10} } },
    ['Arctic_Armor_Legs'] = { Inputs = { {Item='Wool',Count=20}, {Item='Epoxy',Count=10}, {Item='Platinum_Weave',Count=10} } },
    ['Arctic_Armor_Feet'] = { Inputs = { {Item='Wool',Count=5}, {Item='Epoxy',Count=20}, {Item='Platinum_Weave',Count=5} } },
    ['Miner_Armor_Head'] = { Inputs = { {Item='Titanium_Ingot',Count=5}, {Item='Steel_Rebar',Count=3} } },
    ['Miner_Armor_Chest'] = { Inputs = { {Item='Titanium_Ingot',Count=10}, {Item='Steel_Screw',Count=15}, {Item='Advanced_Leather',Count=20} } },
    ['Miner_Armor_Arms'] = { Inputs = { {Item='Titanium_Ingot',Count=2}, {Item='Steel_Screw',Count=5}, {Item='Advanced_Leather',Count=10} } },
    ['Miner_Armor_Legs'] = { Inputs = { {Item='Titanium_Ingot',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Advanced_Leather',Count=15} } },
    ['Miner_Armor_Feet'] = { Inputs = { {Item='Titanium_Ingot',Count=5}, {Item='Steel_Screw',Count=5}, {Item='Advanced_Leather',Count=10} } },
    ['Thumper_Mini'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Electronics',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Composites',Count=6}, {Item='Concrete_Mix',Count=4}, {Item='Epoxy',Count=10}, {Item='Battery_Shelf_T3',Count=1} } },
    ['Mining_Cart'] = { Inputs = { {Item='Steel_Rebar',Count=4}, {Item='Steel_Screw',Count=10}, {Item='Steel_Ingot',Count=10} } },
    ['Rock_Golem_Armor_Fragment_Coal'] = { Inputs = { {Item='Rock_Golem_Juvenile_Armor_Coal',Count=1} } },
    ['Rock_Golem_Armor_Fragment_Iron'] = { Inputs = { {Item='Rock_Golem_Juvenile_Armor_Iron',Count=1} } },
    ['Rock_Golem_Armor_Fragment_Oxite'] = { Inputs = { {Item='Rock_Golem_Juvenile_Armor_Oxite',Count=1} } },
    ['Rock_Golem_Armor_Fragment_Gold'] = { Inputs = { {Item='Rock_Golem_Juvenile_Armor_Gold',Count=1} } },
    ['Rock_Golem_Armor_Fragment_Copper'] = { Inputs = { {Item='Rock_Golem_Juvenile_Armor_Copper',Count=1} } },
    ['Rock_Golem_Armor_Fragment_Exotics'] = { Inputs = { {Item='Rock_Golem_Juvenile_Armor_Exotic',Count=1} } },
    ['Caveworm_Head_Armor'] = { Inputs = { {Item='Bone',Count=5}, {Item='Leather',Count=10}, {Item='Fiber',Count=20}, {Item='Caveworm_Scale',Count=12} } },
    ['Caveworm_Chest_Armor'] = { Inputs = { {Item='Bone',Count=25}, {Item='Leather',Count=12}, {Item='Caveworm_Scale',Count=28}, {Item='Fiber',Count=40} } },
    ['Caveworm_Arms_Armor'] = { Inputs = { {Item='Bone',Count=5}, {Item='Leather',Count=4}, {Item='Caveworm_Scale',Count=8}, {Item='Fiber',Count=20} } },
    ['Caveworm_Legs_Armor'] = { Inputs = { {Item='Bone',Count=15}, {Item='Leather',Count=9}, {Item='Caveworm_Scale',Count=14}, {Item='Fiber',Count=30} } },
    ['Caveworm_Feet_Armor'] = { Inputs = { {Item='Bone',Count=5}, {Item='Leather',Count=6}, {Item='Caveworm_Scale',Count=8}, {Item='Fiber',Count=20} } },
    ['Saddle_Arctic_Survival'] = { Inputs = { {Item='Platinum_Weave',Count=10}, {Item='Wool',Count=12}, {Item='Rope',Count=5} } },
    ['Uranium'] = { Inputs = { {Item='Uranium_Raw',Count=5} } },
    ['Uranium_Collector'] = { Inputs = { {Item='Titanium_Plate',Count=40}, {Item='Steel_Ingot',Count=40}, {Item='Electronics',Count=30}, {Item='Composites',Count=20}, {Item='Synthetics',Count=30}, {Item='Aluminium_Screw',Count=120} } },
    ['Uranium_Converter'] = { Inputs = { {Item='Titanium_Plate',Count=40}, {Item='Composites',Count=35}, {Item='Electronics',Count=40}, {Item='Plastics',Count=30}, {Item='Epoxy',Count=20}, {Item='Platinum_Ingot',Count=25} } },
    ['Lithium_Refined'] = { Inputs = { {Item='Lithium_Ore',Count=4}, {Item='Oxite',Count=2} } },
    ['Shaped_Ruby'] = { Inputs = { {Item='Ruby_Ore',Count=3} } },
    ['Chainsaw'] = { Inputs = { {Item='Titanium_Plate',Count=10}, {Item='Plastics',Count=50}, {Item='Electronics',Count=10}, {Item='Platinum_Ingot',Count=10}, {Item='Aluminium_Screw',Count=50} } },
    ['Jackhammer'] = { Inputs = { {Item='Titanium_Plate',Count=10}, {Item='Plastics',Count=50}, {Item='Electronics',Count=10}, {Item='Platinum_Ingot',Count=10}, {Item='Aluminium_Screw',Count=50} } },
    ['Mining_Laser'] = { Inputs = { {Item='Steel_Ingot',Count=25}, {Item='Plastics',Count=15}, {Item='Electronics',Count=10}, {Item='Powerbank',Count=1}, {Item='Ruby_Shaped',Count=10}, {Item='Aluminium_Screw',Count=50} } },
    ['Lithium_Axe'] = { Inputs = { {Item='Composites',Count=8}, {Item='Plastics',Count=15}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=10}, {Item='Aluminium_Screw',Count=15}, {Item='Powerbank',Count=1} } },
    ['Lithium_Pickaxe'] = { Inputs = { {Item='Composites',Count=8}, {Item='Plastics',Count=15}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=10}, {Item='Aluminium_Screw',Count=15}, {Item='Powerbank',Count=1} } },
    ['Lithium_Knife'] = { Inputs = { {Item='Composites',Count=8}, {Item='Plastics',Count=15}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=10}, {Item='Aluminium_Screw',Count=15}, {Item='Powerbank',Count=1} } },
    ['Lithium_Throwing_Knife'] = { Inputs = { {Item='Composites',Count=4}, {Item='Plastics',Count=7}, {Item='Electronics',Count=3}, {Item='Lithium_Refined',Count=10}, {Item='Aluminium_Screw',Count=10} } },
    ['Lithium_Spear'] = { Inputs = { {Item='Composites',Count=8}, {Item='Plastics',Count=14}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=15}, {Item='Aluminium_Screw',Count=20}, {Item='Powerbank',Count=1} } },
    ['Lithium_Throwing_Spear'] = { Inputs = { {Item='Composites',Count=4}, {Item='Plastics',Count=10}, {Item='Electronics',Count=3}, {Item='Lithium_Refined',Count=15}, {Item='Aluminium_Screw',Count=20} } },
    ['Lithium_Sickle'] = { Inputs = { {Item='Composites',Count=8}, {Item='Plastics',Count=14}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=15}, {Item='Aluminium_Screw',Count=20}, {Item='Powerbank',Count=1} } },
    ['Lithium_Sledge'] = { Inputs = { {Item='Composites',Count=8}, {Item='Plastics',Count=14}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=25}, {Item='Aluminium_Screw',Count=30}, {Item='Powerbank',Count=1} } },
    ['Lithium_Shield'] = { Inputs = { {Item='Uranium_Inert',Count=20}, {Item='Plastics',Count=14}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=15}, {Item='Aluminium_Screw',Count=20}, {Item='Powerbank',Count=1} } },
    ['Lithium_Bow'] = { Inputs = { {Item='Uranium_Inert',Count=20}, {Item='Plastics',Count=10}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=20}, {Item='Aluminium_Screw',Count=20}, {Item='Powerbank',Count=1} } },
    ['Lithium_Crossbow'] = { Inputs = { {Item='Uranium_Inert',Count=30}, {Item='Plastics',Count=10}, {Item='Electronics',Count=5}, {Item='Lithium_Refined',Count=20}, {Item='Aluminium_Screw',Count=40}, {Item='Powerbank',Count=1} } },
    ['Radiation_Tracker'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Gold_Wire',Count=25}, {Item='Electronics',Count=5}, {Item='Copper_Wire',Count=25} } },
    ['Uranium_Generator'] = { Inputs = { {Item='Titanium_Plate',Count=80}, {Item='Uranium_Inert',Count=60}, {Item='Electronics',Count=80}, {Item='Compounds',Count=30}, {Item='Carbon_Fiber',Count=40}, {Item='Lithium_Refined',Count=50} } },
    ['Glass_Diagonal_Set'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Curved_Set'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Glass',Count=18}, {Item='Epoxy',Count=6} } },
    ['Glass_Wall_Curved'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Advanced_Beams_Set'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Epoxy',Count=6} } },
    ['Glass_Roof_CurvedAngles'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Diagonal_Set_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Curved_Set_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Diagonal_Curved_Wall_Angles_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Glass',Count=18}, {Item='Epoxy',Count=6} } },
    ['Glass_Wall_Curved_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Glass_Advanced_Beams_Set_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Epoxy',Count=6} } },
    ['Glass_Roof_CurvedAngles_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Glass',Count=24}, {Item='Epoxy',Count=6} } },
    ['Concrete_Diagonal_Set'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Curved_Set'] = { Inputs = { {Item='Steel_Rebar',Count=12}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Wall_Curved'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Advanced_Beams_Set'] = { Inputs = { {Item='Steel_Rebar',Count=4}, {Item='Concrete_Mix',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Concrete_Roof_CurvedAngles'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['ClayBrick_Diagonal_Set'] = { Inputs = { {Item='Clay_Brick',Count=34}, {Item='Tree_Sap',Count=6} } },
    ['ClayBrick_Curved_Set'] = { Inputs = { {Item='Clay_Brick',Count=34}, {Item='Tree_Sap',Count=6} } },
    ['ClayBrick_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Clay_Brick',Count=28}, {Item='Tree_Sap',Count=4} } },
    ['ClayBrick_Wall_Curved'] = { Inputs = { {Item='Clay_Brick',Count=34}, {Item='Tree_Sap',Count=6} } },
    ['ClayBrick_Advanced_Beams_Set'] = { Inputs = { {Item='Clay_Brick',Count=26}, {Item='Tree_Sap',Count=4} } },
    ['ClayBrick_Roof_CurvedAngles'] = { Inputs = { {Item='Clay_Brick',Count=34}, {Item='Tree_Sap',Count=6} } },
    ['StoneBrick_Diagonal_Set'] = { Inputs = { {Item='Wood_Refined',Count=8}, {Item='Stone_Brick',Count=34}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['StoneBrick_Curved_Set'] = { Inputs = { {Item='Wood_Refined',Count=8}, {Item='Stone_Brick',Count=34}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['StoneBrick_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=28}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['StoneBrick_Wall_Curved'] = { Inputs = { {Item='Wood_Refined',Count=8}, {Item='Stone_Brick',Count=34}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['StoneBrick_Advanced_Beams_Set'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=18}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['StoneBrick_Roof_CurvedAngles'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=28}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['ScoriaBrick_Diagonal_Set'] = { Inputs = { {Item='Scoria_Brick',Count=44}, {Item='Tree_Sap',Count=6} } },
    ['ScoriaBrick_Curved_Set'] = { Inputs = { {Item='Scoria_Brick',Count=44}, {Item='Tree_Sap',Count=6} } },
    ['ScoriaBrick_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Scoria_Brick',Count=36}, {Item='Tree_Sap',Count=6} } },
    ['ScoriaBrick_Wall_Curved'] = { Inputs = { {Item='Scoria_Brick',Count=44}, {Item='Tree_Sap',Count=6} } },
    ['ScoriaBrick_Advanced_Beams_Set'] = { Inputs = { {Item='Scoria_Brick',Count=34}, {Item='Tree_Sap',Count=6} } },
    ['ScoriaBrick_Roof_CurvedAngles'] = { Inputs = { {Item='Scoria_Brick',Count=40}, {Item='Tree_Sap',Count=6} } },
    ['Hazmat_Head'] = { Inputs = { {Item='Platinum_Weave',Count=20}, {Item='Glass',Count=3} } },
    ['Hazmat_Chest'] = { Inputs = { {Item='Platinum_Weave',Count=50}, {Item='Epoxy',Count=10} } },
    ['Hazmat_Arms'] = { Inputs = { {Item='Platinum_Weave',Count=20}, {Item='Epoxy',Count=10} } },
    ['Hazmat_Legs'] = { Inputs = { {Item='Platinum_Weave',Count=30}, {Item='Epoxy',Count=20} } },
    ['Hazmat_Feet'] = { Inputs = { {Item='Platinum_Weave',Count=10}, {Item='Epoxy',Count=10} } },
    ['Radiation_Protection_Armor_Head'] = { Inputs = { {Item='Uranium_Inert',Count=20}, {Item='Glass',Count=3}, {Item='Synthetics',Count=10}, {Item='Aluminium_Screw',Count=20} } },
    ['Radiation_Protection_Armor_Chest'] = { Inputs = { {Item='Uranium_Inert',Count=50}, {Item='Synthetics',Count=10}, {Item='Aluminium_Screw',Count=40} } },
    ['Radiation_Protection_Armor_Arms'] = { Inputs = { {Item='Uranium_Inert',Count=20}, {Item='Synthetics',Count=10}, {Item='Aluminium_Screw',Count=10} } },
    ['Radiation_Protection_Armor_Legs'] = { Inputs = { {Item='Uranium_Inert',Count=20}, {Item='Synthetics',Count=10}, {Item='Aluminium_Screw',Count=20} } },
    ['Radiation_Protection_Armor_Feet'] = { Inputs = { {Item='Synthetics',Count=30}, {Item='Aluminium_Screw',Count=20} } },
    ['Radiation_Transfusion'] = { Inputs = { {Item='Raw_Meat',Count=1}, {Item='Tree_Sap',Count=1}, {Item='Charcoal',Count=5}, {Item='Salt',Count=5}, {Item='Truffle',Count=2} } },
    ['Carcass_Tundra_Deer'] = { Inputs = { {Item='AnimalCarcass_Tundra_Deer',Count=1} } },
    ['Telsa_Coil'] = { Inputs = { {Item='Copper_Wire',Count=200}, {Item='Plastics',Count=40}, {Item='Electronics',Count=20}, {Item='Powerbank',Count=4}, {Item='Composites',Count=50}, {Item='Ruby_Shaped',Count=20} } },
    ['Turret_Flamethrower'] = { Inputs = { {Item='Titanium_Plate',Count=8}, {Item='Electronics',Count=12}, {Item='Composites',Count=12}, {Item='Synthetics',Count=30}, {Item='Compounds',Count=20}, {Item='Jerrycan',Count=1} } },
    ['Mission_Makeshift_Beacon'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Rope',Count=10}, {Item='Refined_Copper',Count=20}, {Item='Tree_Sap',Count=25} } },
    ['Carcass_Slinker'] = { Inputs = { {Item='AnimalCarcass_Slinker',Count=1} } },
    ['Food_Cooked_Onion'] = { Inputs = { {Item='Onion',Count=1} } },
    ['Food_Caramelized_Onion'] = { Inputs = { {Item='Onion',Count=8}, {Item='Salt',Count=6} } },
    ['Food_French_Onion_Soup'] = { Inputs = { {Item='Onion',Count=6}, {Item='Raw_Meat',Count=6} } },
    ['Food_Onion_Rings'] = { Inputs = { {Item='Onion',Count=3}, {Item='Flour',Count=3}, {Item='Salt',Count=4} } },
    ['Food_Onion_Souffle'] = { Inputs = { {Item='Onion',Count=4}, {Item='Egg',Count=4} } },
    ['Food_Cooked_Agave'] = { Inputs = { {Item='Agave',Count=1} } },
    ['Food_Agave_Syrup'] = { Inputs = { {Item='Agave',Count=4} } },
    ['Drink_Tequila'] = { Inputs = { {Item='Agave',Count=10}, {Item='Glass_Bottle',Count=1} } },
    ['Food_Glazed_Carrots'] = { Inputs = { {Item='Carrot',Count=4}, {Item='Agave_Syrup',Count=2} } },
    ['Food_Pumpkin_Pie'] = { Inputs = { {Item='Pumpkin',Count=3}, {Item='Agave_Syrup',Count=2}, {Item='Egg',Count=8}, {Item='Cheese',Count=2} } },
    ['Food_Cooked_PricklyPear'] = { Inputs = { {Item='PricklyPear',Count=1} } },
    ['Drink_PricklyPear_Margarita'] = { Inputs = { {Item='PricklyPear',Count=6}, {Item='Tequila',Count=1} } },
    ['Food_PricklyPear_Jelly'] = { Inputs = { {Item='PricklyPear',Count=12}, {Item='Sugar',Count=4}, {Item='Glass_Jar',Count=1} } },
    ['Food_PricklyPear_Muffins'] = { Inputs = { {Item='PricklyPear',Count=5}, {Item='Sugar',Count=2}, {Item='Egg',Count=5}, {Item='Flour',Count=6}, {Item='Butter',Count=2} } },
    ['Food_Cooked_Garlic'] = { Inputs = { {Item='Garlic',Count=1} } },
    ['Food_Garlic_Butter'] = { Inputs = { {Item='Garlic',Count=4}, {Item='Butter',Count=4} } },
    ['Food_Garlic_Bread'] = { Inputs = { {Item='Dough_Bread',Count=2}, {Item='Garlic_Butter',Count=4} } },
    ['Food_Garlic_Pizza'] = { Inputs = { {Item='Dough_Flatbread',Count=2}, {Item='Garlic_Butter',Count=4} } },
    ['Food_Smoked_Garlic'] = { Inputs = { {Item='Garlic',Count=3}, {Item='Seed_Oil',Count=1}, {Item='Salt',Count=4} } },
    ['Food_Cooked_Truffle'] = { Inputs = { {Item='Truffle',Count=1} } },
    ['Drink_Vodka'] = { Inputs = { {Item='Potato',Count=18}, {Item='Wheat',Count=8}, {Item='Glass_Bottle',Count=1} } },
    ['Drink_Truffle_Vodka'] = { Inputs = { {Item='Vodka',Count=1}, {Item='Truffle',Count=2} } },
    ['Food_Truffle_Focaccia'] = { Inputs = { {Item='Truffle',Count=4}, {Item='Dough_Flatbread',Count=4} } },
    ['Food_Truffle_Pasta'] = { Inputs = { {Item='Truffle',Count=3}, {Item='Egg',Count=6}, {Item='Mushroom',Count=6}, {Item='Cheese',Count=2} } },
    ['Food_Truffle_Fries'] = { Inputs = { {Item='Potato',Count=4}, {Item='Truffle',Count=2}, {Item='Garlic',Count=1}, {Item='Animal_Fat',Count=1} } },
    ['Food_Banana_Bread'] = { Inputs = { {Item='Banana',Count=10}, {Item='Dough_Bread',Count=4}, {Item='Flour',Count=2}, {Item='Salt',Count=1}, {Item='Butter',Count=1}, {Item='Sugar',Count=2} } },
    ['Carcass_Chew'] = { Inputs = { {Item='AnimalCarcass_Chew',Count=1} } },
    ['Charging_Station_Wall'] = { Inputs = { {Item='Electronics',Count=10}, {Item='Concrete_Mix',Count=8}, {Item='Steel_Screw',Count=25}, {Item='Glass',Count=6}, {Item='Copper_Wire',Count=65}, {Item='Aluminium',Count=5} } },
    ['Nailgun'] = { Inputs = { {Item='Titanium_Plate',Count=3}, {Item='Plastics',Count=10}, {Item='Electronics',Count=10}, {Item='Iron_Nail',Count=20}, {Item='Powerbank',Count=1} } },
    ['National_Flag_NewZealand'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Australia'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Belgium'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Brazil'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Canada'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_China'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Czech'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Denmark'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_EuropeanUnion'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Finland'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_France'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Germany'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Hungry'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Italy'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Japan'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Netherlands'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Norway'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Romania'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Russia'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_SouthAfrica'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_SouthKorea'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Spain'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Sweden'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Switzerland'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Taiwan'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Turkey'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_Ukraine'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_UnitedKingdom'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['National_Flag_UnitedStates'] = { Inputs = { {Item='Rope',Count=5}, {Item='Steel_Ingot',Count=5} } },
    ['Attachment_Tool_Durability_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Tool_Durability_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Tool_Attachment_Durability_1',Count=1} } },
    ['Attachment_Tool_StaminaCost_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Tool_StaminaCost_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Tool_Attachment_StaminaCost_1',Count=1} } },
    ['Attachment_Knife_VestigeChance_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Knife_VestigeChance_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Knife_Attachment_VestigeChance_1',Count=1} } },
    ['Attachment_Pickaxe_MiningRadius_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Pickaxe_MiningRadius_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Pickaxe_Attachment_MiningRadius_1',Count=1} } },
    ['Attachment_Pickaxe_BauxiteYield_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Pickaxe_BauxiteYield_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Pickaxe_Attachment_BauxiteYield_1',Count=1} } },
    ['Attachment_Axe_FellingYield_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Axe_FellingYield_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Axe_Attachment_Felling_Yield_1',Count=1} } },
    ['Attachment_Axe_FellingDamage_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Axe_FellingDamage_2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Axe_Attachment_FellingDamage_1',Count=1} } },
    ['Attachment_Sledgehammer_Slow_1'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Leather',Count=6}, {Item='Wood_Refined',Count=6} } },
    ['Attachment_Sledgehammer_Slow2'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Epoxy',Count=2}, {Item='Copper_Nail',Count=4}, {Item='Sledgehammer_Attachment_Slow_1',Count=1} } },
    ['Attachment_Armor_Comfort_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Glass',Count=6} } },
    ['Attachment_Armor_Comfort_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Epoxy',Count=4}, {Item='Armor_Attachment_Comfort_1',Count=1} } },
    ['Attachment_Arms_FistDamage_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Glass',Count=6} } },
    ['Attachment_Arms_FistDamage_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Epoxy',Count=4}, {Item='Arms_Attachment_FistDamage_1',Count=1} } },
    ['Attachment_Arms_ThrowAccuracy_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Glass',Count=6} } },
    ['Attachment_Arms_ThrowAccuracy_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Epoxy',Count=4}, {Item='Arms_Attachment_ThrowAccuracy_1',Count=1} } },
    ['Attachment_Legs_Jump_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Glass',Count=6} } },
    ['Attachment_Legs_Jump_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Epoxy',Count=4}, {Item='Legs_Attachment_Jump_1',Count=1} } },
    ['Attachment_Chest_Oxygen_1'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Epoxy',Count=4}, {Item='Glass',Count=6} } },
    ['Attachment_Chest_Oxygen_2'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Electronics',Count=1}, {Item='Epoxy',Count=4}, {Item='Chest_Attachment_Oxygen_1',Count=1} } },
    ['Attachment_Guns_Damage_1'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=1} } },
    ['Attachment_Guns_Damage_2'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Glass',Count=1}, {Item='Guns_Attachment_Damage_1',Count=1} } },
    ['Attachment_Guns_ExtendedAmmo_1'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=1} } },
    ['Attachment_Guns_ExtendedAmmo_2'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Glass',Count=1}, {Item='Guns_Attachment_ExtendedAmmo_1',Count=1} } },
    ['Attachment_Pistol_Accuracy_1'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=1} } },
    ['Attachment_Pistol_Accuracy_2'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Glass',Count=1}, {Item='Pistol_Attachment_Accuracy_1',Count=1} } },
    ['Attachment_Rifle_Accuracy_1'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=1} } },
    ['Attachment_Rifle_Accuracy_2'] = { Inputs = { {Item='Platinum_Ingot',Count=2}, {Item='Glass',Count=1}, {Item='Rifle_Attachment_Accuracy_1',Count=1} } },
    ['Orka_Arctic_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Orka_Arctic_Head',Count=1} } },
    ['Thumper_Sandworm'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Electronics',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Composites',Count=6}, {Item='Concrete_Mix',Count=4}, {Item='Epoxy',Count=10}, {Item='Battery_Shelf_T3',Count=1} } },
    ['Flat_Solar_Panel'] = { Inputs = { {Item='Electronics',Count=30}, {Item='Steel_Screw',Count=10}, {Item='Glass',Count=60}, {Item='Composites',Count=18}, {Item='Carbon_Fiber',Count=8} } },
    ['Pistol_Round_Uranium'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=5}, {Item='Uranium_Inert',Count=1} } },
    ['Pistol_Round_Lithium'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=5}, {Item='Lithium_Refined',Count=2} } },
    ['Shotgun_Shell_Uranium'] = { Inputs = { {Item='Ammo_Shell_Buckshot',Count=5}, {Item='Uranium_Inert',Count=1} } },
    ['Shotgun_Shell_Lithium'] = { Inputs = { {Item='Ammo_Shell_Buckshot',Count=5}, {Item='Lithium_Refined',Count=2} } },
    ['Rifle_Round_Uranium'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=5}, {Item='Uranium_Inert',Count=1} } },
    ['Rifle_Round_Lithium'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=5}, {Item='Lithium_Refined',Count=2} } },
    ['AssaultRifle_Round_Uranium'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=5}, {Item='Uranium_Inert',Count=1} } },
    ['AssaultRifle_Round_Lithium'] = { Inputs = { {Item='Ammo_AssaultRifle_Round',Count=5}, {Item='Lithium_Refined',Count=2} } },
    ['Flare_Yellow'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Sulfur',Count=1} } },
    ['Flare_Green'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Sulfur',Count=1} } },
    ['Flare_Red'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Sulfur',Count=1} } },
    ['Flare_Blue'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Sulfur',Count=1} } },
    ['Yeti_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Yeti_Head',Count=1} } },
    ['Synthetic_Armor_Head'] = { Inputs = { {Item='Synthetics',Count=20}, {Item='Glass',Count=3}, {Item='Composites',Count=10} } },
    ['Synthetic_Armor_Chest'] = { Inputs = { {Item='Synthetics',Count=50}, {Item='Platinum_Weave',Count=10} } },
    ['Synthetic_Armor_Arms'] = { Inputs = { {Item='Synthetics',Count=30}, {Item='Platinum_Weave',Count=10} } },
    ['Synthetic_Armor_Legs'] = { Inputs = { {Item='Synthetics',Count=30}, {Item='Platinum_Weave',Count=30} } },
    ['Synthetic_Armor_Feet'] = { Inputs = { {Item='Synthetics',Count=20} } },
    ['Fortification_Concrete_Wall'] = { Inputs = { {Item='Steel_Rebar',Count=20}, {Item='Concrete_Mix',Count=10}, {Item='Steel_Screw',Count=10} } },
    ['Fortification_Concrete_Gate'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Concrete_Mix',Count=5}, {Item='Steel_Screw',Count=20} } },
    ['Fortification_Concrete_Walkway'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Concrete_Mix',Count=15}, {Item='Steel_Screw',Count=10} } },
    ['Fortification_Concrete_Platform'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Concrete_Mix',Count=10}, {Item='Steel_Screw',Count=15} } },
    ['Fortification_Concrete_Spike'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Concrete_Mix',Count=5}, {Item='Steel_Screw',Count=10} } },
    ['Fortification_Stone_Wall'] = { Inputs = { {Item='Stone',Count=50}, {Item='Tree_Sap',Count=20} } },
    ['Fortification_Stone_Spikes'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Tree_Sap',Count=10}, {Item='Copper_Nail',Count=10} } },
    ['Fortification_Stone_Gate'] = { Inputs = { {Item='Stone',Count=20}, {Item='Tree_Sap',Count=20}, {Item='Wood_Refined',Count=30}, {Item='Copper_Nail',Count=10} } },
    ['Fortification_Stone_Walkways'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Copper_Nail',Count=20} } },
    ['Fortification_Stone_Platform'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Copper_Nail',Count=25} } },
    ['Laser_Pistol'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Plastics',Count=30}, {Item='Electronics',Count=5}, {Item='Powerbank',Count=1}, {Item='Ruby_Shaped',Count=5} } },
    ['Attachment_Laser_Converison_Fire'] = { Inputs = { {Item='Ruby_Shaped',Count=2}, {Item='Glass',Count=5}, {Item='Shaped_Obsidian',Count=5} } },
    ['Attachment_Laser_Converison_Frost'] = { Inputs = { {Item='Ruby_Shaped',Count=2}, {Item='Glass',Count=5}, {Item='Super_Cooled_Ice',Count=5} } },
    ['Attachment_Laser_Converison_Electric'] = { Inputs = { {Item='Ruby_Shaped',Count=2}, {Item='Glass',Count=5}, {Item='Lithium_Refined',Count=5} } },
    ['Attachment_Laser_Converison_Poison'] = { Inputs = { {Item='Ruby_Shaped',Count=2}, {Item='Glass',Count=5}, {Item='Refined_Iron_Wood',Count=5} } },
    ['Raptor_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Raptor_Head',Count=1} } },
    ['Raptor_Desert_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Raptor_Desert_Head',Count=1} } },
    ['SulfurWorm_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='SulfurWorm_Head',Count=1} } },
    ['Creature_Bait_Orka'] = { Inputs = { {Item='Wheat',Count=3}, {Item='Animal_Fat',Count=2}, {Item='Raw_Meat',Count=5} } },
    ['Creature_Bait_Storca'] = { Inputs = { {Item='Carrot',Count=2}, {Item='Seed',Count=6}, {Item='Yeast',Count=3} } },
    ['Stone_Brick_Fireplace'] = { Inputs = { {Item='Stone_Brick',Count=100}, {Item='Wood_Refined',Count=30}, {Item='Tree_Sap',Count=20} } },
    ['Stone_Brick_Fireplace_Ext'] = { Inputs = { {Item='Stone_Brick',Count=50}, {Item='Wood_Refined',Count=20}, {Item='Tree_Sap',Count=10} } },
    ['Stone_Brick_Fireplace_Cap'] = { Inputs = { {Item='Stone_Brick',Count=30}, {Item='Wood_Refined',Count=20}, {Item='Tree_Sap',Count=10}, {Item='Refined_Metal',Count=10} } },
    ['Saddle_Raptor'] = { Inputs = { {Item='Platinum_Weave',Count=15}, {Item='Carbon_Fiber',Count=10}, {Item='Rope',Count=5} } },
    ['Saddle_Mammoth_Standard'] = { Inputs = { {Item='Platinum_Weave',Count=15}, {Item='Carbon_Fiber',Count=10}, {Item='Rope',Count=20} } },
    ['Creature_Bait_Tundra_Monkey'] = { Inputs = { {Item='Banana',Count=2}, {Item='Stick',Count=6}, {Item='Super_Cooled_Ice',Count=3} } },
    ['Uranium_Platinum'] = { Inputs = { {Item='Uranium_Inert',Count=5} } },
    ['Uranium_Titanium'] = { Inputs = { {Item='Uranium_Inert',Count=5} } },
    ['Aluminium_Screw'] = { Inputs = { {Item='Aluminium',Count=1} } },
    ['Lithium_Bolt'] = { Inputs = { {Item='Lithium_Refined',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Aluminium_Screw',Count=4} } },
    ['Uranium_Bolt'] = { Inputs = { {Item='Uranium_Inert',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Aluminium_Screw',Count=4} } },
    ['Lithium_Arrow'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Aluminium_Screw',Count=2}, {Item='Lithium_Refined',Count=1} } },
    ['Uranium_Arrow'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Aluminium_Screw',Count=2}, {Item='Uranium_Inert',Count=1} } },
    ['Landing_Pad'] = { Inputs = { {Item='Titanium_Plate',Count=40}, {Item='Composites',Count=35}, {Item='Plastics',Count=30}, {Item='Portable_Beacon',Count=1} } },
    ['Advanced_Orbital_Exchange_Interface'] = { Inputs = { {Item='Titanium_Plate',Count=20}, {Item='Composites',Count=25}, {Item='Plastics',Count=30}, {Item='Electronics',Count=15}, {Item='Portable_Beacon',Count=1} } },
    ['Powerbank'] = { Inputs = { {Item='Electronics',Count=5}, {Item='Copper_Wire',Count=15}, {Item='Lithium_Refined',Count=10}, {Item='Refined_Metal',Count=5} } },
    ['Powerbank_2'] = { Inputs = { {Item='Electronics',Count=10}, {Item='Copper_Wire',Count=30}, {Item='Platinum_Shealth',Count=20}, {Item='Refined_Metal',Count=10} } },
    ['Battery_T3_Shelf_Lithium'] = { Inputs = { {Item='Electronics',Count=2}, {Item='Copper_Wire',Count=8}, {Item='Lithium_Refined',Count=10}, {Item='Platinum_Shealth',Count=3}, {Item='Titanium_Plate',Count=1} } },
    ['Battery_T4_Shelf_Lithium'] = { Inputs = { {Item='Electronics',Count=4}, {Item='Titanium_Plate',Count=4}, {Item='Copper_Wire',Count=9}, {Item='Lithium_Refined',Count=10}, {Item='Composites',Count=2} } },
    ['Butcher_Meat_Pig'] = { Inputs = { {Item='Pig_Head',Count=1} } },
    ['Butcher_Meat_Rooster'] = { Inputs = { {Item='Rooster_Head',Count=1} } },
    ['Butcher_Meat_Sheep'] = { Inputs = { {Item='Sheep_Head',Count=1} } },
    ['Butcher_Meat_Ram'] = { Inputs = { {Item='Ram_Head',Count=1} } },
    ['Butcher_Meat_Cow'] = { Inputs = { {Item='Cow_Head',Count=1} } },
    ['Butcher_Meat_Bull'] = { Inputs = { {Item='Bull_Head',Count=1} } },
    ['Red_Exotic_Seed'] = { Inputs = { {Item='MetaResource',Count=1}, {Item='Plant_Extract',Count=50} } },
    ['Dust_Iron'] = { Inputs = { {Item='Terraforming_Dust',Count=5} } },
    ['Dust_Copper'] = { Inputs = { {Item='Terraforming_Dust',Count=5} } },
    ['Dust_Gold'] = { Inputs = { {Item='Terraforming_Dust',Count=5} } },
    ['Blood_Thinning_Tonic_0'] = { Inputs = { {Item='Mushroom',Count=1}, {Item='Organic_Resin',Count=1}, {Item='Charcoal',Count=3} } },
    ['Alloy_Armor_Head'] = { Inputs = { {Item='Titanium_Ingot',Count=20}, {Item='Uranium_Inert',Count=10}, {Item='Glass',Count=5}, {Item='Aluminium_Screw',Count=25} } },
    ['Alloy_Armor_Chest'] = { Inputs = { {Item='Titanium_Ingot',Count=30}, {Item='Uranium_Inert',Count=30}, {Item='Aluminium_Screw',Count=50} } },
    ['Alloy_Armor_Arms'] = { Inputs = { {Item='Titanium_Ingot',Count=20}, {Item='Uranium_Inert',Count=10}, {Item='Aluminium_Screw',Count=25} } },
    ['Alloy_Armor_Legs'] = { Inputs = { {Item='Titanium_Ingot',Count=40}, {Item='Uranium_Inert',Count=25}, {Item='Aluminium_Screw',Count=35} } },
    ['Alloy_Armor_Feet'] = { Inputs = { {Item='Titanium_Ingot',Count=15}, {Item='Uranium_Inert',Count=15}, {Item='Aluminium_Screw',Count=35}, {Item='Compounds',Count=20} } },
    ['Carcass_Bounder_Desert'] = { Inputs = { {Item='AnimalCarcass_Bounder_Desert',Count=1} } },
    ['Carcass_Mange_Wolf'] = { Inputs = { {Item='AnimalCarcass_Mange_Wolf',Count=1} } },
    ['Carcass_Orka'] = { Inputs = { {Item='AnimalCarcass_Orka_Arctic',Count=1} } },
    ['Carcass_TundraMonkey'] = { Inputs = { {Item='AnimalCarcass_Tundra_Monkey',Count=1} } },
    ['Carcass_Storca'] = { Inputs = { {Item='AnimalCarcass_Storca',Count=1} } },
    ['Carcass_Chick'] = { Inputs = { {Item='AnimalCarcass_Chick',Count=1} } },
    ['Carcass_Chicken'] = { Inputs = { {Item='AnimalCarcass_Chicken',Count=1} } },
    ['Carcass_Rooster'] = { Inputs = { {Item='AnimalCarcass_Rooster',Count=1} } },
    ['Carcass_Sheep'] = { Inputs = { {Item='AnimalCarcass_Sheep',Count=1} } },
    ['Carcass_Ram'] = { Inputs = { {Item='AnimalCarcass_Ram',Count=1} } },
    ['Carcass_Lamb'] = { Inputs = { {Item='AnimalCarcass_Lamb',Count=1} } },
    ['Carcass_Pig'] = { Inputs = { {Item='AnimalCarcass_Pig',Count=1} } },
    ['Carcass_Piglet'] = { Inputs = { {Item='AnimalCarcass_Piglet',Count=1} } },
    ['Carcass_Cat_A'] = { Inputs = { {Item='AnimalCarcass_Tame_Cat_A',Count=1} } },
    ['Carcass_Cat_B'] = { Inputs = { {Item='AnimalCarcass_Tame_Cat_B',Count=1} } },
    ['Carcass_Cat_C'] = { Inputs = { {Item='AnimalCarcass_Tame_Cat_C',Count=1} } },
}
return Chunk
