-- Recipes Chunk 1
local Chunk = {
    ['Stone_Pickaxe'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4}, {Item='Stone',Count=6} } },
    ['Stone_Axe'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4}, {Item='Stone',Count=6} } },
    ['Wood_Spear'] = { Inputs = { {Item='Fiber',Count=12}, {Item='Stick',Count=18} } },
    ['Bone_Spear'] = { Inputs = { {Item='Wood',Count=16}, {Item='Leather',Count=4}, {Item='Bone',Count=40} } },
    ['Stone_Knife'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Stick',Count=2}, {Item='Stone',Count=4} } },
    ['Bone_Knife'] = { Inputs = { {Item='Wood',Count=2}, {Item='Leather',Count=2}, {Item='Bone',Count=20} } },
    ['Wood_Bow'] = { Inputs = { {Item='Fiber',Count=30}, {Item='Stick',Count=24} } },
    ['Stone_Arrow'] = { Inputs = { {Item='Fiber',Count=1}, {Item='Stick',Count=1}, {Item='Stone',Count=1} } },
    ['Bone_Arrow'] = { Inputs = { {Item='Stick',Count=1}, {Item='Leather',Count=1}, {Item='Bone',Count=5} } },
    ['Flare_Arrow'] = { Inputs = { {Item='Stone_Arrow',Count=1}, {Item='Sulfur',Count=2} } },
    ['Fire_Arrow'] = { Inputs = { {Item='Stone_Arrow',Count=1}, {Item='Gunpowder',Count=2} } },
    ['Wood_Rag_Torch'] = { Inputs = { {Item='Fiber',Count=40}, {Item='Stick',Count=8} } },
    ['Wood_Flare'] = { Inputs = { {Item='Fiber',Count=40}, {Item='Stick',Count=8}, {Item='Sulfur',Count=8} } },
    ['Campfire'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Stick',Count=8}, {Item='Stone',Count=24} } },
    ['FireWhacker'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4}, {Item='Stone',Count=2} } },
    ['Thatch_Beam'] = { Inputs = { {Item='Fiber',Count=12}, {Item='Stick',Count=6} } },
    ['Thatch_Floor'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Stick',Count=3} } },
    ['Thatch_Wall'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Stick',Count=3} } },
    ['Thatch_Halfpiece'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=2} } },
    ['Thatch_Half_Pitch'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=2} } },
    ['Thatch_Wall_Angled'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=2} } },
    ['Thatch_Ramp'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Stick',Count=3} } },
    ['Thatch_Roof_Corner'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=2} } },
    ['Thatch_Door'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4} } },
    ['Thatch_Window'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4} } },
    ['Thatch_TrapDoor'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4} } },
    ['Thatch_Railing'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Stick',Count=2} } },
    ['Thatch_Ladder'] = { Inputs = { {Item='Fiber',Count=6}, {Item='Stick',Count=10} } },
    ['Basic_Oxite_Dissolver'] = { Inputs = { {Item='Stick',Count=8}, {Item='Fiber',Count=24}, {Item='Leather',Count=20}, {Item='Bone',Count=10} } },
    ['Crafting_Bench'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Wood',Count=50}, {Item='Stone',Count=12}, {Item='Leather',Count=20} } },
    ['Building_RepairHammer'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Stick',Count=4}, {Item='Stone',Count=6} } },
    ['Wood_Beam'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=6} } },
    ['Wood_Floor'] = { Inputs = { {Item='Fiber',Count=12}, {Item='Wood',Count=20} } },
    ['Wood_Wall'] = { Inputs = { {Item='Fiber',Count=12}, {Item='Wood',Count=20} } },
    ['Wood_Halfpiece'] = { Inputs = { {Item='Fiber',Count=6}, {Item='Wood',Count=10} } },
    ['Wood_Half_Pitch'] = { Inputs = { {Item='Fiber',Count=6}, {Item='Wood',Count=10} } },
    ['Wood_Wall_Angled'] = { Inputs = { {Item='Fiber',Count=6}, {Item='Wood',Count=10} } },
    ['Wood_Ramp'] = { Inputs = { {Item='Fiber',Count=12}, {Item='Wood',Count=20} } },
    ['Wood_Roof_Corner'] = { Inputs = { {Item='Fiber',Count=6}, {Item='Wood',Count=10} } },
    ['Wood_Railing'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Wood',Count=8} } },
    ['Wood_Door'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Wood',Count=10} } },
    ['Wood_Window'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Wood',Count=10} } },
    ['Wood_TrapDoor'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=10} } },
    ['Wood_Ladder'] = { Inputs = { {Item='Fiber',Count=6}, {Item='Wood',Count=10} } },
    ['Bed_Bedroll'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Stick',Count=10}, {Item='Fur',Count=20}, {Item='Leather',Count=10} } },
    ['Cloth_Head_Armor'] = { Inputs = { {Item='Fiber',Count=80} } },
    ['Cloth_Chest_Armor'] = { Inputs = { {Item='Fiber',Count=120} } },
    ['Cloth_Arms_Armor'] = { Inputs = { {Item='Fiber',Count=80} } },
    ['Cloth_Legs_Armor'] = { Inputs = { {Item='Fiber',Count=120} } },
    ['Cloth_Feet_Armor'] = { Inputs = { {Item='Fiber',Count=40} } },
    ['Wood_Crate_Small'] = { Inputs = { {Item='Fiber',Count=16}, {Item='Wood',Count=24} } },
    ['Wood_Crate_Medium'] = { Inputs = { {Item='Fiber',Count=32}, {Item='Wood',Count=32} } },
    ['ResourceStack_Wood'] = { Inputs = { {Item='Wood',Count=100} } },
    ['ResourceStack_Stone'] = { Inputs = { {Item='Stone',Count=100} } },
    ['Metal_Axe'] = { Inputs = { {Item='Wood',Count=5}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Metal_Pickaxe'] = { Inputs = { {Item='Wood',Count=5}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=6} } },
    ['Metal_Spear'] = { Inputs = { {Item='Wood',Count=5}, {Item='Leather',Count=6}, {Item='Refined_Metal',Count=24} } },
    ['Steel_Spear'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=6}, {Item='Steel_Ingot',Count=24} } },
    ['Metal_Knife'] = { Inputs = { {Item='Wood',Count=5}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Sickle'] = { Inputs = { {Item='Wood',Count=4}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=10} } },
    ['Metal_Shovel'] = { Inputs = { {Item='Wood',Count=4}, {Item='Refined_Metal',Count=6} } },
    ['Stone_Shovel'] = { Inputs = { {Item='Wood',Count=15}, {Item='Stick',Count=10}, {Item='Fiber',Count=15} } },
    ['Longbow'] = { Inputs = { {Item='Wood',Count=24}, {Item='Leather',Count=32}, {Item='Bone',Count=4} } },
    ['Flint_Arrow'] = { Inputs = { {Item='Leather',Count=1}, {Item='Stick',Count=5}, {Item='Metal_Ore',Count=1} } },
    ['Steel_Arrow'] = { Inputs = { {Item='Epoxy',Count=1}, {Item='Stick',Count=5}, {Item='Steel_Ingot',Count=1} } },
    ['Lantern'] = { Inputs = { {Item='Refined_Metal',Count=8}, {Item='Rope',Count=4}, {Item='Epoxy',Count=12}, {Item='Animal_Fat',Count=5} } },
    ['Canteen'] = { Inputs = { {Item='Advanced_Leather',Count=1}, {Item='Steel_Ingot',Count=8} } },
    ['Crossbow'] = { Inputs = { {Item='Wood',Count=18}, {Item='Leather',Count=12}, {Item='Refined_Metal',Count=12}, {Item='Iron_Nail',Count=2} } },
    ['Metal_Bolt'] = { Inputs = { {Item='Wood',Count=1}, {Item='Refined_Metal',Count=2} } },
    ['Copper_Bolt'] = { Inputs = { {Item='Wood',Count=1}, {Item='Refined_Copper',Count=1} } },
    ['Steel_Bolt'] = { Inputs = { {Item='Wood',Count=1}, {Item='Steel_Ingot',Count=1} } },
    ['Waterskin'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Leather',Count=12}, {Item='Bone',Count=4} } },
    ['Oxygen_Bladder'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Leather',Count=30}, {Item='Bone',Count=8} } },
    ['Rope'] = { Inputs = { {Item='Fiber',Count=12} } },
    ['Mortar_And_Pestle'] = { Inputs = { {Item='Silica',Count=4}, {Item='Stone',Count=12} } },
    ['Machining_Bench'] = { Inputs = { {Item='Wood',Count=20}, {Item='Stone',Count=12}, {Item='Iron_Nail',Count=120}, {Item='Refined_Metal',Count=40}, {Item='Epoxy',Count=10}, {Item='Rope',Count=24} } },
    ['Skinning_Bench'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Wood',Count=50}, {Item='Stone',Count=12}, {Item='Leather',Count=20} } },
    ['Carpentry_Bench'] = { Inputs = { {Item='Wood',Count=80}, {Item='Rope',Count=12}, {Item='Copper_Nail',Count=120} } },
    ['Cooking_Station'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Stick',Count=8}, {Item='Stone',Count=24}, {Item='Refined_Metal',Count=4} } },
    ['Stone_Furnace'] = { Inputs = { {Item='Stick',Count=4}, {Item='Wood',Count=12}, {Item='Stone',Count=80}, {Item='Leather',Count=12} } },
    ['Oxite_Dissolver'] = { Inputs = { {Item='Wood',Count=18}, {Item='Leather',Count=24}, {Item='Bone',Count=8} } },
    ['Wood_Cupboard'] = { Inputs = { {Item='Wood',Count=40}, {Item='Leather',Count=8}, {Item='Copper_Nail',Count=4}, {Item='Rope',Count=8} } },
    ['Wood_Cupboard_Small'] = { Inputs = { {Item='Wood',Count=25}, {Item='Leather',Count=5}, {Item='Copper_Nail',Count=4}, {Item='Rope',Count=5} } },
    ['Stone_Frame'] = { Inputs = { {Item='Wood',Count=12}, {Item='Stone',Count=40}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=12} } },
    ['Stone_Beam'] = { Inputs = { {Item='Wood',Count=2}, {Item='Stone',Count=6}, {Item='Leather',Count=1}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Floor'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Wall'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Halfpiece'] = { Inputs = { {Item='Wood',Count=3}, {Item='Stone',Count=10}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Stone_Half_Pitch'] = { Inputs = { {Item='Wood',Count=3}, {Item='Stone',Count=10}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Stone_Wall_Angled'] = { Inputs = { {Item='Wood',Count=3}, {Item='Stone',Count=10}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=4} } },
    ['Stone_Ramp'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Roof_Corner'] = { Inputs = { {Item='Wood',Count=3}, {Item='Stone',Count=10}, {Item='Leather',Count=2}, {Item='Iron_Nail',Count=3} } },
    ['Reinforced_Door'] = { Inputs = { {Item='Wood',Count=4}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=8}, {Item='Rope',Count=4} } },
    ['Reinforced_Window'] = { Inputs = { {Item='Wood',Count=4}, {Item='Refined_Metal',Count=2}, {Item='Iron_Nail',Count=8}, {Item='Rope',Count=4} } },
    ['Reinforced_TrapDoor'] = { Inputs = { {Item='Wood',Count=4}, {Item='Refined_Metal',Count=2}, {Item='Iron_Nail',Count=4}, {Item='Rope',Count=4} } },
    ['Reinforced_Ladder'] = { Inputs = { {Item='Wood',Count=10}, {Item='Refined_Metal',Count=8}, {Item='Iron_Nail',Count=8} } },
    ['Floor_Torch'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Stick',Count=8}, {Item='Sulfur',Count=8} } },
    ['Wall_Torch'] = { Inputs = { {Item='Wood',Count=4}, {Item='Leather',Count=8}, {Item='Sulfur',Count=8}, {Item='Refined_Metal',Count=8} } },
    ['Rain_Reservoir'] = { Inputs = { {Item='Stick',Count=8}, {Item='Wood',Count=24}, {Item='Stone',Count=60}, {Item='Leather',Count=8} } },
    ['Leather_Head_Armor'] = { Inputs = { {Item='Fiber',Count=40}, {Item='Leather',Count=12} } },
    ['Leather_Chest_Armor'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Leather',Count=24} } },
    ['Leather_Arms_Armor'] = { Inputs = { {Item='Fiber',Count=40}, {Item='Leather',Count=8} } },
    ['Leather_Legs_Armor'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Leather',Count=18} } },
    ['Leather_Feet_Armor'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Leather',Count=12} } },
    ['Fur_Head_Armor'] = { Inputs = { {Item='Leather',Count=4}, {Item='Fur',Count=12}, {Item='Rope',Count=2} } },
    ['Fur_Chest_Armor'] = { Inputs = { {Item='Leather',Count=8}, {Item='Fur',Count=24}, {Item='Rope',Count=4} } },
    ['Fur_Arms_Armor'] = { Inputs = { {Item='Leather',Count=4}, {Item='Fur',Count=8}, {Item='Rope',Count=1} } },
    ['Fur_Legs_Armor'] = { Inputs = { {Item='Leather',Count=8}, {Item='Fur',Count=18}, {Item='Rope',Count=3} } },
    ['Fur_Feet_Armor'] = { Inputs = { {Item='Leather',Count=6}, {Item='Fur',Count=12}, {Item='Rope',Count=2} } },
    ['Farming_CropPlot'] = { Inputs = { {Item='Wood',Count=8}, {Item='Sulfur',Count=10}, {Item='Dirt',Count=20} } },
    ['Cooked_Meat'] = { Inputs = { {Item='Raw_Meat',Count=1} } },
    ['Refined_Metal'] = { Inputs = { {Item='Metal_Ore',Count=2} } },
    ['Refined_Copper'] = { Inputs = { {Item='Copper_Ore',Count=2} } },
    ['Refined_Gold'] = { Inputs = { {Item='Gold_Ore',Count=2} } },
    ['Glass'] = { Inputs = { {Item='Silica',Count=1} } },
    ['Carbon_Fiber'] = { Inputs = { {Item='Carbon_Paste',Count=1} } },
    ['Aluminum'] = { Inputs = { {Item='Bauxite',Count=1} } },
    ['Epoxy'] = { Inputs = { {Item='Sulfur',Count=2}, {Item='Tree_Sap',Count=4} } },
    ['Gunpowder'] = { Inputs = { {Item='Sulfur',Count=1}, {Item='Charcoal',Count=3} } },
    ['Carbon_Paste'] = { Inputs = { {Item='Silica',Count=1}, {Item='Aluminium',Count=1}, {Item='Organic_Resin',Count=4}, {Item='Epoxy',Count=2} } },
    ['Electronics'] = { Inputs = { {Item='Gold_Wire',Count=5}, {Item='Copper_Wire',Count=15}, {Item='Organic_Resin',Count=2}, {Item='Epoxy',Count=2} } },
    ['Oxygen_Tank'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Epoxy',Count=4} } },
    ['Combat_Knife'] = { Inputs = { {Item='Steel_Ingot',Count=12}, {Item='Steel_Screw',Count=2}, {Item='Carbon_Fiber',Count=2}, {Item='Epoxy',Count=4} } },
    ['Machete'] = { Inputs = { {Item='Refined_Metal',Count=12}, {Item='Wood_Refined',Count=4}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=2} } },
    ['Fabricator'] = { Inputs = { {Item='Aluminium',Count=40}, {Item='Electronics',Count=30}, {Item='Concrete_Mix',Count=30}, {Item='Carbon_Fiber',Count=8}, {Item='Steel_Screw',Count=30} } },
    ['Composter'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Refined_Copper',Count=8}, {Item='Concrete_Mix',Count=12}, {Item='Steel_Screw',Count=20} } },
    ['Aluminium_Arrow'] = { Inputs = { {Item='Refined_Copper',Count=1}, {Item='Aluminium',Count=1}, {Item='Epoxy',Count=1} } },
    ['Carbon_Arrow'] = { Inputs = { {Item='Refined_Copper',Count=1}, {Item='Carbon_Fiber',Count=1}, {Item='Epoxy',Count=1} } },
    ['Concrete_Furnace'] = { Inputs = { {Item='Refined_Metal',Count=12}, {Item='Rope',Count=8}, {Item='Epoxy',Count=12}, {Item='Concrete_Mix',Count=20} } },
    ['Electric_Furnace'] = { Inputs = { {Item='Steel_Ingot',Count=30}, {Item='Glass',Count=4}, {Item='Electronics',Count=60}, {Item='Concrete_Mix',Count=80}, {Item='Steel_Screw',Count=8} } },
    ['Binoculars'] = { Inputs = { {Item='Rope',Count=4}, {Item='Glass',Count=6}, {Item='Aluminium',Count=6}, {Item='Epoxy',Count=2} } },
    ['Carbon_Spear'] = { Inputs = { {Item='Refined_Copper',Count=4}, {Item='Carbon_Fiber',Count=24}, {Item='Epoxy',Count=8} } },
    ['Platinum_Spear'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=24} } },
    ['Titanium_Spear'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=24} } },
    ['Concrete_Frame'] = { Inputs = { {Item='Steel_Rebar',Count=20}, {Item='Concrete_Mix',Count=8}, {Item='Steel_Screw',Count=10} } },
    ['Concrete_Beam'] = { Inputs = { {Item='Steel_Rebar',Count=8}, {Item='Concrete_Mix',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Concrete_Floor'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Wall'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Halfpiece'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Concrete_Mix',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Concrete_Half_Pitch'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Concrete_Mix',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Concrete_Wall_Angled'] = { Inputs = { {Item='Steel_Rebar',Count=5}, {Item='Concrete_Mix',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Concrete_Ramp'] = { Inputs = { {Item='Steel_Rebar',Count=12}, {Item='Concrete_Mix',Count=4}, {Item='Steel_Screw',Count=4} } },
    ['Concrete_Roof_Corner'] = { Inputs = { {Item='Steel_Rebar',Count=6}, {Item='Steel_Ingot',Count=1}, {Item='Steel_Screw',Count=2} } },
    ['Concrete_Window'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Glass',Count=8}, {Item='Epoxy',Count=4} } },
    ['Concrete_TrapDoor'] = { Inputs = { {Item='Refined_Metal',Count=12}, {Item='Steel_Screw',Count=4}, {Item='Epoxy',Count=4} } },
    ['Recurve_Bow'] = { Inputs = { {Item='Steel_Ingot',Count=8}, {Item='Rope',Count=8}, {Item='Aluminium',Count=18}, {Item='Epoxy',Count=8}, {Item='Steel_Screw',Count=4} } },
    ['Metal_Cupboard'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Rope',Count=4}, {Item='Epoxy',Count=12} } },
    ['Metal_Cupboard_Small'] = { Inputs = { {Item='Refined_Metal',Count=25}, {Item='Rope',Count=4}, {Item='Epoxy',Count=8} } },
    ['Biofuel1'] = { Inputs = { {Item='Raw_Meat',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel5'] = { Inputs = { {Item='Cooked_Meat',Count=1}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel2'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel3'] = { Inputs = { {Item='Stick',Count=5}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel4'] = { Inputs = { {Item='Wood',Count=1}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel6'] = { Inputs = { {Item='Spoiled_Meat',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel7'] = { Inputs = { {Item='Spoiled_Plants',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel8'] = { Inputs = { {Item='Wheat',Count=10}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel_9'] = { Inputs = { {Item='Guano',Count=2}, {Item='Tree_Sap',Count=1} } },
    ['Biofuel_10'] = { Inputs = { {Item='Fur',Count=30}, {Item='Tree_Sap',Count=1} } },
    ['Concrete_Mix'] = { Inputs = { {Item='Tree_Sap',Count=1}, {Item='Stone',Count=8}, {Item='Silica',Count=4} } },
    ['Composites'] = { Inputs = { {Item='Composite_Paste',Count=1} } },
    ['Organic_Resin'] = { Inputs = { {Item='Wood',Count=1}, {Item='Oxite',Count=1} } },
    ['Tree_Sap'] = { Inputs = { {Item='Stick',Count=4} } },
    ['Composite_Paste'] = { Inputs = { {Item='Metal_Ore',Count=2}, {Item='Silica',Count=1}, {Item='Organic_Resin',Count=1}, {Item='Gold_Ore',Count=1} } },
    ['Composite_Paste_Plat'] = { Inputs = { {Item='Metal_Ore',Count=2}, {Item='Silica',Count=1}, {Item='Organic_Resin',Count=1}, {Item='Platinum_Ore',Count=1} } },
    ['Flashlight'] = { Inputs = { {Item='Glass',Count=4}, {Item='Aluminium',Count=4}, {Item='Epoxy',Count=4}, {Item='Electronics',Count=2} } },
    ['Composite_Arrow'] = { Inputs = { {Item='Composites',Count=1}, {Item='Steel_Screw',Count=2} } },
    ['Extractor_Electric'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Electronics',Count=5} } },
    ['Radar'] = { Inputs = { {Item='Steel_Ingot',Count=12}, {Item='Electronics',Count=10}, {Item='Steel_Screw',Count=8}, {Item='Glass',Count=2}, {Item='Composites',Count=12} } },
    ['Carcass_Deer'] = { Inputs = { {Item='AnimalCarcass_Deer',Count=1} } },
    ['Carcass_Chamois_M'] = { Inputs = { {Item='AnimalCarcass_Chamois_M',Count=1} } },
    ['Material_Processor'] = { Inputs = { {Item='Aluminium',Count=30}, {Item='Electronics',Count=60}, {Item='Steel_Screw',Count=12}, {Item='Titanium_Plate',Count=3}, {Item='Carbon_Fiber',Count=8} } },
    ['Stick'] = { Inputs = { {Item='Wood',Count=1} } },
    ['Refined_Wood'] = { Inputs = { {Item='Wood',Count=1} } },
    ['Wood_Floor_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15} } },
    ['Wood_Wall_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15} } },
    ['Wood_Wall_Angled_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=2}, {Item='Wood',Count=8} } },
    ['Wood_Ramp_CarpentryBench'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=15} } },
    ['Interior_Wood_Floor'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=4} } },
    ['Interior_Wood_Wall'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=4} } },
    ['Interior_Wood_Halfpiece'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=2} } },
    ['Interior_Wood_Half_Pitch'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=2} } },
    ['Interior_Wood_Wall_Angled'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=2} } },
    ['Interior_Wood_Ramp'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=4} } },
    ['Interior_Wood_Railing'] = { Inputs = { {Item='Wood_Refined',Count=8}, {Item='Copper_Nail',Count=4} } },
    ['Interior_Wood_Door'] = { Inputs = { {Item='Rope',Count=8}, {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=6} } },
    ['Interior_Wood_TrapDoor'] = { Inputs = { {Item='Rope',Count=4}, {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=2} } },
    ['Wood_Sign_Small'] = { Inputs = { {Item='Wood_Refined',Count=12}, {Item='Rope',Count=2}, {Item='Copper_Nail',Count=2} } },
    ['Bed_Wood'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Fur',Count=30}, {Item='Leather',Count=10}, {Item='Copper_Nail',Count=10} } },
    ['Wood_Table'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=10} } },
    ['Wood_Hedgehog_Medium'] = { Inputs = { {Item='Wood',Count=60}, {Item='Rope',Count=4} } },
    ['Scorpion_Hedgehog_Medium'] = { Inputs = { {Item='Wood_Hedgehog_Medium',Count=1}, {Item='Scorpion_Tail',Count=1} } },
    ['Scorpion_Trap_Medium'] = { Inputs = { {Item='Stone',Count=4}, {Item='Stick',Count=4}, {Item='Scorpion_Pincer',Count=1} } },
    ['Frag_Grenade'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Gunpowder',Count=2}, {Item='Volatile_Substance',Count=3} } },
    ['Frag_Grenade_Impact'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Gunpowder',Count=2}, {Item='Volatile_Substance',Count=3} } },
    ['Smoke_Grenade'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Stone',Count=10} } },
    ['Shotgun'] = { Inputs = { {Item='Wood_Refined',Count=12}, {Item='Advanced_Leather',Count=1}, {Item='Steel_Ingot',Count=26}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=10} } },
    ['Shotgun_Shell_Buckshot'] = { Inputs = { {Item='Shotgun_Casing',Count=1}, {Item='Copper_Nail',Count=2}, {Item='Gunpowder',Count=1}, {Item='Epoxy',Count=1} } },
    ['Shotgun_Shell_Explosive'] = { Inputs = { {Item='Ammo_Shell_Buckshot',Count=5}, {Item='Volatile_Substance',Count=1} } },
    ['Fireplace'] = { Inputs = { {Item='Stone',Count=120}, {Item='Wood',Count=30} } },
    ['Fireplace_Chimney_Ext'] = { Inputs = { {Item='Stone',Count=40}, {Item='Wood',Count=20} } },
    ['Fireplace_Chimney_Cap'] = { Inputs = { {Item='Stone',Count=40}, {Item='Wood',Count=20} } },
    ['Fireplace_Chimney_Cap_Half'] = { Inputs = { {Item='Stone',Count=30}, {Item='Wood',Count=15} } },
    ['Composite_Spear'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Aluminium',Count=4}, {Item='Composites',Count=24} } },
    ['Compound_Bow'] = { Inputs = { {Item='Aluminium',Count=16}, {Item='Carbon_Fiber',Count=8}, {Item='Composites',Count=18}, {Item='Steel_Screw',Count=4} } },
    ['Hunting_Rifle'] = { Inputs = { {Item='Wood_Refined',Count=12}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=40}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=16} } },
    ['Rifle_Round'] = { Inputs = { {Item='Ammo_Casing',Count=1}, {Item='Gunpowder',Count=2} } },
    ['Flour'] = { Inputs = { {Item='Wheat',Count=10} } },
    ['Dough_Bread'] = { Inputs = { {Item='Flour',Count=3}, {Item='Yeast',Count=1} } },
    ['Dough_Flatbread'] = { Inputs = { {Item='Flour',Count=3} } },
    ['Fire_Extinguisher'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Refined_Copper',Count=4}, {Item='Sulfur',Count=8}, {Item='Epoxy',Count=4}, {Item='Oxite',Count=8} } },
    ['Fill_Oxygen_Container'] = { Inputs = { {Item='Oxite',Count=1} } },
    ['Ghillie_Head_Armor'] = { Inputs = { {Item='Fiber',Count=120}, {Item='Stick',Count=2}, {Item='Rope',Count=2} } },
    ['Ghillie_Chest_Armor'] = { Inputs = { {Item='Fiber',Count=160}, {Item='Stick',Count=8}, {Item='Rope',Count=4} } },
    ['Ghillie_Arms_Armor'] = { Inputs = { {Item='Fiber',Count=120}, {Item='Stick',Count=4}, {Item='Rope',Count=1} } },
    ['Ghillie_Legs_Armor'] = { Inputs = { {Item='Fiber',Count=160}, {Item='Stick',Count=8}, {Item='Rope',Count=3} } },
    ['Ghillie_Feet_Armor'] = { Inputs = { {Item='Fiber',Count=80}, {Item='Stick',Count=6}, {Item='Rope',Count=2} } },
    ['Beer'] = { Inputs = { {Item='Wheat',Count=20}, {Item='Yeast',Count=1}, {Item='Glass_Bottle',Count=1} } },
    ['Wine'] = { Inputs = { {Item='Berry',Count=10}, {Item='Reed_Flower',Count=1}, {Item='Glass_Bottle',Count=1} } },
    ['Glass_Jar'] = { Inputs = { {Item='Glass',Count=1}, {Item='Refined_Metal',Count=1} } },
    ['Glass_Bottle'] = { Inputs = { {Item='Glass',Count=5} } },
    ['Flatbread'] = { Inputs = { {Item='Dough_Flatbread',Count=1} } },
    ['Bread'] = { Inputs = { {Item='Dough_Bread',Count=1} } },
    ['Thermos'] = { Inputs = { {Item='Epoxy',Count=8}, {Item='Glass',Count=4}, {Item='Steel_Ingot',Count=12} } },
    ['Jerrycan'] = { Inputs = { {Item='Refined_Metal',Count=25} } },
    ['Biofuel_Lamp'] = { Inputs = { {Item='Rope',Count=4}, {Item='Glass',Count=12}, {Item='Aluminium',Count=8}, {Item='Epoxy',Count=4} } },
    ['Carcass_BabyDeer'] = { Inputs = { {Item='AnimalCarcass_BabyDeer',Count=1} } },
    ['Ice'] = { Inputs = { {Item='Ice',Count=1} } },
    ['Brazier'] = { Inputs = { {Item='Refined_Metal',Count=20}, {Item='Refined_Copper',Count=4} } },
    ['PotBellyStove'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Refined_Copper',Count=6}, {Item='Epoxy',Count=10} } },
    ['Carcass_Snow_Wolf'] = { Inputs = { {Item='AnimalCarcass_Snow_Wolf',Count=1} } },
    ['Composite_Head_Armor'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Composites',Count=12}, {Item='Steel_Screw',Count=6}, {Item='Carbon_Fiber',Count=2} } },
    ['Composite_Chest_Armor'] = { Inputs = { {Item='Aluminium',Count=6}, {Item='Composites',Count=24}, {Item='Steel_Screw',Count=12}, {Item='Carbon_Fiber',Count=2} } },
    ['Composite_Arm_Armor'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Composites',Count=8}, {Item='Steel_Screw',Count=6}, {Item='Carbon_Fiber',Count=2} } },
    ['Composite_Leg_Armor'] = { Inputs = { {Item='Aluminium',Count=6}, {Item='Composites',Count=18}, {Item='Steel_Screw',Count=8}, {Item='Carbon_Fiber',Count=2} } },
    ['Composite_Feet_Armor'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Composites',Count=12}, {Item='Steel_Screw',Count=6}, {Item='Carbon_Fiber',Count=2} } },
    ['Fill_Oxygen_Container_Metal'] = { Inputs = { {Item='Oxite',Count=1} } },
    ['Metal_Oxite_Dissolver'] = { Inputs = { {Item='Steel_Ingot',Count=15}, {Item='Glass',Count=4}, {Item='Epoxy',Count=12}, {Item='Electronics',Count=20}, {Item='Copper_Wire',Count=50} } },
    ['Carcass_Lion_F'] = { Inputs = { {Item='AnimalCarcass_Lion_F',Count=1} } },
    ['Bandage_Basic'] = { Inputs = { {Item='Fiber',Count=40} } },
    ['Titanium_Ingot'] = { Inputs = { {Item='Titanium_Ore',Count=5} } },
    ['Platinum_Ingot'] = { Inputs = { {Item='Platinum_Ore',Count=5} } },
    ['Interior_Wood_Beam'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Copper_Nail',Count=4} } },
    ['Interior_Wood_Ladder'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Copper_Nail',Count=6} } },
    ['Armor_Bench'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Stick',Count=20}, {Item='Wood',Count=50}, {Item='Stone',Count=12} } },
    ['Masonry_Bench'] = { Inputs = { {Item='Wood',Count=80}, {Item='Leather',Count=12}, {Item='Iron_Nail',Count=120}, {Item='Rope',Count=12} } },
    ['Cement_Mixer'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Stone',Count=40}, {Item='Refined_Metal',Count=20}, {Item='Rope',Count=8}, {Item='Iron_Nail',Count=8} } },
    ['Interior_Wood_Crate_Small'] = { Inputs = { {Item='Rope',Count=4}, {Item='Wood_Refined',Count=24}, {Item='Copper_Nail',Count=5} } },
    ['Interior_Wood_Crate_Medium'] = { Inputs = { {Item='Rope',Count=8}, {Item='Wood_Refined',Count=32}, {Item='Copper_Nail',Count=10} } },
    ['Metal_Crate_Small'] = { Inputs = { {Item='Epoxy',Count=4}, {Item='Refined_Metal',Count=24} } },
    ['Metal_Crate_Medium'] = { Inputs = { {Item='Epoxy',Count=8}, {Item='Refined_Metal',Count=32} } },
    ['Interior_Wood_Cupboard'] = { Inputs = { {Item='Leather',Count=8}, {Item='Wood_Refined',Count=40}, {Item='Copper_Nail',Count=20}, {Item='Rope',Count=8} } },
    ['Interior_Wood_Cupboard_Small'] = { Inputs = { {Item='Leather',Count=5}, {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=12}, {Item='Rope',Count=5} } },
    ['Charcoal'] = { Inputs = { {Item='Spoiled_Meat',Count=1} } },
    ['Herbalism_Bench'] = { Inputs = { {Item='Fiber',Count=60}, {Item='Stick',Count=20}, {Item='Wood',Count=50}, {Item='Stone',Count=12} } },
    ['Titanium_Pickaxe'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=12} } },
    ['Titanium_Axe'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=12} } },
    ['Trophy_Bench'] = { Inputs = { {Item='Wood',Count=60}, {Item='Copper_Nail',Count=50}, {Item='Refined_Metal',Count=2}, {Item='Rope',Count=12} } },
    ['Deer_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Deer_Head',Count=1} } },
    ['Bear_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Bear_Head',Count=1} } },
    ['PolarBear_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='PolarBear_Head',Count=1} } },
    ['Cougar_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Cougar_Head',Count=1} } },
    ['Jaguar_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Jaguar_Head',Count=1} } },
    ['Jaguar_Black_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Jaguar_Black_Head',Count=1} } },
    ['Iron_Beam'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Floor'] = { Inputs = { {Item='Bauxite',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Wall'] = { Inputs = { {Item='Bauxite',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Halfpiece'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Half_Pitch'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Wall_Angled'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Ramp'] = { Inputs = { {Item='Bauxite',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Roof_Corner'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Door'] = { Inputs = { {Item='Bauxite',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_TrapDoor'] = { Inputs = { {Item='Bauxite',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Window'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Ladder'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Refrigerator'] = { Inputs = { {Item='Aluminium',Count=40}, {Item='Electronics',Count=20}, {Item='Carbon_Fiber',Count=8}, {Item='Steel_Screw',Count=12} } },
    ['Taxidermy_Knife'] = { Inputs = { {Item='Wood',Count=2}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['IceBox'] = { Inputs = { {Item='Wood',Count=40}, {Item='Leather',Count=24}, {Item='Rope',Count=8}, {Item='Refined_Metal',Count=8}, {Item='Copper_Nail',Count=4} } },
    ['Glass_Wall'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Glass',Count=20}, {Item='Epoxy',Count=6} } },
    ['Glass_Halfpiece'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Half_Pitch'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Wall_Angled'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Ramp'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Glass',Count=20}, {Item='Epoxy',Count=6} } },
    ['Glass_Roof_Corner'] = { Inputs = { {Item='Refined_Metal',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Beam'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Epoxy',Count=6} } },
    ['Glass_Door'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Glass',Count=10}, {Item='Epoxy',Count=6} } },
    ['Glass_Window'] = { Inputs = { {Item='Wood',Count=12}, {Item='Glass',Count=8}, {Item='Epoxy',Count=4} } },
    ['Titanium_Knife'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=2}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=8} } },
    ['Titanium_Arrow'] = { Inputs = { {Item='Carbon_Fiber',Count=1}, {Item='Steel_Screw',Count=2}, {Item='Titanium_Ingot',Count=1} } },
    ['Titanium_Sickle'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=2}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=10} } },
    ['Repair_Bench'] = { Inputs = { {Item='Aluminium',Count=20}, {Item='Advanced_Leather',Count=20}, {Item='Wood_Refined',Count=50}, {Item='Stone',Count=12} } },
    ['Carcass_Deer_Desert'] = { Inputs = { {Item='AnimalCarcass_DeerDesert',Count=1} } },
    ['WaterBomb'] = { Inputs = { {Item='Leather',Count=5}, {Item='Fiber',Count=15} } },
    ['Bandage_Heat'] = { Inputs = { {Item='Fiber',Count=40}, {Item='Oxite',Count=4}, {Item='Charcoal',Count=10} } },
    ['Poison_Arrow'] = { Inputs = { {Item='Stone_Arrow',Count=1}, {Item='Poison_Paste',Count=2} } },
    ['Poison_Paste'] = { Inputs = { {Item='Spoiled_Meat',Count=2}, {Item='Sulfur',Count=1} } },
    ['Steel_Bloom'] = { Inputs = { {Item='Metal_Ore',Count=6}, {Item='Coal_Ore',Count=1} } },
    ['Steel_Bloom2'] = { Inputs = { {Item='Refined_Metal',Count=3}, {Item='Coal_Ore',Count=1} } },
    ['Steel_Bloom3'] = { Inputs = { {Item='Metal_Ore',Count=6}, {Item='Charcoal',Count=20} } },
    ['Steel_Bloom4'] = { Inputs = { {Item='Refined_Metal',Count=3}, {Item='Charcoal',Count=20} } },
    ['Steel_Ingot'] = { Inputs = { {Item='Steel_Bloom',Count=1} } },
    ['Steel_Axe'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=4}, {Item='Steel_Ingot',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Steel_Pickaxe'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=4}, {Item='Steel_Ingot',Count=6} } },
    ['Steel_Knife'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=4}, {Item='Steel_Ingot',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Suture_Kit'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Bone',Count=5}, {Item='Leather',Count=2} } },
    ['Antipoison_Paste'] = { Inputs = { {Item='Fiber',Count=1}, {Item='Spoiled_Meat',Count=2}, {Item='Charcoal',Count=1} } },
    ['Antibiotic_Paste'] = { Inputs = { {Item='Yeast',Count=1}, {Item='Silica',Count=1}, {Item='Charcoal',Count=1} } },
    ['Antiparasitic_Paste'] = { Inputs = { {Item='Reed_Flower',Count=1}, {Item='Sulfur',Count=1}, {Item='Charcoal',Count=1} } },
    ['Blood_Thinner_Paste'] = { Inputs = { {Item='Lily',Count=1}, {Item='Stick',Count=10}, {Item='Charcoal',Count=1} } },
    ['Anvil_Bench'] = { Inputs = { {Item='Refined_Metal',Count=40}, {Item='Wood',Count=20}, {Item='Stone',Count=10} } },
    ['Wood_Chair'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Copper_Nail',Count=5} } },
    ['Firepit'] = { Inputs = { {Item='Stone',Count=100}, {Item='Wood',Count=25} } },
    ['Dehumidifier'] = { Inputs = { {Item='Steel_Ingot',Count=15}, {Item='Glass',Count=4}, {Item='Epoxy',Count=12}, {Item='Electronics',Count=20}, {Item='Copper_Wire',Count=50} } },
    ['Portable_Beacon'] = { Inputs = { {Item='Gold_Wire',Count=30}, {Item='Copper_Wire',Count=25}, {Item='Steel_Ingot',Count=10}, {Item='Platinum_Shealth',Count=20}, {Item='Glass',Count=10} } },
    ['Stick_Talent'] = { Inputs = { {Item='Wood',Count=1} } },
    ['Epoxy_2'] = { Inputs = { {Item='Crushed_Bone',Count=4} } },
    ['Crushed_Bone'] = { Inputs = { {Item='Bone',Count=2} } },
    ['Glassworking_Bench'] = { Inputs = { {Item='Refined_Metal',Count=24}, {Item='Wood_Refined',Count=10}, {Item='Epoxy',Count=6}, {Item='Rope',Count=6}, {Item='Copper_Nail',Count=40} } },
    ['Kitchen_Bench'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=8}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=20} } },
    ['Kitchen_Stove'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=4}, {Item='Steel_Ingot',Count=24}, {Item='Steel_Screw',Count=8} } },
    ['Kitchen_Storage'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=2}, {Item='Epoxy',Count=20}, {Item='Copper_Nail',Count=12} } },
    ['Carcass_Conifer_Wolf'] = { Inputs = { {Item='AnimalCarcass_Conifer_Wolf',Count=1} } },
    ['Carcass_Pack_Wolf'] = { Inputs = { {Item='AnimalCarcass_Pack_Wolf',Count=1} } },
    ['Carcass_Jaguar'] = { Inputs = { {Item='AnimalCarcass_Jaguar',Count=1} } },
    ['Carcass_SnowLeopord'] = { Inputs = { {Item='AnimalCarcass_SnowLeopard',Count=1} } },
    ['Carcass_Desert_Wolf'] = { Inputs = { {Item='AnimalCarcass_Desert_Wolf',Count=1} } },
    ['Bone_Sickle'] = { Inputs = { {Item='Wood',Count=2}, {Item='Leather',Count=2}, {Item='Bone',Count=20} } },
    ['Glass_Jar_Jam'] = { Inputs = { {Item='Glass_Jar',Count=1}, {Item='Berry',Count=5} } },
    ['Leather_Curtain_Door'] = { Inputs = { {Item='Fiber',Count=20}, {Item='Wood',Count=5}, {Item='Leather',Count=15} } },
    ['Polarbear_Head_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=3}, {Item='Fur',Count=10}, {Item='Rope',Count=4}, {Item='PolarBear_Head',Count=1} } },
    ['Polarbear_Chest_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=5}, {Item='Polarbear_Pelt',Count=8}, {Item='Fur',Count=20}, {Item='Rope',Count=6} } },
    ['Polarbear_Arm_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=3}, {Item='Polarbear_Pelt',Count=4}, {Item='Fur',Count=8}, {Item='Rope',Count=2} } },
    ['Polarbear_Leg_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=4}, {Item='Polarbear_Pelt',Count=6}, {Item='Fur',Count=16}, {Item='Rope',Count=6} } },
    ['Polarbear_Feet_Armor'] = { Inputs = { {Item='Advanced_Leather',Count=3}, {Item='Polarbear_Pelt',Count=2}, {Item='Fur',Count=8}, {Item='Rope',Count=2} } },
    ['Rope_Armor_Bench'] = { Inputs = { {Item='Leather',Count=5} } },
    ['Iron_Nail'] = { Inputs = { {Item='Refined_Metal',Count=1} } },
    ['Copper_Nail'] = { Inputs = { {Item='Refined_Copper',Count=1} } },
    ['Steel_Screw'] = { Inputs = { {Item='Steel_Ingot',Count=1} } },
    ['Iron_Hammer'] = { Inputs = { {Item='Wood',Count=4}, {Item='Leather',Count=4}, {Item='Refined_Metal',Count=10} } },
    ['Steel_Hammer'] = { Inputs = { {Item='Wood',Count=5}, {Item='Epoxy',Count=4}, {Item='Steel_Ingot',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Rifle_Round_Incendiary'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=1}, {Item='Gunpowder',Count=5} } },
    ['Rifle_Round_Explosive'] = { Inputs = { {Item='Ammo_Rifle_Round',Count=5}, {Item='Volatile_Substance',Count=1} } },
    ['Steel_Rebar'] = { Inputs = { {Item='Steel_Ingot',Count=1} } },
    ['Talent_Leather_Rope'] = { Inputs = { {Item='Leather',Count=5} } },
    ['Platinum_Bolt'] = { Inputs = { {Item='Epoxy',Count=3}, {Item='Platinum_Ingot',Count=1} } },
    ['Titanium_Bolt'] = { Inputs = { {Item='Steel_Screw',Count=4}, {Item='Titanium_Ingot',Count=1}, {Item='Carbon_Fiber',Count=1} } },
    ['Carcass_Rabbit'] = { Inputs = { {Item='AnimalCarcass_Rabbit',Count=1} } },
    ['Carcass_Kea'] = { Inputs = { {Item='AnimalCarcass_Kea',Count=1} } },
    ['Carcass_Snow_Rabbit'] = { Inputs = { {Item='AnimalCarcass_Snow_Rabbit',Count=1} } },
    ['Antibiotic_Tonic'] = { Inputs = { {Item='Yeast',Count=1}, {Item='Epoxy',Count=1}, {Item='Charcoal',Count=3} } },
    ['Antibiotic_Tonic_2'] = { Inputs = { {Item='Honeycomb',Count=3}, {Item='Charcoal',Count=3} } },
    ['Antiparasitic_Tonic'] = { Inputs = { {Item='Reed_Flower',Count=1}, {Item='Organic_Resin',Count=1}, {Item='Charcoal',Count=3} } },
    ['Antiparasitic_Tonic_2'] = { Inputs = { {Item='Honeycomb',Count=3}, {Item='Charcoal',Count=3} } },
    ['AntiPoison_Tonic'] = { Inputs = { {Item='Fiber',Count=1}, {Item='Poison_Paste',Count=1}, {Item='Charcoal',Count=3} } },
    ['Blood_Thinning_Tonic'] = { Inputs = { {Item='Lily',Count=1}, {Item='Tree_Sap',Count=1}, {Item='Charcoal',Count=3} } },
    ['Antibiotic_Pill'] = { Inputs = { {Item='Antibiotic_Tonic',Count=1}, {Item='Epoxy',Count=1}, {Item='Charcoal',Count=5} } },
    ['Antiparasitic_Pill'] = { Inputs = { {Item='Antiparasitic_Tonic',Count=1}, {Item='Organic_Resin',Count=1}, {Item='Charcoal',Count=5} } },
    ['Antipoison_Pill'] = { Inputs = { {Item='AntiPoison_Tonic',Count=1}, {Item='Poison_Paste',Count=1}, {Item='Charcoal',Count=5} } },
    ['Blood_Thinning_Pill'] = { Inputs = { {Item='Blood_Thinning_Tonic',Count=1}, {Item='Tree_Sap',Count=1}, {Item='Charcoal',Count=5} } },
    ['Splint_2'] = { Inputs = { {Item='Wood',Count=2}, {Item='Stick',Count=8}, {Item='Fiber',Count=100} } },
    ['Splint'] = { Inputs = { {Item='Wood',Count=2}, {Item='Stick',Count=8}, {Item='Rope',Count=6} } },
    ['Platinum_Knife'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=12} } },
    ['Platinum_Axe'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=12} } },
    ['Platinum_Sickle'] = { Inputs = { {Item='Wood_Refined',Count=4}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=10} } },
    ['Platinum_Hammer'] = { Inputs = { {Item='Wood_Refined',Count=5}, {Item='Epoxy',Count=4}, {Item='Platinum_Ingot',Count=6}, {Item='Steel_Screw',Count=2} } },
    ['Titanium_Hammer'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=10}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=10} } },
    ['Platinum_Pickaxe'] = { Inputs = { {Item='Wood_Refined',Count=2}, {Item='Advanced_Leather',Count=1}, {Item='Platinum_Ingot',Count=12} } },
    ['Leather_Curtain_Window'] = { Inputs = { {Item='Fiber',Count=15}, {Item='Wood',Count=5}, {Item='Leather',Count=10} } },
    ['Sandworm_Knife'] = { Inputs = { {Item='Wood',Count=2}, {Item='Leather',Count=2}, {Item='Sandworm_Scale',Count=5} } },
    ['Sandworm_Spear'] = { Inputs = { {Item='Wood',Count=16}, {Item='Leather',Count=4}, {Item='Sandworm_Scale',Count=10} } },
    ['Sandworm_Arrow'] = { Inputs = { {Item='Stick',Count=1}, {Item='Leather',Count=1}, {Item='Sandworm_Scale',Count=2} } },
    ['Sandworm_Bow'] = { Inputs = { {Item='Wood',Count=10}, {Item='Leather',Count=25}, {Item='Sandworm_Scale',Count=15} } },
    ['BoltAction_Rifle'] = { Inputs = { {Item='Wood_Refined',Count=12}, {Item='Advanced_Leather',Count=1}, {Item='Steel_Ingot',Count=40}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=10} } },
    ['Pistol_Handgun'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Leather',Count=15}, {Item='Refined_Metal',Count=20}, {Item='Tree_Sap',Count=4}, {Item='Copper_Nail',Count=10} } },
    ['Pistol_Round'] = { Inputs = { {Item='Ammo_Casing',Count=1}, {Item='Gunpowder',Count=1} } },
    ['Pistol_Explosive_Round'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=5}, {Item='Volatile_Substance',Count=1} } },
    ['Pistol_Incendiary_Round'] = { Inputs = { {Item='Ammo_Pistol_Round',Count=1}, {Item='Gunpowder',Count=5} } },
    ['Reinforced_Railing'] = { Inputs = { {Item='Wood',Count=10}, {Item='Refined_Metal',Count=8}, {Item='Iron_Nail',Count=8} } },
    ['Iron_Railing'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Concrete_Railing'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Recombined_Tech'] = { Inputs = { {Item='FactionMission_Tech1',Count=1}, {Item='FactionMission_Tech2',Count=1}, {Item='FactionMission_Tech3',Count=1} } },
    ['Glacier_Expedition_Deployable'] = { Inputs = { {Item='FactionMission_Tech1',Count=1}, {Item='FactionMission_Tech2',Count=1}, {Item='FactionMission_Tech3',Count=1} } },
    ['Recombined_HighTech'] = { Inputs = { {Item='Mission_HighTech_1',Count=1}, {Item='Mission_HighTech_2',Count=1}, {Item='Mission_HighTech_3',Count=1} } },
    ['Carcass_Boar'] = { Inputs = { {Item='AnimalCarcass_WildBoar',Count=1} } },
    ['Carcass_Boar_Tame'] = { Inputs = { {Item='AnimalCarcass_WildBoar_Tame',Count=1} } },
    ['Carcass_Boar_Juvenile'] = { Inputs = { {Item='AnimalCarcass_Boar_Juvenile',Count=1} } },
    ['Carcass_Zebra'] = { Inputs = { {Item='AnimalCarcass_Zebra',Count=1} } },
    ['Carcass_Scorpion'] = { Inputs = { {Item='AnimalCarcass_Scorpion',Count=1} } },
    ['LightningRod_Basic'] = { Inputs = { {Item='Refined_Copper',Count=10} } },
    ['Bulk_Rifle_Round'] = { Inputs = { {Item='Ammo_Casing',Count=5}, {Item='Gunpowder',Count=10} } },
    ['Bulk_Pistol_Round'] = { Inputs = { {Item='Ammo_Casing',Count=5}, {Item='Gunpowder',Count=5} } },
    ['Bulk_Shotgun_Shell_Buckshot'] = { Inputs = { {Item='Shotgun_Casing',Count=5}, {Item='Copper_Nail',Count=10}, {Item='Gunpowder',Count=5}, {Item='Epoxy',Count=5} } },
    ['Food_Cooked_Corn'] = { Inputs = { {Item='Corn',Count=1} } },
    ['Food_Cooked_Pumpkin'] = { Inputs = { {Item='Pumpkin',Count=1} } },
    ['Food_Cooked_Squash'] = { Inputs = { {Item='Squash',Count=1} } },
    ['Food_Cooked_Carrot'] = { Inputs = { {Item='Carrot',Count=1} } },
    ['Food_Cooked_Mushroom'] = { Inputs = { {Item='Mushroom',Count=1} } },
    ['Food_Corn_Soup'] = { Inputs = { {Item='Corn',Count=3} } },
    ['Food_Mushroom_Soup'] = { Inputs = { {Item='Mushroom',Count=3} } },
}
return Chunk
