-- Recipes Chunk 4
local Chunk = {
    ['Saddle_Wood_Cart_Plough'] = { Inputs = { {Item='Saddle_Standard',Count=1}, {Item='Wood',Count=80}, {Item='Iron_Nail',Count=15}, {Item='Rope',Count=20}, {Item='Epoxy',Count=10}, {Item='Wood_Refined',Count=50} } },
    ['Saddle_Wood_Cart_Water'] = { Inputs = { {Item='Saddle_Standard',Count=1}, {Item='Wood',Count=80}, {Item='Iron_Nail',Count=15}, {Item='Rope',Count=20}, {Item='Epoxy',Count=10}, {Item='Wood_Refined',Count=50} } },
    ['Saddle_Wood_Cart_Harvest'] = { Inputs = { {Item='Saddle_Standard',Count=1}, {Item='Wood',Count=80}, {Item='Iron_Nail',Count=15}, {Item='Rope',Count=20}, {Item='Epoxy',Count=10}, {Item='Wood_Refined',Count=50} } },
    ['Stone_Diagonal_Set'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Curved_Set'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Wall_Curved'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Advanced_Beams_Set'] = { Inputs = { {Item='Wood',Count=2}, {Item='Stone',Count=6}, {Item='Leather',Count=1}, {Item='Iron_Nail',Count=6} } },
    ['Stone_Roof_CurvedAngles'] = { Inputs = { {Item='Wood',Count=6}, {Item='Stone',Count=20}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Diagonal_Set'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Curved_Set'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Roof_CurvedAngles'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Wall_Curved'] = { Inputs = { {Item='Wood',Count=6}, {Item='Scoria',Count=10}, {Item='Leather',Count=4}, {Item='Iron_Nail',Count=6} } },
    ['Scoria_Advanced_Beam_Set'] = { Inputs = { {Item='Wood',Count=2}, {Item='Scoria',Count=3}, {Item='Leather',Count=1}, {Item='Iron_Nail',Count=6} } },
    ['Ice_Wall'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Floor'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Ramp'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Wall_Angle'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Beam'] = { Inputs = { {Item='Ice',Count=14} } },
    ['Ice_Roof_Corner'] = { Inputs = { {Item='Ice',Count=10} } },
    ['Ice_Half_Pitch'] = { Inputs = { {Item='Ice',Count=10} } },
    ['Ice_Halfpiece'] = { Inputs = { {Item='Ice',Count=10} } },
    ['Ice_Diagonal_Set'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Curved_Set'] = { Inputs = { {Item='Ice',Count=30} } },
    ['Ice_Diagonal_Curved_Wall_Angles'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Roof_CurvedAngles'] = { Inputs = { {Item='Ice',Count=20} } },
    ['Ice_Wall_Curved'] = { Inputs = { {Item='Ice',Count=25} } },
    ['Ice_Advanced_Beam_Set'] = { Inputs = { {Item='Ice',Count=14} } },
    ['Platinum_Shovel'] = { Inputs = { {Item='Platinum_Ingot',Count=4}, {Item='Refined_Metal',Count=6} } },
    ['Titanium_Shovel'] = { Inputs = { {Item='Titanium_Ingot',Count=4}, {Item='Carbon_Fiber',Count=6} } },
    ['Shotgun_T4'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=20}, {Item='Epoxy',Count=5}, {Item='Steel_Screw',Count=25} } },
    ['Enzyme_Cannon_Hub'] = { Inputs = { {Item='Titanium_Plate',Count=4}, {Item='Electronics',Count=20}, {Item='Steel_Screw',Count=10}, {Item='Composites',Count=8}, {Item='Epoxy',Count=22} } },
    ['Water_Trough_Large'] = { Inputs = { {Item='Wood',Count=80}, {Item='Tree_Sap',Count=12}, {Item='Iron_Nail',Count=32} } },
    ['Water_Trough_T4'] = { Inputs = { {Item='Concrete_Mix',Count=20}, {Item='Titanium_Plate',Count=2}, {Item='Electronics',Count=10}, {Item='Carbon_Fiber',Count=5} } },
    ['Food_Trough_Large'] = { Inputs = { {Item='Wood',Count=80}, {Item='Tree_Sap',Count=12}, {Item='Iron_Nail',Count=32} } },
    ['Food_Trough_T4'] = { Inputs = { {Item='Titanium_Plate',Count=2}, {Item='Electronics',Count=10}, {Item='Carbon_Fiber',Count=15}, {Item='Platinum_Weave',Count=30} } },
    ['Water_Trough_Stone'] = { Inputs = { {Item='Stone',Count=50}, {Item='Tree_Sap',Count=20} } },
    ['Water_Trough_Metal'] = { Inputs = { {Item='Aluminium',Count=30}, {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=15} } },
    ['Water_Trough_Fountain'] = { Inputs = { {Item='Concrete_Mix',Count=30}, {Item='Tree_Sap',Count=30}, {Item='Stone',Count=25} } },
    ['Food_Trough_Rustic'] = { Inputs = { {Item='Wood',Count=50}, {Item='Tree_Sap',Count=20}, {Item='Stick',Count=30} } },
    ['Food_Trough_Metal'] = { Inputs = { {Item='Aluminium',Count=30}, {Item='Refined_Metal',Count=15}, {Item='Steel_Screw',Count=15} } },
    ['Food_Trough_Glass'] = { Inputs = { {Item='Steel_Ingot',Count=25}, {Item='Glass',Count=30}, {Item='Steel_Screw',Count=15} } },
    ['Chicken_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Chicken_Head',Count=1} } },
    ['Chicken_Trophy_A2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Chicken_Head_A2',Count=1} } },
    ['Chicken_Trophy_A3'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Chicken_Head_A3',Count=1} } },
    ['Sheep_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Sheep_Head',Count=1} } },
    ['Flow_Meter'] = { Inputs = { {Item='Aluminium',Count=6}, {Item='Gold_Wire',Count=10}, {Item='Copper_Wire',Count=10}, {Item='Electronics',Count=2}, {Item='Glass',Count=2} } },
    ['Rain_Reservoir_T3'] = { Inputs = { {Item='Refined_Metal',Count=12}, {Item='Wood',Count=8}, {Item='Stone',Count=20}, {Item='Epoxy',Count=4}, {Item='Charcoal',Count=20} } },
    ['Water_Barrel'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Wood_Refined',Count=40}, {Item='Epoxy',Count=4} } },
    ['Water_Borer'] = { Inputs = { {Item='Composites',Count=4}, {Item='Steel_Ingot',Count=12}, {Item='Electronics',Count=6}, {Item='Steel_Screw',Count=8}, {Item='Copper_Wire',Count=40} } },
    ['Biofuel_Water_Pump'] = { Inputs = { {Item='Steel_Ingot',Count=16}, {Item='Electronics',Count=4}, {Item='Epoxy',Count=12}, {Item='Copper_Wire',Count=16} } },
    ['Animal_Bed_Burlap'] = { Inputs = { {Item='Fiber',Count=200} } },
    ['Animal_Bed_Heated'] = { Inputs = { {Item='Platinum_Weave',Count=25}, {Item='Gold_Wire',Count=20} } },
    ['Animal_Bed_Royal'] = { Inputs = { {Item='Platinum_Weave',Count=30}, {Item='Fur',Count=40}, {Item='Jaguar_Head',Count=1} } },
    ['Animal_Bed_WolfSkin'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Leather',Count=35}, {Item='ConiferWolf_Head',Count=1} } },
    ['Animal_Bed_LeopardSkin'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Leather',Count=35}, {Item='SnowLeopard_Head',Count=1} } },
    ['Iron_Shears'] = { Inputs = { {Item='Fiber',Count=10}, {Item='Leather',Count=10}, {Item='Refined_Metal',Count=6}, {Item='Iron_Nail',Count=2} } },
    ['Animal_Bed_Emperor'] = { Inputs = { {Item='Platinum_Weave',Count=30}, {Item='Fur',Count=40}, {Item='Jaguar_Black_Head',Count=1} } },
    ['Animal_Bed_Striker'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Fur',Count=35}, {Item='Desert_Striker_Head',Count=1}, {Item='Terrenus_Head',Count=1} } },
    ['Animal_Bed_Tusker'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Fur',Count=35}, {Item='Tusker_Head',Count=1}, {Item='Charcoal',Count=40} } },
    ['Animal_Bed_Zebra'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Fur',Count=35}, {Item='Zebra_Head',Count=1} } },
    ['Animal_Bed_Leopard'] = { Inputs = { {Item='Advanced_Leather',Count=10}, {Item='Fur',Count=35}, {Item='Jaguar_Head',Count=1}, {Item='Buffalo_Head',Count=1} } },
    ['Hitching_Post'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=6}, {Item='Rope',Count=2} } },
    ['Snare_Trap'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Stick',Count=8}, {Item='Rope',Count=2}, {Item='Stone',Count=4} } },
    ['Hitching_Rope'] = { Inputs = { {Item='Rope',Count=4} } },
    ['Pyritic_Crust_Stone'] = { Inputs = { {Item='Pyritic_Crust_Stone',Count=1} } },
    ['Pyritic_Crust_Salt'] = { Inputs = { {Item='Pyritic_Crust_Salt',Count=1} } },
    ['Pyritic_Crust_Limestone'] = { Inputs = { {Item='Pyritic_Crust_Limestone',Count=1} } },
    ['Pyritic_Crust_Lithium'] = { Inputs = { {Item='Pyritic_Crust_Lithium',Count=1} } },
    ['Pyritic_Crust_Ruby'] = { Inputs = { {Item='Pyritic_Crust_Ruby',Count=1} } },
    ['Purify_Water'] = { Inputs = { {Item='Workshop_Purification_Tablet',Count=1} } },
    ['Clean_Water'] = { Inputs = { {Item='Purification_Pill',Count=1} } },
    ['Purification_Pill'] = { Inputs = { {Item='Salt',Count=2}, {Item='Charcoal',Count=3} } },
    ['Dog_Bowl_Water'] = { Inputs = { {Item='Steel_Ingot',Count=3} } },
    ['Dog_Bowl_Food'] = { Inputs = { {Item='Steel_Ingot',Count=3} } },
    ['Cat_Bowl_Water'] = { Inputs = { {Item='Steel_Ingot',Count=3} } },
    ['Cat_Bowl_Food'] = { Inputs = { {Item='Steel_Ingot',Count=3} } },
    ['Food_Cooked_Egg'] = { Inputs = { {Item='Egg',Count=1} } },
    ['Food_Mushroom_Omlette'] = { Inputs = { {Item='Mushroom',Count=1}, {Item='Egg',Count=1} } },
    ['Food_Egg_Salad'] = { Inputs = { {Item='Egg',Count=1}, {Item='Tomato',Count=1} } },
    ['Food_Pickled_Eggs'] = { Inputs = { {Item='Egg',Count=1}, {Item='Glass_Jar',Count=1}, {Item='Salt',Count=5} } },
    ['Food_Big_Breakfast'] = { Inputs = { {Item='Egg',Count=1}, {Item='Raw_Meat',Count=1}, {Item='Potato',Count=1}, {Item='Tomato',Count=1} } },
    ['Food_Scrambled_Eggs'] = { Inputs = { {Item='Egg',Count=1}, {Item='Food_Bread',Count=1} } },
    ['Food_Smashed_Avocado'] = { Inputs = { {Item='Avocado',Count=1}, {Item='Food_Bread',Count=1} } },
    ['Grilled_Chicken'] = { Inputs = { {Item='Raw_Chicken',Count=1}, {Item='Charcoal',Count=2} } },
    ['Fried_Chicken'] = { Inputs = { {Item='Raw_Chicken',Count=1}, {Item='Seed_Oil',Count=1} } },
    ['Roast_Chicken'] = { Inputs = { {Item='Salt',Count=5}, {Item='Raw_Chicken',Count=1} } },
    ['Horse_Trophy_A1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Horse_Head_A1',Count=1} } },
    ['Horse_Trophy_A2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Horse_Head_A2',Count=1} } },
    ['Horse_Trophy_A3'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Horse_Head_A3',Count=1} } },
    ['Cat_Trophy_A1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Cat_Head_A1',Count=1} } },
    ['Cat_Trophy_A2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Cat_Head_A2',Count=1} } },
    ['Cat_Trophy_A3'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Cat_Head_A3',Count=1} } },
    ['Dog_Trophy_A1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_A1',Count=1} } },
    ['Dog_Trophy_A2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_A2',Count=1} } },
    ['Dog_Trophy_B1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_B1',Count=1} } },
    ['Dog_Trophy_B2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_B2',Count=1} } },
    ['Dog_Trophy_C1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_C1',Count=1} } },
    ['Animal_Feed_Squash'] = { Inputs = { {Item='Seed',Count=10}, {Item='Squash',Count=5} } },
    ['Animal_Feed_Pumpkin'] = { Inputs = { {Item='Seed',Count=10}, {Item='Pumpkin',Count=5} } },
    ['Animal_Feed_Potato'] = { Inputs = { {Item='Seed',Count=10}, {Item='Potato',Count=5} } },
    ['Animal_Feed_Corn'] = { Inputs = { {Item='Seed',Count=10}, {Item='Corn',Count=5} } },
    ['Animal_Feed_Carrot'] = { Inputs = { {Item='Seed',Count=10}, {Item='Carrot',Count=5} } },
    ['Animal_Feed_Mushroom'] = { Inputs = { {Item='Seed',Count=10}, {Item='Mushroom',Count=5} } },
    ['Animal_Feed_Bean'] = { Inputs = { {Item='Seed',Count=10}, {Item='Bean',Count=5} } },
    ['Animal_Feed_Omni'] = { Inputs = { {Item='Honey',Count=1} } },
    ['Platinum_Weave_Wool'] = { Inputs = { {Item='Wool',Count=2}, {Item='Platinum_Shealth',Count=2} } },
    ['Packed_Fuel_Brick'] = { Inputs = { {Item='Tree_Sap',Count=1}, {Item='Fur',Count=20} } },
    ['Fur_From_Wool'] = { Inputs = { {Item='Wool',Count=2} } },
    ['Arctic_Pelt_Wool'] = { Inputs = { {Item='Wool',Count=6}, {Item='Fiber',Count=30} } },
    ['Rope_Armor_Bench_Wool'] = { Inputs = { {Item='Wool',Count=3} } },
    ['Bandage_Basic_Wool'] = { Inputs = { {Item='Wool',Count=6} } },
    ['Bandage_Heat_Wool'] = { Inputs = { {Item='Wool',Count=6}, {Item='Oxite',Count=4}, {Item='Charcoal',Count=10} } },
    ['Bandage_Cooling_Wool'] = { Inputs = { {Item='Wool',Count=6}, {Item='Oxite',Count=4}, {Item='Charcoal',Count=10} } },
    ['Suture_Kit_Wool'] = { Inputs = { {Item='Wool',Count=2}, {Item='Bone',Count=5}, {Item='Leather',Count=2} } },
    ['Mission_Incubator'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Electronics',Count=4}, {Item='Glass',Count=15}, {Item='Copper_Wire',Count=16} } },
    ['Creature_Bait_Wolf'] = { Inputs = { {Item='Stringy_Meat',Count=1}, {Item='Animal_Fat',Count=2}, {Item='Spoiled_Meat',Count=5} } },
    ['Creature_Bait_Boar'] = { Inputs = { {Item='Raw_Bacon',Count=1}, {Item='Animal_Fat',Count=2}, {Item='Spoiled_Plants',Count=5} } },
    ['Creature_Bait_Hyena'] = { Inputs = { {Item='Gamey_Meat',Count=1}, {Item='Animal_Fat',Count=2}, {Item='Spoiled_Meat',Count=5} } },
    ['Animal_Bench'] = { Inputs = { {Item='Rope',Count=10}, {Item='Wood',Count=30}, {Item='Leather',Count=20}, {Item='Fur',Count=10}, {Item='Iron_Nail',Count=15} } },
    ['Chicken_Coop'] = { Inputs = { {Item='Wood',Count=100}, {Item='Leather',Count=50}, {Item='Fiber',Count=100}, {Item='Iron_Nail',Count=25} } },
    ['Chicken_Coop_Red'] = { Inputs = { {Item='Wood',Count=100}, {Item='Leather',Count=50}, {Item='Fiber',Count=100}, {Item='Iron_Nail',Count=25}, {Item='Paints',Count=5} } },
    ['Dirt_Ramp'] = { Inputs = { {Item='Dirt',Count=10} } },
    ['Dirt_Frame'] = { Inputs = { {Item='Dirt',Count=20} } },
    ['Kitchen_Corner'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Refined_Metal',Count=2}, {Item='Epoxy',Count=10}, {Item='Copper_Nail',Count=12} } },
    ['Advanced_Kitchen_Corner'] = { Inputs = { {Item='Composites',Count=1}, {Item='Aluminium',Count=5}, {Item='Concrete_Mix',Count=5}, {Item='Steel_Screw',Count=8}, {Item='Stone',Count=100} } },
    ['Medicine_Bench'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=8}, {Item='Organic_Resin',Count=5}, {Item='Copper_Nail',Count=20}, {Item='Glass',Count=5} } },
    ['Basic_Ceiling_Light'] = { Inputs = { {Item='Refined_Metal',Count=15}, {Item='Glass',Count=6}, {Item='Copper_Wire',Count=40} } },
    ['Exposed_Ceiling_Light'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Glass',Count=3}, {Item='Copper_Wire',Count=10} } },
    ['Single_Ceiling_Light'] = { Inputs = { {Item='Refined_Metal',Count=7}, {Item='Glass',Count=4}, {Item='Copper_Wire',Count=15} } },
    ['Wood_Burner'] = { Inputs = { {Item='Steel_Ingot',Count=30}, {Item='Refined_Copper',Count=10}, {Item='Iron_Nail',Count=15} } },
    ['Glass2'] = { Inputs = { {Item='Sand',Count=10} } },
    ['Health_Remedy'] = { Inputs = { {Item='Oxite',Count=3}, {Item='Salt',Count=2}, {Item='Bone',Count=3} } },
    ['Health_Elixir'] = { Inputs = { {Item='Organic_Resin',Count=6}, {Item='Charcoal',Count=5}, {Item='Flour',Count=2}, {Item='Salt',Count=3} } },
    ['Electric_Oxite_Dissolver'] = { Inputs = { {Item='Titanium_Plate',Count=2}, {Item='Glass',Count=10}, {Item='Electronics',Count=20}, {Item='Copper_Wire',Count=70} } },
    ['Iron_Beam_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Floor_Ingot'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Wall_Ingot'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Wall_Angled_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Ramp_Ingot'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Door_Ingot'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_TrapDoor_Ingot'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Wood',Count=6}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Window_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=4} } },
    ['Iron_Ladder_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Iron_Railing_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Iron_Halfpiece_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Half_Pitch_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Iron_Roof_Corner_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=3}, {Item='Steel_Screw',Count=2} } },
    ['Stone_Cairn'] = { Inputs = { {Item='Stone',Count=80} } },
    ['Exposed_Ceiling_Light_Foggy'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Glass',Count=3}, {Item='Copper_Wire',Count=10} } },
    ['Medicine_Bag'] = { Inputs = { {Item='Rope',Count=12}, {Item='Leather',Count=20}, {Item='Iron_Nail',Count=5} } },
    ['Vitamins'] = { Inputs = { {Item='Organic_Resin',Count=3}, {Item='Lily',Count=2}, {Item='Charcoal',Count=2}, {Item='Reed_Flower',Count=2}, {Item='Salt',Count=2} } },
    ['Dressing_Kit'] = { Inputs = { {Item='Platinum_Weave',Count=2}, {Item='Organic_Resin',Count=2}, {Item='Rope',Count=2}, {Item='Charcoal',Count=5}, {Item='Honey',Count=5}, {Item='Reed_Flower',Count=4}, {Item='Lily',Count=4} } },
    ['Dirt_Corner'] = { Inputs = { {Item='Dirt',Count=20} } },
    ['LightningRod_Platinum'] = { Inputs = { {Item='Platinum_Ingot',Count=12}, {Item='Copper_Wire',Count=25}, {Item='Electronics',Count=2} } },
    ['Charging_Station'] = { Inputs = { {Item='Electronics',Count=10}, {Item='Concrete_Mix',Count=8}, {Item='Steel_Screw',Count=18}, {Item='Glass',Count=6}, {Item='Copper_Wire',Count=65}, {Item='Aluminium',Count=10} } },
    ['Butchery_Bench'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Refined_Metal',Count=20}, {Item='Copper_Nail',Count=20}, {Item='Steel_Ingot',Count=10} } },
    ['Advanced_Butchery_Bench'] = { Inputs = { {Item='Composites',Count=1}, {Item='Aluminium',Count=5}, {Item='Concrete_Mix',Count=5}, {Item='Steel_Screw',Count=8}, {Item='Stone',Count=100}, {Item='Steel_Ingot',Count=20} } },
    ['Dog_Trophy_D1_1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_D1',Count=1} } },
    ['Dog_Trophy_D1_2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_D1',Count=1}, {Item='Dog_Accessory_D',Count=1} } },
    ['Dog_D_Accessory'] = { Inputs = { {Item='Leather',Count=25}, {Item='Rope',Count=15} } },
    ['Dog_Trophy_D2_1'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_D2',Count=1} } },
    ['Dog_Trophy_D2_2'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Dog_Head_D2',Count=1}, {Item='Dog_Accessory_D',Count=1} } },
    ['Thatch_Railing_Gate'] = { Inputs = { {Item='Fiber',Count=8}, {Item='Stick',Count=2} } },
    ['Interior_Wood_Railing_Gate'] = { Inputs = { {Item='Wood_Refined',Count=8}, {Item='Copper_Nail',Count=4} } },
    ['Reinforced_Railing_Gate'] = { Inputs = { {Item='Wood',Count=10}, {Item='Refined_Metal',Count=8}, {Item='Iron_Nail',Count=8} } },
    ['Iron_Railing_Gate'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Concrete_Railing_Gate'] = { Inputs = { {Item='Bauxite',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Clay_Brick_Railing_Gate'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Wood_Refined',Count=5} } },
    ['Stone_Brick_Beam'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=15}, {Item='Tree_Sap',Count=4}, {Item='Steel_Screw',Count=6} } },
    ['Stone_Brick_Floor'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=30}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['Stone_Brick_Wall'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=30}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['Stone_Brick_Halfpiece'] = { Inputs = { {Item='Wood_Refined',Count=3}, {Item='Stone_Brick',Count=15}, {Item='Tree_Sap',Count=3}, {Item='Steel_Screw',Count=3} } },
    ['Stone_Brick_Half_Pitch'] = { Inputs = { {Item='Wood_Refined',Count=3}, {Item='Stone_Brick',Count=15}, {Item='Tree_Sap',Count=3}, {Item='Steel_Screw',Count=3} } },
    ['Stone_Brick_Wall_Angle'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=15}, {Item='Tree_Sap',Count=3}, {Item='Steel_Screw',Count=3} } },
    ['Stone_Brick_Ramp'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Stone_Brick',Count=30}, {Item='Tree_Sap',Count=6}, {Item='Steel_Screw',Count=6} } },
    ['Stone_Brick_Roof_Corner'] = { Inputs = { {Item='Wood_Refined',Count=3}, {Item='Stone_Brick',Count=15}, {Item='Tree_Sap',Count=3}, {Item='Steel_Screw',Count=3} } },
    ['Kiwi_Nest'] = { Inputs = { {Item='Fiber',Count=50}, {Item='Stick',Count=30}, {Item='Tree_Sap',Count=25}, {Item='Dirt',Count=5} } },
    ['Kiwi_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Kiwi_Head',Count=1} } },
    ['Dried_Kiwifruit'] = { Inputs = { {Item='Kiwi_Fruit',Count=1} } },
    ['Kiwifruit_Jam'] = { Inputs = { {Item='Glass_Jar',Count=1}, {Item='Kiwi_Fruit',Count=5} } },
    ['Kiwifruit_Sorbet'] = { Inputs = { {Item='Kiwi_Fruit',Count=5}, {Item='Ice',Count=10}, {Item='Honey',Count=2} } },
    ['Fruit_Snack_Pack'] = { Inputs = { {Item='Kiwi_Fruit',Count=2}, {Item='Strawberry',Count=10}, {Item='Watermelon',Count=1}, {Item='Coconut_mature',Count=1}, {Item='Seed',Count=20} } },
    ['Fruit_Smoothie'] = { Inputs = { {Item='Kiwi_Fruit',Count=5}, {Item='Coconut_mature',Count=2}, {Item='Watermelon',Count=1}, {Item='Berry',Count=5}, {Item='Strawberry',Count=10} } },
    ['Stone_Brick'] = { Inputs = { {Item='Stone',Count=3} } },
    ['Mission_AerosolEmitter'] = { Inputs = { {Item='Mission_Liquid_Deployment',Count=1}, {Item='Aluminium',Count=8}, {Item='Titanium_Plate',Count=2}, {Item='Refined_Metal',Count=20}, {Item='Gold_Wire',Count=12} } },
    ['Mission_LiquidDeployment'] = { Inputs = { {Item='Volatile_Substance',Count=2}, {Item='Sulfur',Count=15}, {Item='Crushed_Bone',Count=6}, {Item='Poison_Paste',Count=4}, {Item='Honey',Count=4}, {Item='Salt',Count=5} } },
    ['Mission_MonitoringPylon'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Platinum_Shealth',Count=6}, {Item='Refined_Gold',Count=8} } },
    ['Seed_Pouch_T2'] = { Inputs = { {Item='Rope',Count=8}, {Item='Leather',Count=30}, {Item='Iron_Nail',Count=7} } },
    ['Quality_Fertilizer'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Crushed_Bone',Count=3} } },
    ['Resistance_Fertilizer'] = { Inputs = { {Item='Basic_Fertilizer',Count=1}, {Item='Oxite',Count=4} } },
    ['Sandworm_Trophy_Head'] = { Inputs = { {Item='Sandworm_Head',Count=1}, {Item='Wood_Refined',Count=30} } },
    ['Sandworm_Module'] = { Inputs = { {Item='Sandworm_Scale',Count=10}, {Item='Sandworm_Tendon',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Sandworm_Attachment'] = { Inputs = { {Item='Sandworm_Scale',Count=8}, {Item='Carbon_Fiber',Count=2}, {Item='Sandworm_Tendon',Count=2} } },
    ['Black_Wolf_Module'] = { Inputs = { {Item='Black_Fur',Count=10}, {Item='Black_Wolf_Tooth',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Black_Wolf_Attachment'] = { Inputs = { {Item='Black_Fur',Count=2}, {Item='Carbon_Fiber',Count=2}, {Item='Black_Wolf_Tooth',Count=8} } },
    ['Black_Wolf_Trap'] = { Inputs = { {Item='Black_Fur',Count=1}, {Item='Electronics',Count=1}, {Item='Black_Wolf_Tooth',Count=8}, {Item='Steel_Ingot',Count=6}, {Item='Gold_Wire',Count=8} } },
    ['Black_Wolf_Trophy'] = { Inputs = { {Item='Alphawolf_Head',Count=1}, {Item='Wood_Refined',Count=30} } },
    ['Black_Wolf_Trophy_Howl'] = { Inputs = { {Item='Alphawolf_Head',Count=1}, {Item='Wood_Refined',Count=30} } },
    ['Black_Wolf_Trophy_Sit'] = { Inputs = { {Item='Alphawolf_Head',Count=1}, {Item='Wood_Refined',Count=30} } },
    ['Scorpion_Module'] = { Inputs = { {Item='Venom_Sac',Count=10}, {Item='Scorpion_Carapace',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Scorpion_Attachment'] = { Inputs = { {Item='Venom_Sac',Count=2}, {Item='Carbon_Fiber',Count=2}, {Item='Scorpion_Carapace',Count=8} } },
    ['Scorpion_Boss_Trophy_Chair'] = { Inputs = { {Item='Scorpion_Boss_Head',Count=1}, {Item='Advanced_Leather',Count=15}, {Item='Stone',Count=40}, {Item='Scorpion_Carapace',Count=20} } },
    ['Scorpion_Boss_Trophy_Hanging'] = { Inputs = { {Item='Scorpion_Boss_Head',Count=1}, {Item='Wood_Refined',Count=30}, {Item='Iron_Nail',Count=8} } },
    ['Scorpion_Boss_Trophy_Tail'] = { Inputs = { {Item='Scorpion_Boss_Head',Count=1}, {Item='Wood_Refined',Count=30} } },
    ['Slug_Module'] = { Inputs = { {Item='Slug_Slime',Count=10}, {Item='Slug_Skin',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Slug_Attachment'] = { Inputs = { {Item='Slug_Skin',Count=8}, {Item='Carbon_Fiber',Count=2}, {Item='Slug_Slime',Count=2} } },
    ['Slug_Grenade'] = { Inputs = { {Item='Slug_Slime',Count=1}, {Item='Epoxy',Count=4}, {Item='Glass',Count=2}, {Item='Wood',Count=2} } },
    ['Slug_Axe'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Slug_Slime',Count=4}, {Item='Titanium_Ingot',Count=6}, {Item='Slug_Skin',Count=2} } },
    ['Slug_Trophy_Coil'] = { Inputs = { {Item='Slug_Head',Count=1}, {Item='Slug_Skin',Count=4}, {Item='Iron_Nail',Count=12}, {Item='Fur',Count=30}, {Item='Steel_Rebar',Count=4}, {Item='Slug_Slime',Count=1} } },
    ['Slug_Trophy_Habitat'] = { Inputs = { {Item='Glass',Count=16}, {Item='Wood_Refined',Count=20}, {Item='Refined_Metal',Count=8}, {Item='Slug_Head',Count=1}, {Item='Slug_Skin',Count=6}, {Item='Slug_Slime',Count=2} } },
    ['Slug_Trophy_Vial'] = { Inputs = { {Item='Glass',Count=12}, {Item='Refined_Metal',Count=4}, {Item='Slug_Head',Count=1}, {Item='Slug_Skin',Count=1}, {Item='Slug_Slime',Count=2} } },
    ['Slug_Epoxy'] = { Inputs = { {Item='Slug_Slime',Count=1} } },
    ['Lava_Hunter_Mine'] = { Inputs = { {Item='Lava_Hunter_Magma',Count=2}, {Item='Electronics',Count=1}, {Item='Lava_Hunter_Horn',Count=6}, {Item='Volatile_Substance',Count=2} } },
    ['Lava_Hunter_Sickle'] = { Inputs = { {Item='Carbon_Fiber',Count=4}, {Item='Lava_Hunter_Magma',Count=2}, {Item='Lava_Hunter_Horn',Count=6}, {Item='Epoxy',Count=4}, {Item='Titanium_Ingot',Count=10} } },
    ['Lava_Hunter_Backpack'] = { Inputs = { {Item='Advanced_Leather',Count=25}, {Item='Electronics',Count=15}, {Item='Carbon_Fiber',Count=6}, {Item='Steel_Screw',Count=10}, {Item='Lava_Hunter_Magma',Count=16}, {Item='Lava_Hunter_Horn',Count=2} } },
    ['Lava_Hunter_Trophy_Throne'] = { Inputs = { {Item='Lava_Hunter_Head',Count=1}, {Item='Refined_Metal',Count=6}, {Item='Steel_Screw',Count=8}, {Item='Lava_Hunter_Horn',Count=5}, {Item='Lava_Hunter_Magma',Count=5} } },
    ['Lava_Hunter_Trophy_Feature'] = { Inputs = { {Item='Lava_Hunter_Head',Count=1}, {Item='Gold_Wire',Count=24}, {Item='Steel_Screw',Count=4}, {Item='Lava_Hunter_Horn',Count=5}, {Item='Lava_Hunter_Magma',Count=10} } },
    ['Lava_Hunter_Trophy_Head'] = { Inputs = { {Item='Lava_Hunter_Head',Count=1}, {Item='Wood_Refined',Count=30} } },
    ['Lava_Hunter_Module'] = { Inputs = { {Item='Lava_Hunter_Magma',Count=10}, {Item='Lava_Hunter_Horn',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Lava_Hunter_Attachment'] = { Inputs = { {Item='Lava_Hunter_Magma',Count=8}, {Item='Carbon_Fiber',Count=2}, {Item='Lava_Hunter_Horn',Count=2} } },
    ['Pistol_T3'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Advanced_Leather',Count=5}, {Item='Steel_Ingot',Count=20}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=8} } },
    ['Rock_Golem_Sledgehammer'] = { Inputs = { {Item='Titanium_Ingot',Count=8}, {Item='Carbon_Fiber',Count=6}, {Item='Rock_Golem_Core',Count=10}, {Item='Rock_Golem_Fragment',Count=2}, {Item='Wood_Refined',Count=20} } },
    ['Rock_Golem_Gun'] = { Inputs = { {Item='Rock_Golem_Core',Count=8}, {Item='Refined_Copper',Count=15}, {Item='Steel_Ingot',Count=30}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=16} } },
    ['Rock_Golem_Grenade'] = { Inputs = { {Item='Rock_Golem_Core',Count=1}, {Item='Iron_Nail',Count=14}, {Item='Refined_Metal',Count=1}, {Item='Volatile_Substance',Count=2} } },
    ['Rock_Golem_Attachment'] = { Inputs = { {Item='Rock_Golem_Core',Count=2}, {Item='Carbon_Fiber',Count=2}, {Item='Rock_Golem_Fragment',Count=8} } },
    ['Rock_Golem_Module'] = { Inputs = { {Item='Rock_Golem_Fragment',Count=10}, {Item='Rock_Golem_Core',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Rock_Golem_Trophy'] = { Inputs = { {Item='Rock_Golem_Head',Count=1}, {Item='Stone',Count=100}, {Item='Rock_Golem_Core',Count=5}, {Item='Rock_Golem_Fragment',Count=2} } },
    ['Rock_Golem_Trophy_Lamp'] = { Inputs = { {Item='Rock_Golem_Head',Count=1}, {Item='Stone',Count=20}, {Item='Salt',Count=12}, {Item='Rock_Golem_Fragment',Count=6}, {Item='Rock_Golem_Core',Count=2} } },
    ['Slug_Biomass_1'] = { Inputs = { {Item='Slug_Skin',Count=5} } },
    ['Biomass_To_Slug_Skin'] = { Inputs = { {Item='Biomass',Count=5} } },
    ['Slug_Biomass_2'] = { Inputs = { {Item='Slug_Slime',Count=3} } },
    ['Biomass_To_Slug_Slime'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Rock_Golem_Biomass_1'] = { Inputs = { {Item='Rock_Golem_Fragment',Count=5} } },
    ['Biomass_To_Rock_Fragment'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Rock_Golem_Biomass_2'] = { Inputs = { {Item='Rock_Golem_Core',Count=3} } },
    ['Biomass_To_Golem_Core'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Ape_Biomass_1'] = { Inputs = { {Item='Ape_Hide',Count=5} } },
    ['Biomass_To_Ape_Hide'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Ape_Biomass_2'] = { Inputs = { {Item='Ape_Bicep',Count=3} } },
    ['Biomass_To_Ape_Bicep'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Lava_Hunter_Biomass_1'] = { Inputs = { {Item='Lava_Hunter_Horn',Count=5} } },
    ['Biomass_To_Lava_Hunter_Horn'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Lava_Hunter_Biomass_2'] = { Inputs = { {Item='Lava_Hunter_Magma',Count=3} } },
    ['Biomass_To_Lava_Hunter_Magma'] = { Inputs = { {Item='Biomass',Count=1} } },
    ['Ape_Trophy'] = { Inputs = { {Item='Ape_Head',Count=1}, {Item='Ape_Bicep',Count=4}, {Item='Ape_Hide',Count=8}, {Item='Refined_Metal',Count=26}, {Item='Glass',Count=60}, {Item='Wood_Refined',Count=35} } },
    ['Ape_Rug'] = { Inputs = { {Item='Ape_Head',Count=1}, {Item='Ape_Hide',Count=8}, {Item='Fur',Count=14}, {Item='Advanced_Leather',Count=10}, {Item='Platinum_Weave',Count=5} } },
    ['Ape_Fishing_Trap'] = { Inputs = { {Item='Ape_Hide',Count=4}, {Item='Ape_Bicep',Count=2}, {Item='Wood_Refined',Count=24}, {Item='Rope',Count=4}, {Item='Advanced_Leather',Count=6} } },
    ['Ape_Armor_Head'] = { Inputs = { {Item='Ape_Hide',Count=6}, {Item='Advanced_Leather',Count=10}, {Item='Epoxy',Count=4}, {Item='Ape_Head',Count=1}, {Item='Titanium_Plate',Count=2}, {Item='Ape_Bicep',Count=2} } },
    ['Ape_Armor_Chest'] = { Inputs = { {Item='Ape_Hide',Count=10}, {Item='Advanced_Leather',Count=22}, {Item='Epoxy',Count=4}, {Item='Titanium_Plate',Count=6}, {Item='Ape_Bicep',Count=4} } },
    ['Ape_Armor_Arms'] = { Inputs = { {Item='Ape_Hide',Count=6}, {Item='Advanced_Leather',Count=12}, {Item='Epoxy',Count=4}, {Item='Titanium_Plate',Count=2}, {Item='Ape_Bicep',Count=2} } },
    ['Ape_Armor_Legs'] = { Inputs = { {Item='Ape_Hide',Count=8}, {Item='Advanced_Leather',Count=16}, {Item='Epoxy',Count=4}, {Item='Titanium_Plate',Count=4}, {Item='Ape_Bicep',Count=3} } },
    ['Ape_Armor_Feet'] = { Inputs = { {Item='Ape_Hide',Count=4}, {Item='Advanced_Leather',Count=8}, {Item='Epoxy',Count=4}, {Item='Titanium_Plate',Count=2}, {Item='Ape_Bicep',Count=2} } },
    ['Ape_Attractor'] = { Inputs = { {Item='Ape_Bicep',Count=12}, {Item='Ape_Hide',Count=8}, {Item='Electronics',Count=12}, {Item='Refined_Metal',Count=16}, {Item='Advanced_Leather',Count=22} } },
    ['Ape_Tonic'] = { Inputs = { {Item='Ape_Bicep',Count=2}, {Item='Organic_Resin',Count=1}, {Item='Yeast',Count=1}, {Item='Tree_Sap',Count=2} } },
    ['Ape_Module'] = { Inputs = { {Item='Ape_Hide',Count=10}, {Item='Ape_Bicep',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['Ape_Attachment'] = { Inputs = { {Item='Ape_Bicep',Count=2}, {Item='Carbon_Fiber',Count=2}, {Item='Ape_Hide',Count=8} } },
    ['IceMammoth_Attachment'] = { Inputs = { {Item='Frozen_Wool',Count=2}, {Item='Carbon_Fiber',Count=2}, {Item='Ice_Armor_Fragment',Count=8} } },
    ['IceMammoth_Module'] = { Inputs = { {Item='Ice_Armor_Fragment',Count=10}, {Item='Frozen_Wool',Count=4}, {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=2} } },
    ['IceMammoth_Armor_Head'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Ice_Armor_Fragment',Count=12}, {Item='Frozen_Wool',Count=4}, {Item='Steel_Screw',Count=6}, {Item='Carbon_Fiber',Count=2} } },
    ['IceMammoth_Armor_Chest'] = { Inputs = { {Item='Aluminium',Count=6}, {Item='Ice_Armor_Fragment',Count=24}, {Item='Frozen_Wool',Count=4}, {Item='Steel_Screw',Count=12}, {Item='Carbon_Fiber',Count=2} } },
    ['IceMammoth_Armor_Arms'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Ice_Armor_Fragment',Count=8}, {Item='Frozen_Wool',Count=4}, {Item='Steel_Screw',Count=6}, {Item='Carbon_Fiber',Count=2} } },
    ['IceMammoth_Armor_Legs'] = { Inputs = { {Item='Aluminium',Count=6}, {Item='Ice_Armor_Fragment',Count=18}, {Item='Frozen_Wool',Count=4}, {Item='Steel_Screw',Count=8}, {Item='Carbon_Fiber',Count=2} } },
    ['IceMammoth_Armor_Feet'] = { Inputs = { {Item='Aluminium',Count=4}, {Item='Ice_Armor_Fragment',Count=12}, {Item='Frozen_Wool',Count=4}, {Item='Steel_Screw',Count=6}, {Item='Carbon_Fiber',Count=2} } },
    ['IceMammoth_Trap'] = { Inputs = { {Item='Frozen_Wool',Count=2}, {Item='Electronics',Count=2}, {Item='Ice_Armor_Fragment',Count=6}, {Item='Platinum_Ingot',Count=4}, {Item='Titanium_Plate',Count=1}, {Item='Gold_Wire',Count=8} } },
    ['IceMammoth_Trophy_Head'] = { Inputs = { {Item='IceMammoth_Head',Count=1}, {Item='Refined_Metal',Count=4}, {Item='Rope',Count=8}, {Item='Frozen_Wool',Count=4} } },
    ['IceMammoth_Trophy_Feature'] = { Inputs = { {Item='IceMammoth_Head',Count=1}, {Item='Refined_Metal',Count=4}, {Item='Steel_Rebar',Count=8}, {Item='Titanium_Plate',Count=2} } },
    ['IceMammoth_Trophy_Chandelier'] = { Inputs = { {Item='IceMammoth_Head',Count=1}, {Item='Refined_Metal',Count=4}, {Item='Ice_Armor_Fragment',Count=4} } },
    ['Pistol_T4'] = { Inputs = { {Item='Wood_Refined',Count=6}, {Item='Advanced_Leather',Count=1}, {Item='Titanium_Ingot',Count=16}, {Item='Epoxy',Count=4}, {Item='Steel_Screw',Count=8} } },
    ['Crude_Ammo'] = { Inputs = { {Item='Refined_Metal',Count=2}, {Item='Gunpowder',Count=1} } },
    ['Trail_Beacon'] = { Inputs = { {Item='Gold_Wire',Count=10}, {Item='Copper_Wire',Count=5}, {Item='Steel_Ingot',Count=4}, {Item='Steel_Screw',Count=4}, {Item='Glass',Count=2} } },
    ['Trail_Beacon_Tool'] = { Inputs = { {Item='Gold_Wire',Count=10}, {Item='Copper_Wire',Count=15}, {Item='Steel_Ingot',Count=2}, {Item='Platinum_Shealth',Count=4}, {Item='Glass',Count=2} } },
    ['Ape_Grenade'] = { Inputs = { {Item='Ape_Bicep',Count=1}, {Item='Electronics',Count=1}, {Item='Refined_Metal',Count=2}, {Item='Sulfur',Count=8} } },
    ['Mini_Hippo_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Mini_Hippo_Head',Count=3} } },
    ['Arctic_Bat_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Arctic_Bat_Head',Count=1} } },
    ['Icebox_Backpack'] = { Inputs = { {Item='Aluminium',Count=25}, {Item='Electronics',Count=10}, {Item='Carbon_Fiber',Count=5}, {Item='Steel_Screw',Count=10} } },
    ['Manufacturer'] = { Inputs = { {Item='Titanium_Plate',Count=10}, {Item='Electronics',Count=50}, {Item='Composites',Count=30}, {Item='Steel_Screw',Count=100}, {Item='Steel_Ingot',Count=50} } },
    ['Oil_Barrel'] = { Inputs = { {Item='Steel_Ingot',Count=35}, {Item='Aluminium_Screw',Count=15} } },
    ['Pipe_Tool_Crude_Oil'] = { Inputs = { {Item='Refined_Copper',Count=20}, {Item='Epoxy',Count=20} } },
    ['Pipe_Tool_Biofuel'] = { Inputs = { {Item='Refined_Copper',Count=20}, {Item='Epoxy',Count=20} } },
    ['Pump_Jack'] = { Inputs = { {Item='Titanium_Plate',Count=10}, {Item='Steel_Ingot',Count=40}, {Item='Composites',Count=20}, {Item='Electronics',Count=30}, {Item='Aluminium_Screw',Count=80}, {Item='Concrete_Mix',Count=20} } },
    ['Crude_Oil_Refiner'] = { Inputs = { {Item='Titanium_Plate',Count=20}, {Item='Steel_Ingot',Count=50}, {Item='Composites',Count=30}, {Item='Electronics',Count=40}, {Item='Aluminium_Screw',Count=100}, {Item='Concrete_Mix',Count=20} } },
    ['Natural_Oil_Refiner'] = { Inputs = { {Item='Steel_Ingot',Count=40}, {Item='Glass',Count=30}, {Item='Wood_Refined',Count=30}, {Item='Electronics',Count=20}, {Item='Copper_Wire',Count=25}, {Item='Aluminium_Screw',Count=60} } },
    ['Polymerizer'] = { Inputs = { {Item='Titanium_Plate',Count=20}, {Item='Steel_Ingot',Count=25}, {Item='Electronics',Count=45}, {Item='Aluminium_Screw',Count=70}, {Item='Copper_Wire',Count=50}, {Item='Carbon_Fiber',Count=40} } },
    ['Organic_Extractor'] = { Inputs = { {Item='Steel_Ingot',Count=30}, {Item='Wood_Refined',Count=30}, {Item='Electronics',Count=20}, {Item='Copper_Wire',Count=25}, {Item='Aluminium_Screw',Count=60}, {Item='Composites',Count=15} } },
    ['Crude_Oil_Power_Generator'] = { Inputs = { {Item='Titanium_Plate',Count=35}, {Item='Steel_Ingot',Count=50}, {Item='Electronics',Count=40}, {Item='Carbon_Fiber',Count=30}, {Item='Aluminium_Screw',Count=100}, {Item='Plastics',Count=50} } },
    ['Portable_Biofuel_Generator'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Copper_Wire',Count=20}, {Item='Electronics',Count=6}, {Item='Steel_Screw',Count=10}, {Item='Glass',Count=2} } },
    ['Battery_Latern'] = { Inputs = { {Item='Glass',Count=4}, {Item='Aluminium',Count=4}, {Item='Epoxy',Count=4}, {Item='Electronics',Count=2} } },
    ['Iron_Bucket'] = { Inputs = { {Item='Refined_Metal',Count=10}, {Item='Rope',Count=5}, {Item='Iron_Nail',Count=2} } },
    ['CaveLight_Floor'] = { Inputs = { {Item='Glass',Count=5}, {Item='Steel_Ingot',Count=5}, {Item='Steel_Screw',Count=10}, {Item='Electronics',Count=2}, {Item='Copper_Wire',Count=20} } },
    ['CaveSpotLight_Floor'] = { Inputs = { {Item='Glass',Count=8}, {Item='Aluminium',Count=5}, {Item='Epoxy',Count=6}, {Item='Electronics',Count=3}, {Item='Copper_Wire',Count=10} } },
    ['Glass_Wall_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=20}, {Item='Epoxy',Count=6} } },
    ['Glass_Wall_Angled_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Ramp_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=20}, {Item='Epoxy',Count=6} } },
    ['Glass_Beam_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=4}, {Item='Epoxy',Count=6} } },
    ['Glass_Floor_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=20}, {Item='Epoxy',Count=6} } },
    ['Glass_Halfpiece_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Half_Pitch_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Glass_Roof_Corner_Tempered'] = { Inputs = { {Item='Steel_Ingot',Count=1}, {Item='Glass',Count=10}, {Item='Epoxy',Count=3} } },
    ['Jerry_Can_Water'] = { Inputs = { {Item='Epoxy',Count=50} } },
    ['Portable_Tank_Water'] = { Inputs = { {Item='Composites',Count=20}, {Item='Epoxy',Count=30} } },
    ['Iron_Railing_Gate_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Concrete_Railing_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Concrete_Railing_Gate_Ingot'] = { Inputs = { {Item='Aluminium',Count=2}, {Item='Wood',Count=2}, {Item='Steel_Screw',Count=6} } },
    ['Medical_Device'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Gold_Wire',Count=25}, {Item='Electronics',Count=5}, {Item='Copper_Wire',Count=25} } },
    ['Mission_Alternator'] = { Inputs = { {Item='Copper_Wire',Count=50}, {Item='Steel_Ingot',Count=10}, {Item='Platinum_Shealth',Count=15}, {Item='Refined_Gold',Count=2} } },
    ['Mission_Radiator'] = { Inputs = { {Item='Steel_Rebar',Count=10}, {Item='Titanium_Ingot',Count=10}, {Item='Copper_Wire',Count=25} } },
    ['Portable_Tank_Biofuel'] = { Inputs = { {Item='Composites',Count=20}, {Item='Epoxy',Count=30} } },
    ['Shotgun_Casing'] = { Inputs = { {Item='Epoxy',Count=2}, {Item='Refined_Copper',Count=1} } },
    ['Stasis_Bag'] = { Inputs = { {Item='Platinum_Weave',Count=20}, {Item='Electronics',Count=5}, {Item='Gold_Wire',Count=15}, {Item='Rope',Count=5} } },
    ['Glass_Window_Reinforced'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=8}, {Item='Epoxy',Count=4} } },
    ['Glass_Door_Reinforced'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=10}, {Item='Epoxy',Count=6} } },
    ['Choc_Chip_Cookie'] = { Inputs = { {Item='Flour',Count=2}, {Item='Sugar',Count=2}, {Item='Egg',Count=1}, {Item='Seed_Oil',Count=1}, {Item='Cocoa',Count=2} } },
    ['Coconut_Cookie'] = { Inputs = { {Item='Flour',Count=2}, {Item='Sugar',Count=2}, {Item='Coconut_mature',Count=1}, {Item='Seed_Oil',Count=1} } },
    ['Strawberry_Candy'] = { Inputs = { {Item='Sugar',Count=1}, {Item='Strawberry',Count=5} } },
    ['Watermelon_Lollypop'] = { Inputs = { {Item='Sugar',Count=1}, {Item='Watermelon',Count=2} } },
    ['Energy_Bar'] = { Inputs = { {Item='Seed',Count=10}, {Item='Sugar',Count=2}, {Item='Cocoa',Count=2}, {Item='Honey',Count=1}, {Item='Wheat',Count=2} } },
    ['Caramel_Fruit_Tart'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Sugar',Count=3}, {Item='Kiwi_Fruit',Count=2}, {Item='Berry',Count=5}, {Item='Egg',Count=1} } },
    ['Salted_Caramel_Pastry'] = { Inputs = { {Item='Pastry',Count=1}, {Item='Sugar',Count=2}, {Item='Salt',Count=5} } },
    ['Saddle_Basic_Arctic'] = { Inputs = { {Item='Leather',Count=5}, {Item='Fur',Count=25}, {Item='Rope',Count=2} } },
    ['Saddle_Basic_Desert'] = { Inputs = { {Item='Leather',Count=25}, {Item='Fur',Count=5}, {Item='Rope',Count=2} } },
    ['Plough_Steel'] = { Inputs = { {Item='Steel_Ingot',Count=15}, {Item='Epoxy',Count=5}, {Item='Rope',Count=10}, {Item='Wood_Refined',Count=20} } },
    ['Plough_Platinum'] = { Inputs = { {Item='Platinum_Ingot',Count=15}, {Item='Epoxy',Count=5}, {Item='Rope',Count=10}, {Item='Wood_Refined',Count=20} } },
    ['Plough_Titanium'] = { Inputs = { {Item='Titanium_Ingot',Count=15}, {Item='Epoxy',Count=5}, {Item='Rope',Count=10}, {Item='Wood_Refined',Count=20} } },
    ['Attachment_ClayYield_1'] = { Inputs = { {Item='Clay',Count=4}, {Item='Copper_Nail',Count=8} } },
    ['Attachment_ClayYield_2'] = { Inputs = { {Item='Clay',Count=8}, {Item='Carbon_Fiber',Count=1}, {Item='Sledgehammer_Attachment_ClayYield_1',Count=1} } },
    ['Attachment_ScoriaYield_1'] = { Inputs = { {Item='Scoria',Count=4}, {Item='Iron_Nail',Count=8} } },
    ['Attachment_ScoriaYield_2'] = { Inputs = { {Item='Scoria',Count=8}, {Item='Carbon_Fiber',Count=1}, {Item='Sledgehammer_Attachment_ScoriaYield_1',Count=1} } },
    ['Attachment_ObsidianYield_1'] = { Inputs = { {Item='Obsidian',Count=4}, {Item='Steel_Screw',Count=8} } },
    ['Attachment_ObsidianYield_2'] = { Inputs = { {Item='Shaped_Obsidian',Count=4}, {Item='Carbon_Fiber',Count=1}, {Item='Sledgehammer_Attachment_ObsidianYield_1',Count=1} } },
    ['Windmill'] = { Inputs = { {Item='Steel_Ingot',Count=25}, {Item='Stone',Count=50}, {Item='Wood_Refined',Count=50}, {Item='Rope',Count=25} } },
    ['Submachine_Gun'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Titanium_Plate',Count=6}, {Item='Titanium_Ingot',Count=25}, {Item='Epoxy',Count=15}, {Item='Steel_Screw',Count=25}, {Item='Seed_Oil',Count=5} } },
    ['Cow_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Cow_Head',Count=1} } },
    ['Milk_Bucket'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Steel_Screw',Count=15} } },
    ['Milk_Bottle_Glass'] = { Inputs = { {Item='Glass',Count=7} } },
    ['Bull_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Bull_Head',Count=1} } },
    ['Reinforced_Wood_Beam'] = { Inputs = { {Item='Fiber',Count=4}, {Item='Wood',Count=6}, {Item='Beeswax',Count=6} } },
    ['Flamethrower'] = { Inputs = { {Item='Aluminium',Count=25}, {Item='Electronics',Count=5}, {Item='Steel_Screw',Count=20}, {Item='Glass',Count=3} } },
    ['Chocolate_Cake'] = { Inputs = { {Item='Flour',Count=20}, {Item='Sugar',Count=10}, {Item='Egg',Count=2}, {Item='Seed_Oil',Count=2}, {Item='Cocoa',Count=10}, {Item='Butter',Count=1} } },
    ['Coconut_Cake'] = { Inputs = { {Item='Flour',Count=20}, {Item='Sugar',Count=10}, {Item='Egg',Count=2}, {Item='Seed_Oil',Count=2}, {Item='Coconut_mature',Count=2}, {Item='Butter',Count=1} } },
    ['Carrot_Cake'] = { Inputs = { {Item='Flour',Count=20}, {Item='Sugar',Count=10}, {Item='Egg',Count=2}, {Item='Seed_Oil',Count=2}, {Item='Carrot',Count=5}, {Item='Butter',Count=1} } },
    ['Cheese'] = { Inputs = { {Item='Salt',Count=10}, {Item='Bean',Count=3}, {Item='Beeswax',Count=5} } },
    ['Frozen_Wood'] = { Inputs = { {Item='Frozen_Wood',Count=1} } },
    ['Process_Condensed_Exotic'] = { Inputs = { {Item='Condensed_Exotic',Count=1} } },
    ['Rock_Golem_Chair'] = { Inputs = { {Item='Rock_Golem_Head',Count=1}, {Item='Stone',Count=80}, {Item='Rock_Golem_Core',Count=5}, {Item='Rock_Golem_Fragment',Count=5} } },
    ['SurveyTransmitter_NoSnap'] = { Inputs = { {Item='Refined_Metal',Count=8}, {Item='Gold_Wire',Count=4}, {Item='Copper_Wire',Count=8}, {Item='Glass',Count=2} } },
    ['Cream'] = { Inputs = { {Item='Animal_Fat',Count=2} } },
    ['Butter'] = { Inputs = { {Item='Cream',Count=3}, {Item='Salt',Count=3} } },
    ['Strawberries_And_Cream'] = { Inputs = { {Item='Strawberry',Count=4}, {Item='Cream',Count=2} } },
    ['Cheese_Roll'] = { Inputs = { {Item='Cheese',Count=2}, {Item='Dough_Bread',Count=1}, {Item='Butter',Count=1} } },
    ['Cheese_Pizza'] = { Inputs = { {Item='Dough_Flatbread',Count=2}, {Item='Cheese',Count=5}, {Item='Tomato',Count=3} } },
    ['Pavlova'] = { Inputs = { {Item='Cream',Count=5}, {Item='Sugar',Count=5}, {Item='Egg',Count=2}, {Item='Kiwi_Fruit',Count=3} } },
    ['Bacon_Sandwich'] = { Inputs = { {Item='Food_Bread',Count=1}, {Item='Crispy_Bacon',Count=5}, {Item='Butter',Count=3} } },
    ['Coffee_With_Cream'] = { Inputs = { {Item='Coffee',Count=5}, {Item='Cream',Count=3} } },
    ['Calf_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Calf_Head',Count=1} } },
    ['Pastry_Butter'] = { Inputs = { {Item='Butter',Count=1}, {Item='Flour',Count=5} } },
    ['Crispy_Bacon_Butter'] = { Inputs = { {Item='Raw_Bacon',Count=4}, {Item='Butter',Count=1} } },
    ['Homestead_Silo'] = { Inputs = { {Item='Clay_Brick',Count=100}, {Item='Steel_Ingot',Count=30}, {Item='Steel_Screw',Count=25}, {Item='Tree_Sap',Count=40} } },
    ['Homestead_Quilted_Bed'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Wool',Count=30}, {Item='Copper_Nail',Count=50} } },
    ['Chick_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=15}, {Item='Chick_Head',Count=1} } },
    ['Homestead_Farm_Railing'] = { Inputs = { {Item='Rope',Count=3}, {Item='Wood',Count=8} } },
    ['Homestead_Farm_Railing_Gate'] = { Inputs = { {Item='Rope',Count=3}, {Item='Wood',Count=8} } },
    ['Drill_Arrow'] = { Inputs = { {Item='Wood',Count=1}, {Item='Steel_Screw',Count=1}, {Item='Aluminium',Count=1} } },
    ['Organic_Analyzer'] = { Inputs = { {Item='Steel_Ingot',Count=10}, {Item='Electronics',Count=4}, {Item='Glass',Count=15}, {Item='Copper_Wire',Count=16} } },
    ['Mission_Radio'] = { Inputs = { {Item='Platinum_Shealth',Count=20}, {Item='Gold_Wire',Count=35}, {Item='Electronics',Count=5}, {Item='Copper_Wire',Count=25} } },
    ['Homestead_Swing_Chair'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Wool',Count=10}, {Item='Copper_Nail',Count=20}, {Item='Stick',Count=30} } },
    ['Homestead_Soft_Sofa_Single'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Wool',Count=15}, {Item='Copper_Nail',Count=20} } },
    ['Homestead_Soft_Sofa_Double'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Wool',Count=30}, {Item='Copper_Nail',Count=20} } },
    ['MakeshiftRadio'] = { Inputs = { {Item='Wood',Count=14}, {Item='Rope',Count=6}, {Item='Refined_Metal',Count=12} } },
    ['Homestead_Spawn_Blocker_Scarecrow'] = { Inputs = { {Item='Cloth_Head',Count=1}, {Item='Cloth_Arms',Count=1}, {Item='Cloth_Legs',Count=1}, {Item='Stone',Count=10}, {Item='Wood',Count=25}, {Item='Tree_Sap',Count=20}, {Item='Spoiled_Meat',Count=10}, {Item='Fiber',Count=40} } },
    ['Homestead_PlanterBox_SML'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Sulfur',Count=10}, {Item='Dirt',Count=30}, {Item='Steel_Screw',Count=30} } },
    ['Homestead_Water_Tank'] = { Inputs = { {Item='Aluminium',Count=20}, {Item='Wood_Refined',Count=40}, {Item='Steel_Screw',Count=4} } },
    ['Ammo_EDS'] = { Inputs = { {Item='Ammo_Casing',Count=5}, {Item='Synthetic_Enzymes',Count=5}, {Item='Volatile_Substance',Count=1}, {Item='Health_Elixir',Count=2} } },
    ['Homestead_Cabinet'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Copper_Nail',Count=15}, {Item='Refined_Metal',Count=4} } },
    ['Homestead_Cabinet_LRG'] = { Inputs = { {Item='Wood_Refined',Count=50}, {Item='Copper_Nail',Count=30}, {Item='Refined_Metal',Count=8} } },
    ['Homestead_BirdFeeder'] = { Inputs = { {Item='Wood',Count=14}, {Item='Iron_Nail',Count=16}, {Item='Wood_Refined',Count=10}, {Item='Fiber',Count=20} } },
    ['ResearchEquipment_Centrifuge'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Electronics',Count=6}, {Item='Glass',Count=4}, {Item='Copper_Wire',Count=6}, {Item='Gold_Wire',Count=12} } },
    ['ResearchEquipment_Flasks'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Electronics',Count=2}, {Item='Glass',Count=16}, {Item='Copper_Wire',Count=4} } },
    ['ResearchEquipment_Microscope'] = { Inputs = { {Item='Steel_Ingot',Count=6}, {Item='Electronics',Count=6}, {Item='Glass',Count=10}, {Item='Copper_Wire',Count=4}, {Item='Epoxy',Count=8} } },
    ['ResearchEquipment_TestTubes'] = { Inputs = { {Item='Steel_Ingot',Count=2}, {Item='Glass',Count=10}, {Item='Epoxy',Count=16} } },
    ['ResearchEquipment_LabDesk'] = { Inputs = { {Item='Steel_Ingot',Count=16}, {Item='Wood_Refined',Count=25}, {Item='Composites',Count=6} } },
    ['TriangulationBeacon'] = { Inputs = { {Item='Gold_Wire',Count=10}, {Item='Copper_Wire',Count=5}, {Item='Steel_Ingot',Count=4}, {Item='Steel_Screw',Count=4}, {Item='Glass',Count=2} } },
    ['Mission_Explosive_Crafted'] = { Inputs = { {Item='Refined_Metal',Count=4}, {Item='Gunpowder',Count=4}, {Item='Volatile_Substance',Count=5}, {Item='Gold_Wire',Count=8} } },
    ['Mission_Neurotoxic_Aerosol'] = { Inputs = { {Item='Refined_Metal',Count=6}, {Item='Synthetic_Enzymes',Count=8}, {Item='Volatile_Substance',Count=5}, {Item='Gold_Wire',Count=8}, {Item='Health_Elixir',Count=4} } },
    ['Homestead_Sewing_Machine'] = { Inputs = { {Item='Steel_Ingot',Count=20}, {Item='Wood_Refined',Count=20}, {Item='Epoxy',Count=8}, {Item='Steel_Screw',Count=40} } },
    ['Homestead_Ranch_Sign'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Copper_Nail',Count=15} } },
    ['Homestead_Ranch_Gate_Sign'] = { Inputs = { {Item='Wood_Refined',Count=40}, {Item='Copper_Nail',Count=10} } },
    ['Homestead_Vintage_Jar'] = { Inputs = { {Item='Glass',Count=2}, {Item='Refined_Metal',Count=1} } },
    ['Homestead_Honey_Pot'] = { Inputs = { {Item='Clay',Count=3}, {Item='Refined_Metal',Count=1} } },
    ['Juvenile_Rock_Golem_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Rock_Golem_Juvenile_Head',Count=1} } },
    ['Juvenile_Ape_Trophy'] = { Inputs = { {Item='Wood_Refined',Count=30}, {Item='Juvenile_Ape_Head',Count=1} } },
    ['Homestead_Butter_Churn'] = { Inputs = { {Item='Wood_Refined',Count=10}, {Item='Refined_Metal',Count=3}, {Item='Iron_Nail',Count=5} } },
    ['Homestead_Butter_Churn_Large'] = { Inputs = { {Item='Wood_Refined',Count=20}, {Item='Refined_Metal',Count=5}, {Item='Iron_Nail',Count=10} } },
    ['Homestead_Coffee_Grinder'] = { Inputs = { {Item='Steel_Screw',Count=10}, {Item='Refined_Metal',Count=5}, {Item='Wood_Refined',Count=5} } },
    ['Homestead_Weapon_Rack_Single'] = { Inputs = { {Item='Iron_Nail',Count=10}, {Item='Wood_Refined',Count=15} } },
    ['Homestead_Weapon_Rack_Double'] = { Inputs = { {Item='Iron_Nail',Count=20}, {Item='Wood_Refined',Count=35} } },
    ['Homestead_Cheese'] = { Inputs = { {Item='Cheese',Count=2} } },
    ['Homestead_Hanging_Meat'] = { Inputs = { {Item='Dried_Meat_Generic',Count=5} } },
}
return Chunk
